---
title: "Code"
author: "Edna Chiang"
date: "February 24, 2018"
output: html_document
---

### Load packages, scripts, and functions
```{r}
# Loading everything that we'll need
library(ggplot2)
  # This package is for plotting
library(dplyr)
  # This package is for data manipulation
library(grid)
  # This package is for plotting
source('scripts/import_crds.R')
  # This script imports all the crds data into 1 dataframe
source('scripts/import_crds_sep.R')
  # This script imports all the crds data into a list of accessible dataframes unique for each squirrel
source('scripts/bin_crds.R')
  # This script bins our crds data into 15-min intervals
source('scripts/misc.R')
  # This contains misc scripts
    # 1) Calculates standard error
    # 2) Steals plot legend for fancy plotting
set.seed(1)
  # Makes sure our results are reproducible
theme_set(theme_bw())
  # Sets plot backgrounds to white because I think they look nicer
```

### Load Data
```{r}
### Notes:
  # In your working directory, you should have a folder named 'CSV'
  # In your working directory, you should have a file named 'metadata.csv'

crds <- import.crds('CSV', 'metadata.csv')
  # Creates 1 dataframe with all of your CRDS data
  # Click on "crds" in the upper right quadrant of RStudio
    # This will open up a window in your upper left quadrant
    # You can scroll and look at the data here
# crds.all <- import.crds.sep('CSV', 'metadata.csv')
  # Creates a list of all each separate squirrel CRDS data
  # We don't use this list in my written code, so I commented (#) it out
    # If you want to run this line of code, just remove the # in front of the line
```

### Bin Relaitve Time
```{r}
crds.bin <- bin.crds(crds)
  # Bins all of the relative time measurements into 15-min intervals
```

### Summarize by Substrate + ABX
```{r}
# Remove NA's (gavage time; we don't need to plot this)
rem <- which(is.na(crds.bin$Delta))
  # Identifies what Delta values are NA
    # The only NA Delta values are from the gavage time
crds.rem <- crds.bin[-rem,]
  # Removes gavage time from your crds dataframe

# Remove 3982 because it's an outlier
crds.rem <- crds.rem[-which(crds.rem$Number == 3982),]
  # 3982 is a summer inulin abx
  # This was an outlier, so we'll remove it
  # This squirrel had a higher DNA yield than other ABX squirrels

# Summarize
crds.sum <- crds.rem %>%
  group_by(Substrate, Antibiotics, Season, BinTime) %>%
  summarize(Mean = mean(Delta),
            Median = median(Delta),
            SD = sd(Delta),
            SE = se(Delta),
            iqr = IQR(Delta))
  # Summarizes our data by calculating mean, median, standard deviation, standard error, and interquartile range based on Substrate + Antibiotics + Season + Binned Time
  # This creates a new dataframe that we'll use for plotting
```

### Separate by substrate
```{r}
inu.all <- crds.sum[which(crds.sum$Substrate == "Inulin"),]
  # Pull out all inulin

man.all <- crds.sum[which(crds.sum$Substrate == "Mannitol"),]
  # Pull out all mannitol

sal.all <- crds.sum[which(crds.sum$Substrate == "Saline"),]
  # Pull out all saline

ure.all <- crds.sum[which(crds.sum$Substrate == "Urea"),]
  # Pull out all urea
```


### Plot
```{r}
### Plot all individuals
# You'll rarely actually have to use this plot because there's so much going on that it's not very informative
# ggplot(crds.bin, aes(x=BinTime, y=Delta, color=ID)) +
#   geom_line() +
#   geom_point()

### Plot by Substrate + ABX
# You'll rarely actually have to use this plot because there's so much going on that it's not very informative
# ggplot(crds.sum, aes(x=BinTime, y=Mean, color=Substrate)) +
#   geom_line(aes(linetype=Antibiotics)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE))

### Plot Inulin
# Note: legend isn't perfect because of how ggplot does its plotting; you'll have to finagle it in powerpoint or illustrator or something
# There's code farther down this document that'll make a nicer plot
inu.plot <- ggplot(inu.all, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
   geom_point(size=3, shape=21, aes(color=Season, fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3")) +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) +
  ggtitle("Inulin 13C:12C") +
  xlab("Time") +
  ylab("Mean 13C:12C")+
  theme(plot.title=element_text(hjust=0.5))

### Mannitol
# Note: legend isn't perfect because of how ggplot does its plotting; you'll have to finagle it in powerpoint or illustrator or something
# There's code farther down this document that'll make a nicer plot
man.plot <- ggplot(man.all, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
  geom_point(size=3, shape=21, aes(color=Season, fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3")) +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) +
  ggtitle("Mannitol 13C:12C") +
  xlab("Time") +
  ylab("Mean 13C:12C")+
  theme(plot.title=element_text(hjust=0.5))

### Saline
# Note: legend isn't perfect because of how ggplot does its plotting; you'll have to finagle it in powerpoint or illustrator or something
# There's code farther down this document that'll make a nicer plot
sal.plot <- ggplot(sal.all, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
  geom_point(size=3, shape=21, aes(color=Season, fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3")) +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) +
  ggtitle("Saline 13C:12C") +
  xlab("Time") +
  ylab("Mean 13C:12C")+
  theme(plot.title=element_text(hjust=0.5))


## Steal legend
steal.legend <- ggplot(sal.all, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
  geom_point(size=3) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3")) +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) +
  ggtitle("Saline 13C:12C") +
  xlab("Time") +
  ylab("Mean 13C:12C")+
  theme(plot.title=element_text(hjust=0.5))
legend <- g_legend(steal.legend)
```


### Make plots
```{r}
tiff("crds.tiff", width = 11, height = 5.5, units = "in", res = 300)
grid.newpage()
pushViewport(viewport(layout=(grid.layout(1,4, widths=c(1,1,1,0.25), heights=c(1,1,1,1)))))
print(inu.plot, vp=viewport(layout.pos.row=1, layout.pos.col=1))
print(man.plot, vp=viewport(layout.pos.row=1, layout.pos.col=2))
print(sal.plot, vp=viewport(layout.pos.row=1, layout.pos.col=3))
legend$vp <- viewport(layout.pos.row=1, layout.pos.col=4)
grid.draw(legend)
dev.off()
```