---
title: "Code_AllShortReads"
author: "Edna Chiang"
date: "2/8/2022"
output: html_document
---

### Load Packages, scripts, and functions
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
#library(MESS)
#library(pgirmess)
#library(Bolstad2)
library(phyloseq)
library(vegan)
#library(miLineage)
#library(psych)
library(car)
library(reshape2)
#source('scripts/import_crds.R')
#source('scripts/bin_crds.R')
source('scripts/misc.R')
#source('scripts/calc_delta_metrics.R')
source('scripts/simper_pretty.R')
source('scripts/R_krusk.R')
source('scripts/removeTaxa.R')
source('scripts/kaijuCreatePhyseq.R')
set.seed(1)
theme_set(theme_bw())
```



### DON'T RUN - Prepare taxonomic data
```{r}
### Remove taxa in < 3 samples
#removeTaxa('kaiju/all_shortreads/')

### Create phyloseq objects
#kaijuCreatePhyseq('kaiju/all_shortreads/', 'metadata_metag.csv')
```

### Load tax physeq data
```{r}
### Load physeq data
load("kaiju/all_shortreads/use/physeq/phylum.RData")
phy.phy <- physeq
load("kaiju/all_shortreads/use/physeq/class.RData")
cla.phy <- physeq
load("kaiju/all_shortreads/use/physeq/order.RData")
ord.phy <- physeq
load("kaiju/all_shortreads/use/physeq/family.RData")
fam.phy <- physeq
load("kaiju/all_shortreads/use/physeq/genus.RData")
gen.phy <- physeq
load("kaiju/all_shortreads/use/physeq/species.RData")
spe.phy <- physeq

### Melt physeq objects into dataframes
phy.melt <- psmelt(phy.phy)
cla.melt <- psmelt(cla.phy)
ord.melt <- psmelt(ord.phy)
fam.melt <- psmelt(fam.phy)
gen.melt <- psmelt(gen.phy)
spe.melt <- psmelt(spe.phy)


### Import metadata
meta <- read.csv('metadata_metag.csv', header=T)
meta$Season <- ordered(meta$Season, levels=c("Summer", "Winter", "Spring"))
```


### Summarize tax data
```{r}
phy.sum <- phy.melt %>%
  group_by(Season, OTU) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance),
            SE = se(Abundance))
#write.csv(phy.sum, file = "kaiju/all_shortreads/phylum.sum.csv", row.names = F)

cla.sum <- cla.melt %>%
  group_by(Season, OTU) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance),
            SE = se(Abundance))
#write.csv(cla.sum, file = "kaiju/all_shortreads/class.sum.csv", row.names = F)

ord.sum <- ord.melt %>%
  group_by(Season, OTU) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance),
            SE = se(Abundance))
#write.csv(ord.sum, file = "kaiju/all_shortreads/order.sum.csv", row.names = F)

fam.sum <- fam.melt %>%
  group_by(Season, OTU) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance),
            SE = se(Abundance))
#write.csv(fam.sum, file = "kaiju/all_shortreads/family.sum.csv", row.names = F)

gen.sum <- gen.melt %>%
  group_by(Season, OTU) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance),
            SE = se(Abundance))
#write.csv(gen.sum, file = "kaiju/all_shortreads/genus.sum.csv", row.names = F)

spe.sum <- spe.melt %>%
  group_by(Season, OTU) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance),
            SE = se(Abundance))
#write.csv(spe.sum, file = "kaiju/all_shortreads/species.sum.csv", row.names = F)
```



### Sample dist PCoA & PERMANOVA
```{r}
bray.pcoa <- ordinate(physeq=spe.phy, method="PCoA", distance="bray")
sample_data(spe.phy)$Season <- ordered(sample_data(spe.phy)$Season, levels = c("Summer", "Winter", "Spring"))

#tiff("aaas.pcoa.tiff", width=8, height=6, units="in", res=300)
plot_ordination(physeq = spe.phy, ordination = bray.pcoa, axes = c(1,2),
                color = "Season") +
  geom_point(size=10) +
  scale_color_manual(values=c("#00cccc", "#008484", "#004f4f")) +
  ggtitle("CAZyme Profiles") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        plot.title = element_blank())
#dev.off()



### Run PERMANOVA on DESEq Hellinger distance
sampdf <- data.frame(sample_data(spe.phy))
bray <- phyloseq::distance(physeq = spe.phy, method = "bray")
adonis(bray ~ Season, data = sampdf, permutations = 9999)
  # p-value = 2e-04
beta.tax <- betadisper(d = bray, group = sampdf$Season)
p <- permutest(beta.tax)
p$tab
  # 0.412


```



### DNA Yield
```{r}
dna <- read.csv('dna.csv')
dna.c <- dna[which(grepl("CC", dna$Sample) == T),]
dna.c$Metabolism <- "a"
dna.c$Metabolism[which(dna.c$Season == "Winter")] <- "Hibernation"
dna.c$Metabolism[which(dna.c$Season != "Winter")] <- "Active"
dna.c$Metabolism <- ordered(dna.c$Metabolism, levels = c("Active", "Hibernation"))
dna.c$Season <- ordered(dna.c$Season, levels = c("Summer", "Winter", "Spring"))

dna.c.noabx <- dna.c[which(dna.c$Antibiotics == "No Antibiotics"),]


shapiro.test(dna.c$DNA_Yield_.ng.mg.)
  # p-value = 4.583e-08
  # Not Normal
shapiro.test(dna.c.noabx$DNA_Yield_.ng.mg.)
  # p-value = 0.601
  # Normal

summary(aov(formula = DNA_Yield_.ng.mg. ~ Season, data = dna.c))
  # p-value = 0.411
summary(aov(formula = DNA_Yield_.ng.mg. ~ Season, data = dna.c.noabx))
  # p-value = 0.0472*
TukeyHSD(aov(formula = DNA_Yield_.ng.mg. ~ Season, data = dna.c.noabx))
  # Summer-Winter = 0.9023267
  # Summer-Spring = 0.0499387*
  # Winter-Spring = 0.1449934

t.test(formula = DNA_Yield_.ng.mg. ~ Metabolism, data = dna.c.noabx)
  # p-value = 0.3962
```


### Plot - DNA Yield
```{r}
#tiff("dna_yield.noabx.tiff", width = 175, height = 100, units = "mm", res = 400)
ggplot(dna.c.noabx, aes(x=Season, y=DNA_Yield_.ng.mg., fill=Season)) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize = 1.5) +
  scale_fill_manual(name="Season", values=c("#E69F00", "#0072B2", "#00bf8b")) +
  ylab("DNA Yield\n(ng/mg cecal content)") +
  scale_y_continuous(breaks=c(33.0, 66.4, 99.8, 133.2, 166.6, 200.0),
                     limits=c(33, 206)) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.75,
               show.legend = F) +
  theme(plot.title=element_text(hjust=0.5, size=20),
        axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        axis.title.x = element_text(size=20, margin=margin(t=10, r=0, b=0, l=0)),
        axis.title.y = element_text(size=20, margin=margin(t=0, r=10, b=0, l=0)),
        strip.text.x = element_text(size=20),
        strip.text.y = element_text(size=14),
        panel.spacing=unit(1, "lines"),
        legend.title = element_text(size = 18, face="bold"),
        legend.text = element_text(size=16),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
  ) 
#dev.off()
```




### Combine % microbial * DNA yield
```{r}
### Load taxonomic classification
load("kaiju/all_shortreads/use/physeq/phylum.RData")



### Calculate % microbial
phy.microbial <- subset_taxa(physeq, ta1 != "Viruses")
phy.microbial <- subset_taxa(phy.microbial, ta1 != "Unclassified")
microbe.ra <- data.frame(matrix(nrow = 18, ncol = 1))
colnames(microbe.ra) <- "%_Microbial"
microbe.otu <- data.frame(otu_table(phy.microbial))
rownames(microbe.ra) <- colnames(microbe.otu)

for(i in 1:ncol(microbe.otu)) {
  sum.microbe <- sum(microbe.otu[,i])
  microbe.ra[i,] <- sum.microbe
}



### Load DNA
dna <- read.csv('dna.csv')
dna.c <- dna[which(grepl("CC", dna$Sample) == T),]
dna.c$Metabolism <- "a"
dna.c$Metabolism[which(dna.c$Season == "Winter")] <- "Hibernation"
dna.c$Metabolism[which(dna.c$Season != "Winter")] <- "Active"
dna.c$Metabolism <- ordered(dna.c$Metabolism, levels = c("Active", "Hibernation"))
dna.c$Season <- ordered(dna.c$Season, levels = c("Summer", "Winter", "Spring"))
dna.c.noabx <- dna.c[which(dna.c$Antibiotics == "No Antibiotics"),]


### Load % Host DNA from Short Reads
host.dna <- read.csv('hostDNA_shortreads.csv')
colnames(host.dna) <- c("Sample", "%_Host")


### Combine % microbial and DNA yield
microbe.ra$Squirrel <- substr(rownames(microbe.ra),3,5)
microbe.ra$Host_Percentage <- (host.dna$`%_Host` / 100)
microbe.ra$DNAyield <- NA
microbe.ra$Season <- NA
microbe.ra$Metabolism <- NA

for(j in 1:nrow(microbe.ra)){
  row <- which(dna.c.noabx$Squirrel == microbe.ra$Squirrel[j])
  microbe.ra$DNAyield[j] <- dna.c.noabx$DNA_Yield_.ng.mg.[row]
  microbe.ra$Season[j] <- as.character(dna.c.noabx$Season[row])
  microbe.ra$Metabolism[j] <- as.character(dna.c.noabx$Metabolism[row])
}
microbe.ra$Season <- ordered(microbe.ra$Season, c("Summer", "Winter", "Spring"))
microbe.ra$Metabolism <- ordered(microbe.ra$Metabolism, c("Active", "Hibernation"))

microbe.ra$NonHost_DNA_Yield <- (1 - microbe.ra$Host_Percentage) * microbe.ra$DNAyield

microbe.ra$Microbial_DNA_Yield <- (microbe.ra$`%_Microbial` / 100) * microbe.ra$NonHost_DNA_Yield
```

### Test microbial DNA yield
```{r}
### Test Normality
shapiro.test(microbe.ra$Microbial_DNA_Yield)
  # p-value = 0.7821
  # Normal

summary(aov(formula = Microbial_DNA_Yield ~ Season, data = microbe.ra))
  # p-value = 0.26

t.test(formula = Microbial_DNA_Yield ~ Metabolism, data = microbe.ra)
  # p-value = 0.7692

```

### Test host DNA yield
```{r}
### Calculate Host DNA Yield
microbe.ra$Host_DNA_Yield <- microbe.ra$Host_Percentage * microbe.ra$DNAyield



### Test Host DNA Yield
shapiro.test(microbe.ra$Host_DNA_Yield)
  # p-value = 5.961e-08
  # Not Normal

kruskal.test(formula = Host_DNA_Yield ~ Season, data = microbe.ra)
  # p-value = 0.1129
wilcox.test(formula = Host_DNA_Yield ~ Metabolism, data = microbe.ra)



### Test Host DNA Yield Variance
fligner.test(Host_DNA_Yield ~ Season, microbe.ra)
  # p-value = 0.002298*
fligner.test(Host_DNA_Yield ~ Season, microbe.ra, subset = (Season != "Spring") )
  # Summer vs. Winter
  # p-value = 0.005881*
fligner.test(Host_DNA_Yield ~ Season, microbe.ra, subset = (Season != "Winter") )
  # Summer vs. Spring
  # p-value = 0.8869
fligner.test(Host_DNA_Yield ~ Season, microbe.ra, subset = (Season != "Summer") )
  # Winter vs. Spring
  # p-value = 0.005881*
```