---
title: "Multiomics"
author: "Edna Chiang"
date: "4/27/2022"
output: html_document
---

### Load Libraries
```{r}
library(ape)
library(dplyr)
library(dunn.test)
library(ggplot2)
library(grid)
library(gridExtra)
library(phyloseq)
library(picante)
library(pwr)
library(tidyr)
library(vegan)
library(mixOmics)
library(metagMisc)
library(compositions)
library(biomformat)
library(ggbiplot)
library(stringr)
source('scripts/misc.R')
source('scripts/kaijuCreateTable.R')
source('scripts/kaiju_to_OTU_table.R')
source('scripts/kaijuCreateBigOTUtable.R')
theme_set(theme_bw())
set.seed(1)
```

### Prepare Data - DON'T RUN!!!
```{r}
### Prepare kaiju output --> "OTU" table
#kaijuCreateTable('kaiju/all_shortreads/pre-processed/output/', 'kaiju/all_shortreads/kaijuCreateTable_output/')
#kaiju_to_OTU_table('kaiju/all_shortreads/kaijuCreateTable_output/', 'kaiju/all_shortreads/kaiju_to_OTU_table_output/')
#kaiju_big_OTU_table('kaiju/all_shortreads/kaiju_to_OTU_table_output/', 'kaiju/all_shortreads/bigOTU.txt')

# Create final kaiju "OTU" table
#OTU <- read.table('kaiju/all_shortreads/bigOTU.txt', sep = "\t", header = T)
#OTU.dup <- OTU[which(duplicated(OTU$OTU) == T),]
#rownames(OTU) <- OTU$OTU
#OTU <- OTU[,-2]
#write.table(OTU, 'kaiju/all_shortreads/OTU_use.txt')

# Create OTU biom files
OTU <- read.table('kaiju/all_shortreads/OTU_use.txt', sep = " ", header = T)
OTU.sum <- OTU[,-1:-3]
OTU.sum <- OTU.sum[,-4:-9]
OTU.sum <- OTU.sum[,-7:-9]
OTU.sum.rem <- list()
# Remove taxa found in < 3 samples
for(i in 1:nrow(OTU.sum)){
  if(length(which(OTU.sum[i,] == 0) > 3)){
    OTU.sum.rem <- c(OTU.sum.rem, i)
  }
}
# Remove 8805 taxa
OTU.sum.rem <- as.numeric(OTU.sum.rem)
OTU.sum <- OTU.sum[-OTU.sum.rem,]
# Remove taxa with < 10 reads
OTU.sum.rem10 <- list()
for(i in 1:nrow(OTU.sum)){
  if(sum(OTU.sum[i,]) < 11){
    OTU.sum.rem10 <- c(OTU.sum.rem10, i)
  }
}
# Remove 30 taxa
OTU.sum.rem10 <- as.numeric(OTU.sum.rem10)
OTU.sum <- OTU.sum[-OTU.sum.rem10,]
OTU.sum <- OTU.sum[-1,]
  # Remove unclassified
#write.csv(OTU.sum, file = 'multi-omics/OTU.summer.rem.csv')
rownames(OTU.sum) <- 1:nrow(OTU.sum)
OTU.sum.biom <- make_biom(OTU.sum, id = "AllSummer")
#write_biom(OTU.sum.biom, biom_file = 'OTU.sum.biom')

OTU.inu <- OTU.sum[,1:3]
#OTU.inu.rem <- list()
#for(j in 1:nrow(OTU.inu)){
#  if(length(which(OTU.inu[j,] == 0) > 0)){
#    OTU.inu.rem <- c(OTU.inu.rem, j)
#  }
#}
# No taxa to remove
OTU.inu.biom <- make_biom(OTU.inu, id = "InulinSummer")
#write_biom(OTU.inu.biom, biom_file = 'OTU.inu.biom')





# Load KEGG table
KO <- read.table('KEGG/KOtable_norm.tab', header = T, row.names = 1)
KO <- t(KO)
seasonRem <- which(substr(rownames(KO), 1,1) != "S")
KO <- KO[-seasonRem,]
#KO <- KO[,1:25]


# Load metabolomic data
metab <- read.csv('metabolomics/metabolomics_use.csv', row.names = 1)
metab <- t(metab)
metabUse <- c()
for(k in 1:nrow(KO)){
  useRow <- which(substr(rownames(metab),3,5) == rownames(KO)[k])
  metabUse <- c(metabUse, useRow)
}
metab <- metab[metabUse,]
metab <- metab[, (-(ncol(metab)-1) : -ncol(metab) )]
metab <- data.frame(metab)
for(l in 1:ncol(metab)){
  metab[,l] <- as.numeric(metab[,l])
}
# Remove unused metabolites
metab <- metab[,-5]
metab <- metab[,-6:-9]
metab.all.biom <- make_biom(t(metab))
metab.inu.biom <- make_biom(t(metab[1:3,]))
#write_biom(metab.all.biom, biom_file = 'metab.sum.biom')
#write_biom(metab.inu.biom, biom_file = 'metab.inu.biom')


# Load metadata
meta <- read.csv('metadata_metag.csv', row.names = 2)
row.names(meta) <- substr(rownames(meta),3,5)
meta <- meta[-7:-18,]
  # Remove Winter and Spring samples
meta <- meta[,-11]
  # Remove Ketones because NA
meta.inu <- meta[which(meta$Substrate == "Inulin"),]


### Create physeq object
OTU <- read.table('kaiju/all_shortreads/OTU_use.txt', sep = " ", header = T)
OTU.sum <- OTU[,-1:-3]
OTU.sum <- OTU.sum[,-4:-9]
OTU.sum <- OTU.sum[,-7:-9]
OTU.sum.rem <- list()
# Remove taxa found in < 3 samples
for(i in 1:nrow(OTU.sum)){
  if(length(which(OTU.sum[i,] == 0) > 3)){
    OTU.sum.rem <- c(OTU.sum.rem, i)
  }
}
# Remove 8805 taxa
OTU.sum.rem <- as.numeric(OTU.sum.rem)
OTU.sum <- OTU.sum[-OTU.sum.rem,]
# Remove taxa with < 10 reads
OTU.sum.rem10 <- list()
for(i in 1:nrow(OTU.sum)){
  if(sum(OTU.sum[i,]) < 11){
    OTU.sum.rem10 <- c(OTU.sum.rem10, i)
  }
}
# Remove 30 taxa
OTU.sum.rem10 <- as.numeric(OTU.sum.rem10)
OTU.sum <- OTU.sum[-OTU.sum.rem10,]
OTU.sum <- OTU.sum[-1,]
OTU.inu <- OTU.sum[,1:3]
otu.inu <- otu_table(OTU.inu, taxa_are_rows = T)
inu.tax <- rownames(OTU.sum)
inu.tax.split <- strsplit(inu.tax, split = expression("*"), fixed = T)
inu.tax <- data.frame(inu.tax)
inu.tax$Domain <- NA
inu.tax$Phylum <- NA
inu.tax$Class <- NA
inu.tax$Order <- NA
inu.tax$Family <- NA
inu.tax$Genus <- NA
inu.tax$Species <- NA

for(m in 1:length(inu.tax.split)){
  entry <- inu.tax.split[[m]]
  inu.tax$Domain[m] <- entry[1]
  inu.tax$Phylum[m] <- entry[2]
  inu.tax$Class[m] <- entry[3]
  inu.tax$Order[m] <- entry[4]
  inu.tax$Family[m] <- entry[5]
  inu.tax$Genus[m] <- entry[6]
  inu.tax$Species[m] <- entry[7]
}

OTU.sum$ID <- c(1:nrow(OTU.sum))
inu.tax$ID <- NA
for(n in 1:nrow(inu.tax)){
  match <- which(rownames(OTU.sum) == inu.tax[n,1])
  inu.tax$ID[n] <- OTU.sum$ID[match]
}
tax.inu <- tax_table(inu.tax)
taxa_names(tax.inu) <- taxa_names(otu.inu)

samp.inu <- sample_data(meta.inu)
sample_names(samp.inu) <- sample_names(otu.inu)
inu.phy <- merge_phyloseq(otu.inu, tax.inu, samp.inu)
#save(inu.phy, file = 'multi-omics/inulin.phyloseq.RData')
```


### Test mmvec output
```{r}
### Summer
sum.ranks <- read.table('multi-omics/mmvec_summer/latent_dim_3_input_prior_1.00_output_prior_1.00_beta1_0.90_beta2_0.95_ranks.txt', sep = "\t", header = T, row.names = 1)
#sum.ranks.use <- clrInv(sum.ranks)


### Inulin
inu.ranks <- read.table('multi-omics/mmvec_inulin/latent_dim_3_input_prior_1.00_output_prior_1.00_beta1_0.90_beta2_0.95_ranks.txt', sep = "\t", header = T, row.names = 1)
#inu.ranks.use <- clrInv(inu.ranks)
inu.microbe.ord <- read.table('multi-omics/mmvec_inulin/inu_ord_microbes.txt', sep = "\t", header = F, row.names = 1)
inu.metab.ord <- read.table('multi-omics/mmvec_inulin/inu_ord_metab.txt', sep = "\t", header = F, row.names = 1)

inu.ord <- read.table('multi-omics/mmvec_inulin/latent_dim_3_input_prior_1.00_output_prior_1.00_beta1_0.90_beta2_0.95_ordination.txt', sep = "\t")
```

### Pull out top co-occurence probabilities
```{r}
top.prob <- data.frame(matrix(nrow = nrow(inu.ranks), ncol = 11))
for(o in 1:nrow(inu.ranks)){
  top <- sort(abs(inu.ranks[o,]), decreasing = T)[1:10]
  names <- colnames(top)
  top.prob[o,1] <- rownames(inu.ranks)[o]
  top.prob[o, 2:11] <- names
}

top.unique <- list()
for(p in 2:ncol(top.prob)){
  topTax <- as.character(unique(top.prob[p,2:11]))
  top.unique <- as.character(append(top.unique, topTax))
  top.unique <- unique(top.unique)
}
top.unique <- na.omit(top.unique)

prob.use <- data.frame(matrix(nrow = nrow(inu.ranks), ncol = length(top.unique)))
rownames(prob.use) <- rownames(inu.ranks)
colnames(prob.use) <- top.unique
for(q in 1:length(top.unique)){
  match <- which(colnames(inu.ranks) == top.unique[q])
  prob.use[,q] <- as.numeric(inu.ranks[,match])
}



### Make phyloseq object
colnames(prob.use) <- substr(colnames(prob.use),2,10)
prob.otu <- otu_table(t(prob.use), taxa_are_rows = T)
load('multi-omics/inulin.phyloseq.RData')
inu.tax.table <- data.frame(tax_table(inu.phy))
rownames(inu.tax.table) <- inu.tax.table$ta9
numID <- inu.tax.table$ta9
numID <- str_replace_all(numID, pattern = " ", replacement = "")
inu.tax.table <- tax_table(inu.tax.table)
taxa_names(inu.tax.table) <- numID
prob.phy <- merge_phyloseq(prob.otu, inu.tax.table)
#save(prob.phy, file = 'multi-omics/mmvec_inulin/top_prob_taxa_phy.RData')


# Save taxa names
prob.taxa <- data.frame(tax_table(prob.phy))
#write.table(prob.taxa, file = 'multi-omics/mmvec_inulin/top_prob_taxa.txt', sep = "\t")
rename <- prob.taxa$ta8
rename[12] <- "Kribbella"
rename[15] <- "Bacteroidales"
rename[17] <- "Prevotella"
rename[18] <- "Flavonifractor"
rename[22] <- "Clostridiales"
prob.taxa$Name <- rename
prob.taxa <- tax_table(prob.taxa)
taxa_names(prob.taxa) <- taxa_names(prob.otu)
colnames(prob.taxa) <- c("Full", "Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species", "ID", "Taxon")
prob.phy <- merge_phyloseq(prob.otu, prob.taxa)
#save(prob.phy, file = 'multi-omics/probability.phyloseq.RData')

```

### Plot co-occurrence probability heatmap
```{r}
# Colors taken from RColorBrewer Palette = RdBu

tiff("multi-omics_hm.tiff", width=6.5, height=6.25, units="in", res=600)
plot_heatmap(prob.phy, sample.order = c("Fructose", "Glucose", "Acetate", "Butyrate", "Lactate"), taxa.label = "Taxon", taxa.order = c(10981, 10817, 10263, 9494, 9168, 8863, 8742, 8467, 7637, 7628, 7199, 5761, 5381, 5145, 4681, 3977, 3949, 1959, 937, 565, 57, 7)) +
  geom_tile(colour="gray40") +
  scale_y_discrete(labels=c("Candidatus Wallbacteria bacterium HGW-Wallbacteria-1", "Thermodesulfobacteriales bacterium", "Lentisphaerae bacterium GWF2_49_21", "Spiroplasma taiwanense", "Glycomyces xiaoerkulensis", "Raoultibacter timonensis", "Kribbella", "Francisella uliginis", "Rhodobacteraceae bacterium RKSG542", "Marinicauda sp. WD6-1", "Zymomonas mobilis", "Flavobacteriales bacterium 34_180_T64", "Niastella populi", "Prevotella sp. HMSC069G02", "Pseudarcicella hirudinis", "Prevotella", "Bacteroidales", "Peptoniphilus sp. ING2-D1G", "Butyrivibrio sp. M55", "Butyrivibrio sp. AE3009", "Flavonifractor", "Clostridiales")) +
  xlab("Metabolite") + ylab("Taxon") +
  scale_fill_gradientn(name="Co-occurence\nProbability",
                       colours = c("#053061", "#2166ac", "#4393c3", "#92c5de", "#d1e5f0", "#f7f7f7", "#fddbc7", "#f4a582", "#d6604d", "#b2182b", "#67001f"), 
                       limits = c(-3, 3), breaks = c(-3, -2, -1, 0, 1, 2, 3)) +
  theme(axis.text.x = element_text(size=10, angle=40, hjust=1, vjust=1.15),
        axis.text.y = element_text(size=9),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.border=element_blank(),
        axis.title.x = element_text(size=12, face = "bold"),
        axis.title.y = element_text(size=12, face = "bold"),
        legend.title = element_text(size=10, face = "bold"),
        legend.text = element_text(size=10),
        plot.margin = margin(t=0, r=0, b=0, l=0)) +
  guides(fill = guide_colorbar(barheight = unit(4,"in"),
                               frame.colour="black",
                               frame.linewidth=1))
  
  
dev.off()


```

### Biplot
```{r}
biplot(x = inu.microbe.ord[2:100,1:2], y = inu.metab.ord[,1:2], xlab = "Comp.1 (70.03%)",
       ylab = "Comp.2 (29.92%)", xlim = c(-0.93, 0.30), ylim = c(-0.30, 0.30)) 
```


### Load Data
```{r}
# Load KEGG table
KO <- read.table('KEGG/KOtable_norm.tab', header = T, row.names = 1)
KO <- t(KO)
seasonRem <- which(substr(rownames(KO), 1,1) != "S")
KO <- KO[-seasonRem,]
#KO <- KO[,1:25]

# Load metabolomic data
metab <- read.csv('metabolomics/metabolomics_use.csv', row.names = 1)
metab <- t(metab)
metabUse <- c()
for(i in 1:nrow(KO)){
  useRow <- which(substr(rownames(metab),3,5) == rownames(KO)[i])
  metabUse <- c(metabUse, useRow)
}
metab <- metab[metabUse,]
metab <- metab[, (-(ncol(metab)-1) : -ncol(metab) )]
metab <- data.frame(metab)
for(j in 1:ncol(metab)){
  metab[,j] <- as.numeric(metab[,j])
}

# Load metadata
meta <- read.csv('metadata_metag.csv', row.names = 2)
row.names(meta) <- substr(rownames(meta),3,5)
meta <- meta[-7:-18,]
  # Remove Winter and Spring samples
meta <- meta[,-11]
  # Remove Ketones because NA

# Load CRDS data
#load('crds.use.Rdata')

# Combine data into list
data <- list(KO = KO, metabolomics = metab)


### Pull out just Inulin squirrels
metab.inu <- metab[which(substr(rownames(metab),1,1) == "I"),]
KO.inu <- KO[1:3,]
data.inu <- list(KO = KO.inu, metabolomics = metab.inu)


```

### RCC - Initial Analysis
```{r}
X11()
imgCor(KO, metab)



### Tune rCCA
grid1 <- seq(0.001, 0.2, length = 10) 
grid2 <- seq(0.001, 0.2, length = 10)

# Run RCC to optimize
#tune_rcc <- tune.rcc(KO, metab, grid1 = grid1, grid2 = grid2, validation = "loo")

# Pull out optimal lambda values
#optl1 <- tune_rcc$opt.lambda1
#optl2 <- tune_rcc$opt.lambda2

# Save optimized rCCA
#rcc.opt <- rcc(KO, metab, method = "ridge", lambda1 = optl1, lambda2 = optl2)




### Shrinkage Method
rcc.shrink <- rcc(KO, metab, method = "shrinkage")







### Select # components
plot(rcc.opt, type = "barplot", main = "Cross Validation")
plot(rcc.shrink, type = "barplot", main = "Shrinkage")





### Plot models
plotIndiv(rcc.opt, comp = 1:2, rep.space = "XY-variate", legend = T)
plotArrow(rcc.opt)

plotIndiv(rcc.shrink, comp = 1:2, rep.space = "XY-variate", legend = T)
plotArrow(rcc.shrink)

plotVar(rcc.opt, var.names = c(T, T), cutoff = 0.5)
plotVar(rcc.shrink, var.names = c(T, T), cutoff = 0.5)




### Network Plot
X.11()
network(rcc.opt, comp = 1:2, interactive = F, lwd.edge = 2, cutoff = 0.5)


network(rcc.shrink, comp = 1:2, interactive = F, lwd.edge = 2, cutoff = 0.5)





### CIM plot
X11()
cim(rcc.opt, comp = 1:2, xlab = "KOIDs", ylab = "Metabolites")

X11()
cim(rcc.shrink, comp = 1:2, xlab = "KOIDs", ylab = "Metabolites")

```


### Preliminary analysis (pre-sPLS)
```{r}
# http://mixomics.org/case-studies/spls-liver-toxicity-case-study/

# How many components to use?
pca.ko <- pca(KO[,1:67], ncomp = 6, center = TRUE, scale = TRUE)
  # Selected first 67 to test because they don't have NA's
pca.metab <- pca(metab, ncomp = 6, center = TRUE, scale = TRUE)
plot(pca.ko)
  # Component 1
  # Not much of an elbow
plot(pca.metab)
  # Component 1

# Assess clustering of samples
plotIndiv(pca.ko, comp = c(1, 2))
plotIndiv(pca.metab, comp = c(1, 2))

```
### Pairwise PLS
```{r}
# Current n is too small to perf or tune spls
# http://mixomics.org/case-studies/spls-liver-toxicity-case-study/


pls1 <- spls(data[["KO"]][,1:67], data[["metabolomics"]])




#list.keepX = c(25,25)
#list.keepY = c(10,10)
#pls1 <- spls(data.inu[["KO"]], data.inu[["metabolomics"]], keepX = list.keepX, keepY = list.keepY)

plotVar(pls1, cutoff = 0.5, title = "KO vs. Metabolomics", style = 'graphics')
plotIndiv(pls1, group = meta$Substrate, legend = T)
plotArrow(pls1, group = meta$Substrate)
# Calculate correlation of KO and metabolomics
cor(pls1$variates$X, pls1$variates$Y)
```

### ONLY FOR SEASONAL COMPARISON - DIABLO Model
```{r}
# X = data (KO and metabolomics)
# Y = season


design = matrix(0.1, ncol = length(data), nrow = length(data),
                dimnames = list(names(data), names(data)))
diag(design) <- 0

basic.diablo.model <- block.splsda(X = data, Y = Y, ncomp = 5, design = design)

final.diablo.model <- block.splsda(X = data, Y = Y, design = design)

### Plot
plotDiablo(final.diablo.model, ncomp = 1)
plotIndiv(final.diablo.model, legend = T)
plotArrow(final.diablo.model, legend = T)
plotVar(final.diablo.model, style = 'graphics', legend = T)
circosPlot(final.diablo.model, cutoff = 0.7, line = TRUE, size.labels = 2)
#network(final.diablo.model, cutoff = 0.4)
plotLoadings(final.diablo.model, comp = 2, contrib = 'max', method = 'median')
```
