---
title: "Identify Outliers"
author: "Edna Chiang"
date: "1/17/2022"
output: html_document
---

### Load Packages, scripts, and functions
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
library(MESS)
library(pgirmess)
library(Bolstad2)
library(phyloseq)
library(psych)
library(car)
source('scripts/misc.R')
set.seed(1)
theme_set(theme_bw())
```

### Load Data
```{r}
load('crds.norm.RData')
load('crds.use.Rdata')
meta <- read.csv('metadata.csv')
```

### Prepare CRDS data
```{r}
# Add metadata
crds.use[, colnames(meta)[3:ncol(meta)]] <- NA
for(i in 1:nrow(crds.use)){
  meta.row <- which(meta$ID == crds.use$ID[i])
  crds.use[i, 7:ncol(crds.use)] <- meta[meta.row, 3:ncol(meta)]
}

# Calculate square root of AUC
crds.use$AUC <- as.numeric(crds.use$AUC)
minAUC <- min(crds.use$AUC)
crds.use$AUC_sqrt <- crds.use$AUC + (minAUC * -1)
crds.use$AUC_sqrt <- sqrt(crds.use$AUC_sqrt)

# Convert to numeric
crds.use$AvgDelta <- as.numeric(crds.use$AvgDelta)
crds.use$MaxD <- as.numeric(crds.use$MaxD)
crds.use$MaxSlope <- as.numeric(crds.use$MaxSlope)
crds.use$AUC <- as.numeric(crds.use$AUC)
crds.use$AUC_sqrt <- as.numeric(crds.use$AUC_sqrt)
crds.use$Baseline <- as.numeric(crds.use$Baseline)


# Order categorical variables
crds.use$Season <- ordered(crds.use$Season, levels = c("Summer", "Winter", "Spring"))
crds.use$Sex <- ordered(crds.use$Sex, levels = c("Female", "Male"))
crds.use$Antibiotics <- ordered(crds.use$Antibiotics, levels = c("No", "Yes"))
crds.use$Substrate <- ordered(crds.use$Substrate, levels = c("Inulin", "Saline"))
crds.use$Diet <- ordered(crds.use$Diet, levels = c("1", "2"))

# Remove outliers
crds.rem <- crds.use[-which(crds.use$ID == "S23"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S37"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S60"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W43"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W20"),]
  # This is due to odd metagenome
crds.rem <- crds.rem[-which(crds.rem$ID == "W50"),]


# Separate by substrate
crds.inu <- crds.rem[which(crds.rem$Substrate == "Inulin"),]
crds.sal <- crds.rem[which(crds.rem$Substrate == "Saline"),]

# Separate by substrate + ABX
crds.inu.abx <- crds.inu[which(crds.inu$Antibiotics == "Yes"),]
crds.inu.noabx <- crds.inu[which(crds.inu$Antibiotics == "No"),]
crds.sal.abx <- crds.sal[which(crds.sal$Antibiotics == "Yes"),]
crds.sal.noabx <- crds.sal[which(crds.sal$Antibiotics == "No"),]

# Separate by substrate + season
crds.inu.s <- crds.inu[which(crds.inu$Season == "Summer"),]
crds.inu.w <- crds.inu[which(crds.inu$Season == "Winter"),]
crds.inu.p <- crds.inu[which(crds.inu$Season == "Spring"),]
crds.sal.s <- crds.sal[which(crds.sal$Season == "Summer"),]
crds.sal.w <- crds.sal[which(crds.sal$Season == "Winter"),]
crds.sal.p <- crds.sal[which(crds.sal$Season == "Spring"),]

```



### Test Baseline
```{r}
### All ###
res <- resid(lm(Baseline ~ Season, crds.rem))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p-value = 0.5284
  # Normal
summary(aov(Baseline ~ Season + Diet + Antibiotics + Substrate + Season*Diet + Season*Antibiotics + Antibiotics*Sex, crds.rem))
  # Season p < 2e-16
  # Diet p = 1.12e-08
  # Antibiotics p = 0.000358
  # Substrate = 0.082294
  # Sex = 0.503941
  # Season:Diet = 1.28e-05
  # Season:Antibiotics = 0.052905
  # Antibiotics:Sex = 0.040027
TukeyHSD(aov(Baseline ~ Season + Diet + Antibiotics + Substrate + Season*Diet + Season*Antibiotics + Antibiotics*Sex, crds.rem), conf.level = 0.95)
  # Season
    # Summer-Winter adj p = 0, CI = 3.757269 - 5.232897
    # Summer-Spring adj p = 0, CI = 1.748950 - 3.197562
    # Spring-Winter adj p = 7e-07, CI = 1.305231 - 2.738423
  # Diet
    # 1-2 adj p = 0, CI = 1.068405 - 2.071874
  # Antibiotics
    # No-Yes adj p = 0.0005154, CI = 0.4104679 - 1.398133
  # Substrate
    # Inulin-Saline adj p = 0.0830163, CI = -0.9291451 - 0.05852041
  # Sex
    # Female-Male adj p = 0.5204363, CI = -0.6547183 - 0.3346663
  # Season:Diet
    # Summer:1-Winter:1 adj p = 0, CI = 3.5868458 - 5.7705237
    # Summer:1-Spring:1 adj p = 0.4817443, CI = -0.4918827 - 2.0177852
    # Summer:1-Summer:2 adj p = 0.4966403, CI = -0.5331201 - 2.1325738
    # Summer:1-Winter:2 adj p = 0, CI = 3.6362841 - 6.6902201
    # Summer:1-Spring:2 adj p = 0, CI = 3.0190674 - 5.2912685
    # Spring:1-Winter:1 adj p = 0, CI = 2.7180859 - 5.1133810
    # Summer:2-Winter:1 adj p = 0, CI = 2.5998049 - 5.1581109
    # Winter:1-Winter:2 adj p = 0.9282411, CI = -0.9957646 - 1.9648994
    # Spring:2-Winter:1 adj p = 0.7064592, CI = -1.5961192 - 0.5490856
    # Summer:2-Spring:1 adj p = 0.9999996, CI = -1.4575952 - 1.3840440
    # Spring:1-Winter:2 adj p = 0, CI = 2.7959696 - 6.0046321
    # Spring:1-Spring:2 adj p = 0, CI = 2.1540843 - 4.6303491
    # Summer:2-Winter:2 adj p = 0, CI = 2.6974666 - 6.0295839
    # Summer:2-Spring:2 adj p = 0, CI = 2.0383061 - 4.6725762
    # Spring:2-Winter:2 adj p = 0.3781155, CI = -0.5051888 - 2.5213571
  # Season:Antibiotics
    # Summer:No-Winter:No adj p = 0, CI = 3.76444322 - 6.24423299
    # Summer:No-Spring:No adj p = 0.0000031, CI = 1.9104995 - 3.62615516
    # Summer:No-Summer:Yes adj p = 0.0658636, CI = -0.04870372 - 2.54135222
    # Summer:No-Winter:Yes adj p = 0, CI = 3.86799480 - 6.39891964
    # Summer:No-Spring:Yes adj p = 0, CI = 2.48939308 - 4.96918285
    # Spring:No-Winter:No adj p = 0.0000005, CI = 1.37818295 - 3.81328816
    # Summer:Yes-Winter:No adj p = 0, CI = 2.46298588 - 5.05304183
    # Winter:No-Winter:Yes adj p = 0.9996598, CI = -1.13634330 - 1.39458153
    # Spring:Yes-Winter:No adj p = 0.0403404, CI = 0.03515526 - 2.51494503
    # Summer:Yes-Spring:No adj p = 0.0933025, CI = -0.11137490 - 2.43593150
    # Spring:No-Winter:Yes adj p = 0.0000003, CI = 1.48127510 - 3.96843424
    # Spring:No-Spring:Yes adj p = 0.0258917, CI = 0.10313281 - 2.53823802
    # Summer:Yes-Winter:Yes adj p = 0, CI = 2.56760531 - 5.20666063
    # Summer:Yes-Spring:Yes adj p = 0.0000062, CI = 1.18793574 - 3.77799168
    # Spring:Yes-Winter:Yes adj p =0.0211397, CI = 0.13870684 - 2.66963167
  # Antibiotics:Sex
    # No:Female-Yes:Female adj p = 0.5288121, CI = -0.4306366 - 1.3472318
    # No:Female-No:Male adj p = 0.3148323, CI = -1.4894694 - 0.3079084
    # No:Female-Yes:Male adj p = 0.1543947, CI = -0.1921196 - 1.8073370
    # Yes:Female-No:Male adj p = 0.0113547, CI = -1.9150007 - 0.1831555
    # Yes:Female-Yes:Male adj p = 0.7782444, CI = -0.6210686 - 1.3196909
    # No:Male-Yes:Male adj p = 0.0020091, CI = 0.4190657 - 2.3777128





### By Season ###
crds.s <- crds.rem[which(crds.rem$Season == "Summer"),]
crds.w <- crds.rem[which(crds.rem$Season == "Winter"),]
crds.p <- crds.rem[which(crds.rem$Season == "Spring"),]

# Summer
res <- resid(lm(Baseline ~ Antibiotics, crds.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Antibiotics + Substrate + Sex, crds.s))
  # Antibiotics p = 0.0394
  # Substrate p = 0.1352
  # Sex = 0.8551
TukeyHSD(aov(Baseline ~ Antibiotics + Substrate + Sex, crds.s))
  # Antibiotics
    # Yes - No adj p = 0.0394476, CI = -2.11751 - -0.05801414
  # Substrate
    # Saline - Inulin adj p = 0.1365095, CI = -0.2630195 - 1.789313 
  # Sex
    # Male - Female adj p = 0.8586166, CI = -0.9681393 - 1.151501

# Winter
res <- resid(lm(Baseline ~ Antibiotics, crds.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Antibiotics + Substrate + Sex, crds.w))
  # No Sig


# Spring
res <- resid(lm(Baseline ~ Antibiotics, crds.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Antibiotics + Antibiotics*Substrate + Antibiotics*Sex, crds.p))
  # Antibiotics p = 0.000164
  # Substrate p = 0.633626
  # Sex p = 0.980349
  # Antibiotics:Substrate p = 0.043134
  # Antibiotics:Sex p = 0.012671
TukeyHSD(aov(Baseline ~ Antibiotics + Antibiotics*Substrate + Antibiotics*Sex, crds.p))
  # Antibiotics
    # Yes - No adj p = 0.000164, CI = -4.093812 - -1.535565
  # Substrate
    # Saline - Inulin adj p = 0.6338755, CI = -0.9818493 - 1.576397
  # Sex
    # Male - Female adj p = 0.9813636, CI = -1.315529 - 1.285958
  # Antibiotics:Substrate
    # Yes:Inulin - No:Inulin adj p = 0.0005620, CI = -6.4470696 - -1.68859627
    # No:Saline - No:Inulin adj p = 0.6740001, CI = -3.3461172 - 1.41235611
    # Yes:Saline - No:Inulin adj p = 0.0596263, CI = -4.8765289 - 0.07624711
    # No:Saline - Yes:Inulin adj p = 0.0078344, CI = 0.7217157 - 5.48018903
    # Yes:Saline- Yes:Inulin adj p = 0.2676078, CI = -0.8086960 - 4.14408002
    # Yes:Saline - No:Saline adj p = 0.3930039, CI = -3.9096484 - 1.04312764
  # Antibiotics:Sex
    # Yes:Female - No:Female adj p = 0.8653823, CI = -3.5643841 - 2.0154204
    # No:Male - No:Female adj p = 0.2537241, CI = -0.8279603 - 4.4387045 
    # Yes:Male - No:Female adj p = 0.1232221, CI = -5.2741028 - 0.4722996
    # No:Male - Yes:Female adj p = 0.0174139, CI = 0.3863062 - 4.7734018
    # Yes:Male - Yes:Female adj p = 0.2874963, CI = -4.1028078 - 0.8499682
    # Yes:Male - No:Male adj p = 0.0002574, CI = -6.5048347 - -1.9077128 
summary(aov(Baseline ~ Antibiotics + Diet + Substrate + Sex, crds.p))
TukeyHSD(aov(Baseline ~ Antibiotics + Diet + Substrate + Sex, crds.p))



### By Season + Antibiotics ###
crds.s.noabx <- crds.s[which(crds.s$Antibiotics == "No"),]
crds.s.abx <- crds.s[which(crds.s$Antibiotics == "Yes"),]
crds.w.noabx <- crds.w[which(crds.w$Antibiotics == "No"),]
crds.w.abx <- crds.w[which(crds.w$Antibiotics == "Yes"),]
crds.p.noabx <- crds.p[which(crds.p$Antibiotics == "No"),]
crds.p.abx <- crds.p[which(crds.p$Antibiotics == "Yes"),]

# Summer No ABX
res <- resid(lm(Baseline ~ Substrate, crds.s.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Substrate + Sex, crds.s.noabx))
  # Substrate p = 0.523
  # Sex p = 0.547

# Summer ABX
res <- resid(lm(Baseline ~ Substrate, crds.s.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Substrate + Sex, crds.s.abx))
  # Substrate p = 0.0292
  # Sex = 0.2049
TukeyHSD(aov(Baseline ~ Substrate + Sex, crds.s.abx))
  # Saline - Inulin adj p = 0.0292041, CI = 0.1304445 - 1.873555
  # Male - Female adj p = 0.2095546, CI = -1.551012 - 0.3978453

# Winter No ABX
res <- resid(lm(Baseline ~ Substrate, crds.w.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Substrate*Sex, crds.w.noabx))
  # Substrate p = 0.1177
  # Sex = 0.1746
  # Substrate:Sex = 0.0307

# Winter ABX
res <- resid(lm(Baseline ~ Substrate, crds.w.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Not Normal
kruskal.test(Baseline ~ Substrate, crds.w.abx)
  # p = 0.2232
kruskal.test(Baseline ~ Sex, crds.w.abx)
  # p = 0.2232


# Spring No ABX
  # Note: Not n = 3 for each group, so the stats don't really mean anything
res <- resid(lm(Baseline ~ Substrate, crds.p.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Substrate + Sex , crds.p.noabx))
  # Substrate p = 0.3273
  # Sex = 0.0746
TukeyHSD(aov(Baseline ~ Substrate + Sex , crds.p.noabx))
  # Saline - Inulin adj p = 0.3272579, CI = -3.047856 - 1.110713
  # Male - Female adj p = 0.0885661, CI = -0.3478459 - 4.254846 

# Spring No ABX
res <- resid(lm(Baseline ~ Substrate, crds.p.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
summary(aov(Baseline ~ Substrate + Sex , crds.p.abx))
  # Substrate p = 0.0555
  # Diet p = 0.0861
TukeyHSD(aov(Baseline ~ Substrate + Sex , crds.p.abx))
  # Saline - Inulin adj p = 0.0555378, CI = -0.04784369 - 3.386891
  # Male - Female adj p = 0.0868065, CI = -3.180826 - 0.2539094




### By Season + Antibiotics + Substrate
crds.s.noabx.inu <- crds.s.noabx[which(crds.s.noabx$Substrate == "Inulin"),]
#crds.w.noabx.inu <- crds.w.noabx[which(crds.w.noabx$Substrate == "Inulin"),]
crds.p.noabx.inu <- crds.p.noabx[which(crds.p.noabx$Substrate == "Inulin"),]
crds.s.noabx.sal <- crds.s.noabx[which(crds.s.noabx$Substrate == "Saline"),]
crds.w.noabx.sal <- crds.w.noabx[which(crds.w.noabx$Substrate == "Saline"),]
#crds.p.noabx.sal <- crds.p.noabx[which(crds.p.noabx$Substrate == "Saline"),]

#crds.s.abx.inu <- crds.s.abx[which(crds.s.abx$Substrate == "Inulin"),]
crds.w.abx.inu <- crds.w.abx[which(crds.w.abx$Substrate == "Inulin"),]
crds.p.abx.inu <- crds.p.abx[which(crds.p.abx$Substrate == "Inulin"),]
#crds.s.abx.sal <- crds.s.abx[which(crds.s.abx$Substrate == "Saline"),]
#crds.w.abx.sal <- crds.w.abx[which(crds.w.abx$Substrate == "Saline"),]
crds.p.abx.sal <- crds.p.abx[which(crds.p.abx$Substrate == "Saline"),]


# Summer No ABX Inulin
res <- resid(lm(Baseline ~ Sex, crds.s.noabx.inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
t.test(Baseline ~ Sex , crds.s.noabx.inu)
  # Substrate p = 0.9418

# Spring No ABX Inulin
res <- resid(lm(Baseline ~ Sex, crds.p.noabx.inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
t.test(Baseline ~ Sex , crds.p.noabx.inu)
  # Substrate p = 0.07508
  # CI = -4.1991619 - 0.3141619

# Summer No ABX Saline
res <- resid(lm(Baseline ~ Sex, crds.s.noabx.sal))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
t.test(Baseline ~ Sex , crds.s.noabx.sal)
  # Substrate p = 0.4609

# Winter No ABX Saline
res <- resid(lm(Baseline ~ Sex, crds.w.noabx.sal))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
t.test(Baseline ~ Sex , crds.w.noabx.sal)
  # Substrate p = 0.4405

# Winter ABX Inulin
res <- resid(lm(Baseline ~ Sex, crds.w.abx.inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
t.test(Baseline ~ Sex , crds.w.abx.inu)
  # Substrate p = 0.7221

# Spring ABX Inulin
res <- resid(lm(Baseline ~ Sex, crds.p.abx.inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
t.test(Baseline ~ Sex , crds.p.abx.inu)
  # Substrate p = 0.4827

# Spring ABX Saline
res <- resid(lm(Baseline ~ Sex, crds.p.abx.sal))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
t.test(Baseline ~ Sex , crds.p.abx.sal)
  # Substrate p = 0.1635
```



### DNA Concentration
```{r}
dna <- read.csv("dna.csv", header=T)

# Pull out content samples
cc <- dna.con <- dna[which(substr(dna$Sample,1,2) == "CC"),]

# Separate
dna.inu <- dna.con[which(dna.con$Substrate == "Inulin"),]
dna.sal <- dna.con[which(dna.con$Substrate == "Saline"),]
dna.inu.s <- dna.inu[which(dna.inu$Season == "Summer"),]
dna.inu.w <- dna.inu[which(dna.inu$Season == "Winter"),]
dna.inu.p <- dna.inu[which(dna.inu$Season == "Spring"),]
dna.sal.s <- dna.sal[which(dna.sal$Season == "Summer"),]
dna.sal.w <- dna.sal[which(dna.sal$Season == "Winter"),]
dna.sal.p <- dna.sal[which(dna.sal$Season == "Spring"),]
```


### Find outliers
```{r}
### Boxplot - baseline
ggplot(base.inu.s, aes(x = Antibiotics, y = Delta, fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(base.inu.w, aes(x = Antibiotics, y = Delta, fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(base.inu.p, aes(x = Antibiotics, y = Delta, fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(base.sal.s, aes(x = Antibiotics, y = Delta, fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(base.sal.w, aes(x = Antibiotics, y = Delta, fill = Antibiotics)) +
  geom_boxplot()
  # 2 ABX
ggplot(base.sal.p, aes(x = Antibiotics, y = Delta, fill = Antibiotics)) +
  geom_boxplot()


### Boxplot - AUC
ggplot(crds.inu.s, aes(x = Antibiotics, y = AUC_sqrt, fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(crds.inu.w, aes(x = Antibiotics, y = AUC_sqrt, fill = Antibiotics)) +
  geom_boxplot()
ggplot(crds.inu.p, aes(x = Antibiotics, y = AUC_sqrt, fill = Antibiotics)) +
  geom_boxplot()
  # 2 ABX
ggplot(crds.sal.s, aes(x = Antibiotics, y = AUC_sqrt, fill = Antibiotics)) +
  geom_boxplot()
ggplot(crds.sal.w, aes(x = Antibiotics, y = AUC_sqrt, fill = Antibiotics)) +
  geom_boxplot()
  # 1 No ABX
  # 2 ABX
ggplot(crds.sal.p, aes(x = Antibiotics, y = AUC_sqrt, fill = Antibiotics)) +
  geom_boxplot()


### Boxplot - MaxD
ggplot(d.inu.s, aes(x = Antibiotics, y = MaxD, fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(d.inu.w, aes(x = Antibiotics, y = MaxD, fill = Antibiotics)) +
  geom_boxplot()
ggplot(d.inu.p, aes(x = Antibiotics, y = MaxD, fill = Antibiotics)) +
  geom_boxplot()
  # 2 ABX
ggplot(d.sal.s, aes(x = Antibiotics, y = MaxD, fill = Antibiotics)) +
  geom_boxplot()
ggplot(d.sal.w, aes(x = Antibiotics, y = MaxD, fill = Antibiotics)) +
  geom_boxplot()
  # 1 No ABX
  # 2 ABX
ggplot(d.sal.p, aes(x = Antibiotics, y = MaxD, fill = Antibiotics)) +
  geom_boxplot()


### Boxplot - MaxSlope
ggplot(d.inu.s, aes(x = Antibiotics, y = Slope, fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(d.inu.w, aes(x = Antibiotics, y = Slope, fill = Antibiotics)) +
  geom_boxplot()
ggplot(d.inu.p, aes(x = Antibiotics, y = Slope, fill = Antibiotics)) +
  geom_boxplot()
  # 1 No ABX
ggplot(d.sal.s, aes(x = Antibiotics, y = Slope, fill = Antibiotics)) +
  geom_boxplot()
  # 1 No ABX
ggplot(d.sal.w, aes(x = Antibiotics, y = Slope, fill = Antibiotics)) +
  geom_boxplot()
ggplot(d.sal.p, aes(x = Antibiotics, y = Slope, fill = Antibiotics)) +
  geom_boxplot()
  # 1 No ABX



### Boxplot - DNA Concentration
ggplot(dna.inu.s, aes(x = Antibiotics, y = DNA_Yield_.ng.mg., fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(dna.inu.w, aes(x = Antibiotics, y = DNA_Yield_.ng.mg., fill = Antibiotics)) +
  geom_boxplot()
  # 1 No ABX
ggplot(dna.inu.p, aes(x = Antibiotics, y = DNA_Yield_.ng.mg., fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
ggplot(dna.sal.s, aes(x = Antibiotics, y = DNA_Yield_.ng.mg., fill = Antibiotics)) +
  geom_boxplot()
  # 1 No ABX
ggplot(dna.sal.w, aes(x = Antibiotics, y = DNA_Yield_.ng.mg., fill = Antibiotics)) +
  geom_boxplot()
ggplot(dna.sal.p, aes(x = Antibiotics, y = DNA_Yield_.ng.mg., fill = Antibiotics)) +
  geom_boxplot()
  # 1 ABX
```
