---
title: "Code_TestCorrelations"
author: "Edna Chiang"
date: "12/14/2021"
output: html_document
---

### Load Packages, scripts, and functions
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
library(car)
source('scripts/misc.R')
set.seed(1)
theme_set(theme_bw())
```

### Load Data
```{r}
load('crds.norm.RData')
load('crds.use.Rdata')
meta <- read.csv('metadata.csv')
```

### Prepare CRDS data
```{r}
# Add metadata
crds.use[, colnames(meta)[3:ncol(meta)]] <- NA
for(i in 1:nrow(crds.use)){
  meta.row <- which(meta$ID == crds.use$ID[i])
  crds.use[i, 7:ncol(crds.use)] <- meta[meta.row, 3:ncol(meta)]
}

# Calculate square root of AUC
crds.use$AUC <- as.numeric(crds.use$AUC)
minAUC <- min(crds.use$AUC)
crds.use$AUC_sqrt <- crds.use$AUC + (minAUC * -1)
crds.use$AUC_sqrt <- sqrt(crds.use$AUC_sqrt)

# Convert to numeric
crds.use$AvgD <- as.numeric(crds.use$AvgD)
crds.use$MaxD <- as.numeric(crds.use$MaxD)
crds.use$MaxSlope <- as.numeric(crds.use$MaxSlope)
crds.use$AUC <- as.numeric(crds.use$AUC)
crds.use$MaxD <- as.numeric(crds.use$MaxD)
crds.use$Baseline <- as.numeric(crds.use$Baseline)

# Order categorical variables
crds.use$Season <- ordered(crds.use$Season, levels = c("Summer", "Winter", "Spring"))
crds.use$Sex <- ordered(crds.use$Sex, levels = c("Female", "Male"))
crds.use$Antibiotics <- ordered(crds.use$Antibiotics, levels = c("No", "Yes"))
crds.use$Substrate <- ordered(crds.use$Substrate, levels = c("Inulin", "Saline"))
crds.use$Diet <- ordered(crds.use$Diet, levels = c("1", "2"))

# Remove outliers
crds.rem <- crds.use[-which(crds.use$ID == "S23"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S37"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S60"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W43"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W20"),]
  # This is due to odd metagenome
crds.rem <- crds.rem[-which(crds.rem$ID == "W50"),]

# Separate by substrate
crds.inu <- crds.rem[which(crds.rem$Substrate == "Inulin"),]
crds.sal <- crds.rem[which(crds.rem$Substrate == "Saline"),]

# Separate by substrate + season
crds.inu.s <- crds.inu[which(crds.inu$Season == "Summer"),]
crds.inu.w <- crds.inu[which(crds.inu$Season == "Winter"),]
crds.inu.p <- crds.inu[which(crds.inu$Season == "Spring"),]
crds.sal.s <- crds.sal[which(crds.sal$Season == "Summer"),]
crds.sal.w <- crds.sal[which(crds.sal$Season == "Winter"),]
crds.sal.p <- crds.sal[which(crds.sal$Season == "Spring"),]

# Separate by substrate + ABX
crds.inu.noabx <- crds.inu[which(crds.inu$Antibiotics == "No"),]
crds.inu.abx <- crds.inu[which(crds.inu$Antibiotics == "Yes"),]
crds.sal.noabx <- crds.sal[which(crds.sal$Antibiotics == "No"),]
crds.sal.abx <- crds.sal[which(crds.sal$Antibiotics == "Yes"),]
```


### Test Baseline
```{r}
### Test BodyMass Correlation

# Inulin No ABX
res <- resid(lm(Baseline ~ BodyMass, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$Baseline, crds.inu.noabx$BodyMass, method = "pearson")
  # p = 0.0006718
  # cor = 0.6813544

# Inulin ABX
res <- resid(lm(Baseline ~ BodyMass, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.01681
  # Not Normal
cor.test(crds.inu.abx$Baseline, crds.inu.abx$BodyMass, method = "kendall")
  # p = 0.008264
  # tau = 0.4385965

# Saline No ABX
res <- resid(lm(Baseline ~ BodyMass, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.noabx$Baseline, crds.sal.noabx$BodyMass, method = "pearson")
  # p = 0.1602

# Saline ABX
res <- resid(lm(Baseline ~ BodyMass, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but residuals are clearly sigmoid.
  # Not Normal
cor.test(crds.sal.abx$Baseline, crds.sal.abx$BodyMass, method = "kendall")
  # p = 0.0002925
  # tau = 0.6176471 





### Test BodyTemp Correlation

# Inulin No ABX
res <- resid(lm(Baseline ~ BodyTemp, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$Baseline, crds.inu.noabx$BodyTemp, method = "pearson")
  # p = 0.443

# Inulin ABX
res <- resid(lm(Baseline ~ BodyTemp, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$Baseline, crds.inu.abx$BodyTemp, method = "pearson")
  # p = 0.7934

# Saline No ABX
res <- resid(lm(Baseline ~ BodyTemp, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.noabx$Baseline, crds.sal.noabx$BodyTemp, method = "pearson")
  # p = 0.5212

# Saline ABX
res <- resid(lm(Baseline ~ BodyTemp, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$Baseline, crds.sal.abx$BodyTemp, method = "pearson")
  # p = 0.05815





### Test Ketones Correlation

# Inulin No ABX
res <- resid(lm(Baseline ~ Ketones, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$Baseline, crds.inu.noabx$Ketones, method = "pearson")
  # p = 0.002927
  # cor = -0.6928471

# Inulin ABX
res <- resid(lm(Baseline ~ Ketones, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$Baseline, crds.inu.abx$Ketones, method = "pearson")
  # p = 0.166

# Saline No ABX
res <- resid(lm(Baseline ~ Ketones, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test is on the edge, but residuals are sigmoid
  # Not Normal
cor.test(crds.sal.noabx$Baseline, crds.sal.noabx$Ketones, method = "kendall")
  # p = 0.0378
  # tau = -0.4149041

# Saline ABX
res <- resid(lm(Baseline ~ Ketones, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$Baseline, crds.sal.abx$Ketones, method = "pearson")
  # p = 0.1171

```


### Test AUC_sqrt
```{r}
### Test BodyMass Correlation

# Inulin No ABX
res <- resid(lm(AUC_sqrt ~ BodyMass, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$AUC_sqrt, crds.inu.noabx$BodyMass, method = "pearson")
  # p = 0.4277


# Inulin ABX
res <- resid(lm(AUC_sqrt ~ BodyMass, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$AUC_sqrt, crds.inu.abx$BodyMass, method = "pearson")
  # p = 0.8798

# Saline No ABX
res <- resid(lm(AUC_sqrt ~ BodyMass, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.03218
  # Not Normal
cor.test(crds.sal.noabx$AUC_sqrt, crds.sal.noabx$BodyMass, method = "kendall")
  # p = 0.2983

# Saline ABX
res <- resid(lm(AUC_sqrt ~ BodyMass, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$AUC_sqrt, crds.sal.abx$BodyMass, method = "pearson")
  # p = 0.3556





### Test BodyTemp Correlation

# Inulin No ABX
res <- resid(lm(AUC_sqrt ~ BodyTemp, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$AUC_sqrt, crds.inu.noabx$BodyTemp, method = "pearson")
  # p = 0.04429
  # cor = 0.4430237

# Inulin ABX
res <- resid(lm(AUC_sqrt ~ BodyTemp, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$AUC_sqrt, crds.inu.abx$BodyTemp, method = "pearson")
  # p = 0.7325

# Saline No ABX
res <- resid(lm(AUC_sqrt ~ BodyTemp, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.007584
  # Not Normal
cor.test(crds.sal.noabx$AUC_sqrt, crds.sal.noabx$BodyTemp, method = "kendall")
  # p = 0.858

# Saline ABX
res <- resid(lm(AUC_sqrt ~ BodyTemp, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but residuals look sigmoid
  # Not Normal
cor.test(crds.sal.abx$AUC_sqrt, crds.sal.abx$BodyTemp, method = "kendall")
  # p = 0.4753





### Test Ketones Correlation

# Inulin No ABX
res <- resid(lm(AUC_sqrt ~ Ketones, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$AUC_sqrt, crds.inu.noabx$Ketones, method = "pearson")
  # p = 0.6474

# Inulin ABX
res <- resid(lm(AUC_sqrt ~ Ketones, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$AUC_sqrt, crds.inu.abx$Ketones, method = "pearson")
  # p = 0.4552

# Saline No ABX
res <- resid(lm(AUC_sqrt ~ Ketones, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says not normal, but it seems to be only due to one outlier
  # Normal
cor.test(crds.sal.noabx$AUC_sqrt, crds.sal.noabx$Ketones, method = "pearson")
  # p = 0.3477

# Saline ABX
res <- resid(lm(AUC_sqrt ~ Ketones, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$AUC_sqrt, crds.sal.abx$Ketones, method = "pearson")
  # p = 0.2177

```


### Test AvgD
```{r}
### Test BodyMass Correlation

# Inulin No ABX
res <- resid(lm(AvgD ~ BodyMass, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$AvgD, crds.inu.noabx$BodyMass, method = "pearson")
  # p = 0.5897


# Inulin ABX
res <- resid(lm(AvgD ~ BodyMass, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$AvgD, crds.inu.abx$BodyMass, method = "pearson")
  # p = 0.9436

# Saline No ABX
res <- resid(lm(AvgD ~ BodyMass, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.0006069
  # Not Normal
cor.test(crds.sal.noabx$AvgD, crds.sal.noabx$BodyMass, method = "kendall")
  # p = 0.116

# Saline ABX
res <- resid(lm(AvgD ~ BodyMass, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$AvgD, crds.sal.abx$BodyMass, method = "pearson")
  # p = 0.3748





### Test BodyTemp Correlation

# Inulin No ABX
res <- resid(lm(AvgD ~ BodyTemp, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$AvgD, crds.inu.noabx$BodyTemp, method = "pearson")
  # p = 0.05967

# Inulin ABX
res <- resid(lm(AvgD ~ BodyTemp, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$AvgD, crds.inu.abx$BodyTemp, method = "pearson")
  # p = 0.8833

# Saline No ABX
res <- resid(lm(AvgD ~ BodyTemp, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.0001787
  # Not Normal
cor.test(crds.sal.noabx$AvgD, crds.sal.noabx$BodyTemp, method = "kendall")
  # p = 0.7125

# Saline ABX
res <- resid(lm(AvgD ~ BodyTemp, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$AvgD, crds.sal.abx$BodyTemp, method = "pearson")
  # p = 0.5314





### Test Ketones Correlation

# Inulin No ABX
res <- resid(lm(AvgD ~ Ketones, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$AvgD, crds.inu.noabx$Ketones, method = "pearson")
  # p = 0.722

# Inulin ABX
res <- resid(lm(AvgD ~ Ketones, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$AvgD, crds.inu.abx$Ketones, method = "pearson")
  # p = 0.3582

# Saline No ABX
res <- resid(lm(AvgD ~ Ketones, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.001431
  # Not normal due to an outlier, so go with Normal
cor.test(crds.sal.noabx$AvgD, crds.sal.noabx$Ketones, method = "pearson")
  # p = 0.2854

# Saline ABX
res <- resid(lm(AvgD ~ Ketones, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$AvgD, crds.sal.abx$Ketones, method = "pearson")
  # p = 0.1574

```



### Test MaxD
```{r}
### Test BodyMass Correlation

# Inulin No ABX
res <- resid(lm(MaxD ~ BodyMass, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.04659
  # Not Normal
cor.test(crds.inu.noabx$MaxD, crds.inu.noabx$BodyMass, method = "kendall")
  # p = 0.06493


# Inulin ABX
res <- resid(lm(MaxD ~ BodyMass, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$MaxD, crds.inu.abx$BodyMass, method = "pearson")
  # p = 0.8482

# Saline No ABX
res <- resid(lm(MaxD ~ BodyMass, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.0006069
  # Not Normal
cor.test(crds.sal.noabx$MaxD, crds.sal.noabx$BodyMass, method = "kendall")
  # p = 0.332

# Saline ABX
res <- resid(lm(MaxD ~ BodyMass, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but data looks skewed left
  # Not Normal
cor.test(crds.sal.abx$MaxD, crds.sal.abx$BodyMass, method = "kendall")
  # p = 0.1089





### Test BodyTemp Correlation

# Inulin No ABX
res <- resid(lm(MaxD ~ BodyTemp, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test is on edge, but histo isn't normal
  # Not Normal
cor.test(crds.inu.noabx$MaxD, crds.inu.noabx$BodyTemp, method = "kendall")
  # p = 0.1045

# Inulin ABX
res <- resid(lm(MaxD ~ BodyTemp, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$MaxD, crds.inu.abx$BodyTemp, method = "pearson")
  # p = 0.7786

# Saline No ABX
res <- resid(lm(MaxD ~ BodyTemp, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 2.356e-05
  # Not Normal
cor.test(crds.sal.noabx$MaxD, crds.sal.noabx$BodyTemp, method = "kendall")
  # p = 0.6418

# Saline ABX
res <- resid(lm(MaxD ~ BodyTemp, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$MaxD, crds.sal.abx$BodyTemp, method = "pearson")
  # p = 0.4933





### Test Ketones Correlation

# Inulin No ABX
res <- resid(lm(MaxD ~ Ketones, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$MaxD, crds.inu.noabx$Ketones, method = "pearson")
  # p = 0.1923

# Inulin ABX
res <- resid(lm(MaxD ~ Ketones, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$MaxD, crds.inu.abx$Ketones, method = "pearson")
  # p = 0.9001

# Saline No ABX
res <- resid(lm(MaxD ~ Ketones, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Not normal due to an outlier, so go with Normal
cor.test(crds.sal.noabx$MaxD, crds.sal.noabx$Ketones, method = "pearson")
  # p = 0.4857

# Saline ABX
res <- resid(lm(MaxD ~ Ketones, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$MaxD, crds.sal.abx$Ketones, method = "pearson")
  # p = 0.3552

```




### Test MaxSlope
```{r}
### Test BodyMass Correlation

# Inulin No ABX
res <- resid(lm(MaxSlope ~ BodyMass, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.02615
  # Not Normal
cor.test(crds.inu.noabx$MaxSlope, crds.inu.noabx$BodyMass, method = "kendall")
  # p = 0.006091
  # tau = 0.4285714

# Inulin ABX
res <- resid(lm(MaxSlope ~ BodyMass, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$MaxSlope, crds.inu.abx$BodyMass, method = "pearson")
  # p = 0.2926

# Saline No ABX
res <- resid(lm(MaxSlope ~ BodyMass, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 3.129e-05
  # Not Normal
cor.test(crds.sal.noabx$MaxSlope, crds.sal.noabx$BodyMass, method = "kendall")
  # p = 0.8903

# Saline ABX
res <- resid(lm(MaxSlope ~ BodyMass, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$MaxSlope, crds.sal.abx$BodyMass, method = "pearson")
  # p = 0.4934





### Test BodyTemp Correlation

# Inulin No ABX
res <- resid(lm(MaxSlope ~ BodyTemp, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.03657
  # Not Normal
cor.test(crds.inu.noabx$MaxSlope, crds.inu.noabx$BodyTemp, method = "kendall")
  # p = 0.2322

# Inulin ABX
res <- resid(lm(MaxSlope ~ BodyTemp, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$MaxSlope, crds.inu.abx$BodyTemp, method = "pearson")
  # p = 0.7659

# Saline No ABX
res <- resid(lm(MaxSlope ~ BodyTemp, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 5.267e-06
  # Not Normal
cor.test(crds.sal.noabx$MaxSlope, crds.sal.noabx$BodyTemp, method = "kendall")
  # p = 0.1424

# Saline ABX
res <- resid(lm(MaxSlope ~ BodyTemp, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$MaxSlope, crds.sal.abx$BodyTemp, method = "pearson")
  # p = 0.7211





### Test Ketones Correlation

# Inulin No ABX
res <- resid(lm(MaxSlope ~ Ketones, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.noabx$MaxSlope, crds.inu.noabx$Ketones, method = "pearson")
  # p = 0.06079

# Inulin ABX
res <- resid(lm(MaxSlope ~ Ketones, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.inu.abx$MaxSlope, crds.inu.abx$Ketones, method = "pearson")
  # p = 0.09455

# Saline No ABX
res <- resid(lm(MaxSlope ~ Ketones, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Not normal due to one outlier, but otherwise it looks normal
  # Normal
cor.test(crds.sal.noabx$MaxSlope, crds.sal.noabx$Ketones, method = "pearson")
  # p = 0.9383

# Saline ABX
res <- resid(lm(MaxSlope ~ Ketones, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(crds.sal.abx$MaxSlope, crds.sal.abx$Ketones, method = "pearson")
  # p = 0.9754

```




### Load/Test Inulinase RPKG
```{r}
### Exo - RPKG
exo_rpkg <- read.csv('eCAMI/inulinase/exoRPKG.csv')
exo_rpkg$Season <- ordered(exo_rpkg$Season, c("Summer", "Winter", "Spring"))

# Remove W20 outlier
exo_rpkg <- exo_rpkg[-which(exo_rpkg$Sample == "S-W20"),]


### Prepare AUC & slope data
for(sample in 1:nrow(exo_rpkg)){
  sampName <- substr(exo_rpkg$Sample[sample], 3, 5)
  useRow <- which(crds.rem$ID == sampName)
  exo_rpkg$Baseline[sample] <- crds.rem$Baseline[useRow]
  exo_rpkg$AUC_sqrt[sample] <- crds.rem$AUC_sqrt[useRow]
  exo_rpkg$AvgD[sample] <- crds.rem$AvgD[useRow]
  exo_rpkg$MaxD[sample] <- crds.rem$MaxD[useRow]
  exo_rpkg$MaxSlope[sample] <- crds.rem$MaxSlope[useRow]
}

# Subset out inulin samples
exo_rpkg_inu <- exo_rpkg[1:9,]


# Test RPKG - Baseline
res <- resid(lm(RPKG ~ Baseline, exo_rpkg_inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(exo_rpkg_inu$RPKG, exo_rpkg_inu$Baseline, method = "pearson")
  # p = 0.9096

# Test RPKG - AUC_sqrt
res <- resid(lm(RPKG ~ AUC_sqrt, exo_rpkg_inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(exo_rpkg_inu$RPKG, exo_rpkg_inu$AUC_sqrt, method = "pearson")
  # p = 0.6674

# Test RPKG - AvgD
res <- resid(lm(RPKG ~ AvgD, exo_rpkg_inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(exo_rpkg_inu$RPKG, exo_rpkg_inu$AvgD, method = "pearson")
  # p = 0.6854

# Test RPKG - MaxD
res <- resid(lm(RPKG ~ MaxD, exo_rpkg_inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(exo_rpkg_inu$RPKG, exo_rpkg_inu$MaxD, method = "pearson")
  # p = 0.7554

# Test RPKG - MaxSlope
res <- resid(lm(RPKG ~ MaxSlope, exo_rpkg_inu))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(exo_rpkg_inu$RPKG, exo_rpkg_inu$MaxSlope, method = "pearson")
  # p = 0.9127
```


### Load/Test DNA Yield
```{r}
# Load DNA data
dna <- read.csv('dna.csv')
dna$Season <- ordered(dna$Season, levels=c("Summer", "Winter", "Spring"))
dna <- dna[-which(dna$Squirrel == "S23"),]
dna <- dna[-which(dna$Squirrel == "S37"),]
dna <- dna[-which(dna$Squirrel == "S60"),]
dna <- dna[-which(dna$Squirrel == "W43"),]
dna <- dna[-which(dna$Squirrel == "W20"),]
#dna <- dna[-which(dna$Squirrel == "W53"),]
dna <- dna[-which(dna$Squirrel == "P04"),]
dna <- dna[-which(dna$Squirrel == "S11"),]
dna <- dna[-which(dna$Squirrel == "S40"),]
dna <- dna[-which(dna$Squirrel == "W50"),]
dna.con <- dna[which(substr(dna$Sample,2,2) == "C"),]


### Add in delta metrics
for(sample in 1:nrow(dna.con)){
  sampName <- dna.con$Squirrel[sample]
  useRow <- which(crds.rem$ID == sampName)
  dna.con$Baseline[sample] <- crds.rem$Baseline[useRow]
  dna.con$AUC_sqrt[sample] <- crds.rem$AUC_sqrt[useRow]
  dna.con$AvgD[sample] <- crds.rem$AvgD[useRow]
  dna.con$MaxD[sample] <- crds.rem$MaxD[useRow]
  dna.con$MaxSlope[sample] <- crds.rem$MaxSlope[useRow]
}

# Subset out inulin
dna.c.inu <- dna.con[which(dna.con$Substrate == "Inulin"),]

# Subset out ABX treatments
dna.c.inu.abx <- dna.c.inu[which(dna.c.inu$Antibiotics == "Antibiotics"),]
dna.c.inu.noabx <- dna.c.inu[which(dna.c.inu$Antibiotics == "No Antibiotics"),]



### Test Baseline
res <- resid(lm(DNA_Yield_.ng.mg. ~ Baseline, dna.c.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dna.c.inu.noabx$DNA_Yield_.ng.mg., dna.c.inu.noabx$Baseline, method = "pearson")
  # p = 0.3841

res <- resid(lm(DNA_Yield_.ng.mg. ~ Baseline, dna.c.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.03934
  # Not Normal
cor.test(dna.c.inu.abx$DNA_Yield_.ng.mg., dna.c.inu.abx$Baseline, method = "kendall")
  # p = 0.04198
  # tau = -0.3421963



### Test AUC_sqrt
res <- resid(lm(DNA_Yield_.ng.mg. ~ AUC_sqrt, dna.c.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dna.c.inu.noabx$DNA_Yield_.ng.mg., dna.c.inu.noabx$AUC_sqrt, method = "pearson")
  # p = 0.3218

res <- resid(lm(DNA_Yield_.ng.mg. ~ AUC_sqrt, dna.c.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.0005922
  # Not Normal
cor.test(dna.c.inu.abx$DNA_Yield_.ng.mg., dna.c.inu.abx$AUC_sqrt, method = "kendall")
  # p = 0.2618



### Test AvgD
res <- resid(lm(DNA_Yield_.ng.mg. ~ AvgD, dna.c.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dna.c.inu.noabx$DNA_Yield_.ng.mg., dna.c.inu.noabx$AvgD, method = "pearson")
  # p = 0.2561

res <- resid(lm(DNA_Yield_.ng.mg. ~ AvgD, dna.c.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.001177
  # Not Normal
cor.test(dna.c.inu.abx$DNA_Yield_.ng.mg., dna.c.inu.abx$AvgD, method = "kendall")
  # p = 0.6235



### Test MaxD
res <- resid(lm(DNA_Yield_.ng.mg. ~ MaxD, dna.c.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dna.c.inu.noabx$DNA_Yield_.ng.mg., dna.c.inu.noabx$MaxD, method = "pearson")
  # p = 0.2957

res <- resid(lm(DNA_Yield_.ng.mg. ~ MaxD, dna.c.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.002488
  # Not Normal
cor.test(dna.c.inu.abx$DNA_Yield_.ng.mg., dna.c.inu.abx$MaxD, method = "kendall")
  # p = 0.8885



### Test MaxSlope
res <- resid(lm(DNA_Yield_.ng.mg. ~ MaxSlope, dna.c.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dna.c.inu.noabx$DNA_Yield_.ng.mg., dna.c.inu.noabx$MaxSlope, method = "pearson")
  # p = 0.4263

res <- resid(lm(DNA_Yield_.ng.mg. ~ MaxSlope, dna.c.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.00357
  # Not Normal
cor.test(dna.c.inu.abx$DNA_Yield_.ng.mg., dna.c.inu.abx$MaxSlope, method = "kendall")
  # p = 0.04198
  # tau = 0.3421963
```


### Hib Dates
```{r}
### Load data ###

# Dates
dates <- read.csv('metadata_dates.csv')
dates_use <- dates[-which(dates$Season == "Summer"),]
rownames(dates_use) <- 1:nrow(dates_use)
dates_use <- dates_use[-13:-28,]
rownames(dates_use) <- 1:nrow(dates_use)
dates_use <- dates_use[-33:-40,]
dates_use <- dates_use[-3,]
  # Remove outlier P04
dates_use <- dates_use[-which(dates_use$ID == "W20"),]



# Add CRDS metrics
for(k in 1:nrow(dates_use)){
  ID <- dates_use$ID[k]
  rowUse <- which(crds.rem$ID == ID)
  dates_use$AvgD[k] <- crds.rem$AvgD[rowUse]
  dates_use$MaxD[k] <- crds.rem$MaxD[rowUse]
  dates_use$MaxSlope[k] <- crds.rem$MaxSlope[rowUse]
  dates_use$AUC_sqrt[k] <- crds.rem$AUC_sqrt[rowUse]
  dates_use$Baseline[k] <- crds.rem$Baseline[rowUse]
}



# Separate by Substrate
dates.inu <- dates_use[which(dates_use$Substrate == "Inulin"),]
dates.sal <- dates_use[which(dates_use$Substrate == "Saline"),]

# Separate by Substrate + Season
dates.inu.p <- dates.inu[which(dates.inu$Season == "Spring"),]
dates.inu.w <- dates.inu[which(dates.inu$Season == "Winter"),]
dates.sal.p <- dates.sal[which(dates.sal$Season == "Spring"),]
dates.sal.w <- dates.sal[which(dates.sal$Season == "Winter"),]



### Correlate Baseline ### 

# Inulin Winter
res <- resid(lm(Days_Hib ~ Baseline, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.04767
  # Not Normal
cor.test(dates.inu.w$Days_Hib, dates.inu.w$Baseline, method = "pearson")
  # p-value = 0.8616

res <- resid(lm(IBA.Hib ~ Baseline, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$IBA.Hib, dates.inu.w$Baseline, method = "pearson")
  # p-value = 0.6949

res <- resid(lm(Num_IBA ~ Baseline, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Data doesn't look normal
  # Not Normal
cor.test(dates.inu.w$Num_IBA, dates.inu.w$Baseline, method = "kendall")
  # p-value = 0.3991


# Inulin Spring
res <- resid(lm(Days_Hib ~ Baseline, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Days_Hib, dates.inu.p$Baseline, method = "pearson")
  # p-value = 0.09606

res <- resid(lm(IBA.Hib ~ Baseline, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$IBA.Hib, dates.inu.p$Baseline, method = "pearson")
  # p-value = 0.5982

res <- resid(lm(Num_IBA ~ Baseline, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Num_IBA, dates.inu.p$Baseline, method = "pearson")
  # p-value = 0.4493


# Saline Winter
res <- resid(lm(Days_Hib ~ Baseline, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Days_Hib, dates.sal.w$Baseline, method = "pearson")
  # p-value = 5.622e-05
  # cor = -0.9390097

res <- resid(lm(IBA.Hib ~ Baseline, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$IBA.Hib, dates.sal.w$Baseline, method = "pearson")
  # p-value = 0.9251

res <- resid(lm(Num_IBA ~ Baseline, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Num_IBA, dates.sal.w$Baseline, method = "pearson")
  # p-value = 0.1271


# Saline Spring
res <- resid(lm(Days_Hib ~ Baseline, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Days_Hib, dates.sal.p$Baseline, method = "pearson")
  # p-value = 0.172

res <- resid(lm(IBA.Hib ~ Baseline, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$IBA.Hib, dates.sal.p$Baseline, method = "pearson")
  # p-value = 0.6928

res <- resid(lm(Num_IBA ~ Baseline, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Num_IBA, dates.sal.p$Baseline, method = "pearson")
  # p-value = 0.3761




### Correlate AUC_sqrt ### 

# Inulin Winter
res <- resid(lm(Days_Hib ~ AUC_sqrt, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.04767
  # Not Normal
cor.test(dates.inu.w$Days_Hib, dates.inu.w$AUC_sqrt, method = "pearson")
  # p-value = 0.5399

res <- resid(lm(IBA.Hib ~ AUC_sqrt, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$IBA.Hib, dates.inu.w$AUC_sqrt, method = "pearson")
  # p-value = 0.4686

res <- resid(lm(Num_IBA ~ AUC_sqrt, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$Num_IBA, dates.inu.w$AUC_sqrt, method = "pearson")
  # p-value = 0.7622


# Inulin Spring
res <- resid(lm(Days_Hib ~ AUC_sqrt, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Days_Hib, dates.inu.p$AUC_sqrt, method = "pearson")
  # p-value = 0.4164

res <- resid(lm(IBA.Hib ~ AUC_sqrt, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$IBA.Hib, dates.inu.p$AUC_sqrt, method = "pearson")
  # p-value = 0.5327

res <- resid(lm(Num_IBA ~ AUC_sqrt, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Num_IBA, dates.inu.p$AUC_sqrt, method = "pearson")
  # p-value = 0.4504


# Saline Winter
res <- resid(lm(Days_Hib ~ AUC_sqrt, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Days_Hib, dates.sal.w$AUC_sqrt, method = "pearson")
  # p-value = 0.193

res <- resid(lm(IBA.Hib ~ AUC_sqrt, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$IBA.Hib, dates.sal.w$AUC_sqrt, method = "pearson")
  # p-value = 0.5949

res <- resid(lm(Num_IBA ~ AUC_sqrt, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Num_IBA, dates.sal.w$AUC_sqrt, method = "pearson")
  # p-value = 0.7424


# Saline Spring
res <- resid(lm(Days_Hib ~ AUC_sqrt, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Days_Hib, dates.sal.p$AUC_sqrt, method = "pearson")
  # p-value = 0.6188

res <- resid(lm(IBA.Hib ~ AUC_sqrt, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$IBA.Hib, dates.sal.p$AUC_sqrt, method = "pearson")
  # p-value = 0.162

res <- resid(lm(Num_IBA ~ AUC_sqrt, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Num_IBA, dates.sal.p$AUC_sqrt, method = "pearson")
  # p-value = 0.3363




### Correlate AvgD ### 

# Inulin Winter
res <- resid(lm(Days_Hib ~ AvgD, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$Days_Hib, dates.inu.w$AvgD, method = "pearson")
  # p-value = 0.5222

res <- resid(lm(IBA.Hib ~ AvgD, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$IBA.Hib, dates.inu.w$AvgD, method = "pearson")
  # p-value = 0.4297

res <- resid(lm(Num_IBA ~ AvgD, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$Num_IBA, dates.inu.w$AvgD, method = "pearson")
  # p-value = 0.7281


# Inulin Spring
res <- resid(lm(Days_Hib ~ AvgD, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Days_Hib, dates.inu.p$AvgD, method = "pearson")
  # p-value = 0.4029

res <- resid(lm(IBA.Hib ~ AvgD, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$IBA.Hib, dates.inu.p$AvgD, method = "pearson")
  # p-value = 0.5284

res <- resid(lm(Num_IBA ~ AvgD, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Num_IBA, dates.inu.p$AvgD, method = "pearson")
  # p-value = 0.4436


# Saline Winter
res <- resid(lm(Days_Hib ~ AvgD, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Days_Hib, dates.sal.w$AvgD, method = "pearson")
  # p-value = 0.1841

res <- resid(lm(IBA.Hib ~ AvgD, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$IBA.Hib, dates.sal.w$AvgD, method = "pearson")
  # p-value = 0.6059

res <- resid(lm(Num_IBA ~ AvgD, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Num_IBA, dates.sal.w$AvgD, method = "pearson")
  # p-value = 0.742


# Saline Spring
res <- resid(lm(Days_Hib ~ AvgD, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Days_Hib, dates.sal.p$AvgD, method = "pearson")
  # p-value = 0.6049

res <- resid(lm(IBA.Hib ~ AvgD, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$IBA.Hib, dates.sal.p$AvgD, method = "pearson")
  # p-value = 0.0831

res <- resid(lm(Num_IBA ~ AvgD, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Num_IBA, dates.sal.p$AvgD, method = "pearson")
  # p-value = 0.2111




### Correlate MaxD ### 

# Inulin Winter
res <- resid(lm(Days_Hib ~ MaxD, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$Days_Hib, dates.inu.w$MaxD, method = "pearson")
  # p-value = 0.4531

res <- resid(lm(IBA.Hib ~ MaxD, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$IBA.Hib, dates.inu.w$MaxD, method = "pearson")
  # p-value = 0.4515

res <- resid(lm(Num_IBA ~ MaxD, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$Num_IBA, dates.inu.w$MaxD, method = "pearson")
  # p-value = 0.8128


# Inulin Spring
res <- resid(lm(Days_Hib ~ MaxD, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Days_Hib, dates.inu.p$MaxD, method = "pearson")
  # p-value = 0.7036

res <- resid(lm(IBA.Hib ~ MaxD, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$IBA.Hib, dates.inu.p$MaxD, method = "pearson")
  # p-value = 0.5327

res <- resid(lm(Num_IBA ~ MaxD, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Num_IBA, dates.inu.p$MaxD, method = "pearson")
  # p-value = 0.5463


# Saline Winter
res <- resid(lm(Days_Hib ~ MaxD, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Days_Hib, dates.sal.w$MaxD, method = "pearson")
  # p-value = 0.1624

res <- resid(lm(IBA.Hib ~ MaxD, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$IBA.Hib, dates.sal.w$MaxD, method = "pearson")
  # p-value = 0.4762

res <- resid(lm(Num_IBA ~ MaxD, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Num_IBA, dates.sal.w$MaxD, method = "pearson")
  # p-value = 0.8184


# Saline Spring
res <- resid(lm(Days_Hib ~ MaxD, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Days_Hib, dates.sal.p$MaxD, method = "pearson")
  # p-value = 0.9127

res <- resid(lm(IBA.Hib ~ MaxD, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$IBA.Hib, dates.sal.p$MaxD, method = "pearson")
  # p-value = 0.01461
  # cor = -0.9467961 

res <- resid(lm(Num_IBA ~ MaxD, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Num_IBA, dates.sal.p$MaxD, method = "pearson")
  # p-value = 0.08477






### Correlate MaxSlope ### 

# Inulin Winter
res <- resid(lm(Days_Hib ~ MaxSlope, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.04767
  # Not Normal
cor.test(dates.inu.w$Days_Hib, dates.inu.w$MaxSlope, method = "kendall")
  # p-value = 0.3454

res <- resid(lm(IBA.Hib ~ MaxSlope, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$IBA.Hib, dates.inu.w$MaxSlope, method = "pearson")
  # p-value = 0.4296

res <- resid(lm(Num_IBA ~ MaxSlope, dates.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.w$Num_IBA, dates.inu.w$MaxSlope, method = "pearson")
  # p-value = 0.9546


# Inulin Spring
res <- resid(lm(Days_Hib ~ MaxSlope, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Days_Hib, dates.inu.p$MaxSlope, method = "pearson")
  # p-value = 0.7633

res <- resid(lm(IBA.Hib ~ MaxSlope, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$IBA.Hib, dates.inu.p$MaxSlope, method = "pearson")
  # p-value = 0.6705

res <- resid(lm(Num_IBA ~ MaxSlope, dates.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.inu.p$Num_IBA, dates.inu.p$MaxSlope, method = "pearson")
  # p-value = 0.6385


# Saline Winter
res <- resid(lm(Days_Hib ~ MaxSlope, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Days_Hib, dates.sal.w$MaxSlope, method = "pearson")
  # p-value = 0.2444

res <- resid(lm(IBA.Hib ~ MaxSlope, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$IBA.Hib, dates.sal.w$MaxSlope, method = "pearson")
  # p-value = 0.4055

res <- resid(lm(Num_IBA ~ MaxSlope, dates.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.w$Num_IBA, dates.sal.w$MaxSlope, method = "pearson")
  # p-value = 0.8882


# Saline Spring
res <- resid(lm(Days_Hib ~ MaxSlope, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Days_Hib, dates.sal.p$MaxSlope, method = "pearson")
  # p-value = 0.9362

res <- resid(lm(IBA.Hib ~ MaxSlope, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$IBA.Hib, dates.sal.p$MaxSlope, method = "pearson")
  # p-value = 0.9958

res <- resid(lm(Num_IBA ~ MaxSlope, dates.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
cor.test(dates.sal.p$Num_IBA, dates.sal.p$MaxSlope, method = "pearson")
  # p-value = 0.8852




### Combine RPKG + Hib Dates ###
rpkg.dates <- exo_rpkg[which(exo_rpkg$Season != "Summer"),]

for(m in 1:nrow(rpkg.dates)){
  ID <- substr(rpkg.dates$Sample, 3, 5)[m]
  
  useRow <- which(dates_use$ID == ID)
  rpkg.dates$Days_Hib[m] <- dates_use$Days_Hib[useRow]
  rpkg.dates$IBA.Hib[m] <- dates_use$IBA.Hib[useRow]
  rpkg.dates$Num_IBA[m] <- dates_use$Num_IBA[useRow]
}

# Separate by Season
rpkg.dates.w <- rpkg.dates[which(rpkg.dates$Season == "Winter"),]
rpkg.dates.p <- rpkg.dates[which(rpkg.dates$Season == "Spring"),]



### Correlate RPKG w/ Hib Dates ###
res <- resid(lm(Days_Hib ~ RPKG, rpkg.dates.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(rpkg.dates.w$Days_Hib, rpkg.dates.w$RPKG, method = "pearson")
  # p-value = 0.5756

res <- resid(lm(IBA.Hib ~ RPKG, rpkg.dates.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(rpkg.dates.w$IBA.Hib, rpkg.dates.w$RPKG, method = "pearson")
  # p-value = 0.6959

res <- resid(lm(Num_IBA ~ RPKG, rpkg.dates.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(rpkg.dates.w$Num_IBA, rpkg.dates.w$RPKG, method = "pearson")
  # p-value = 0.5854

res <- resid(lm(Days_Hib ~ RPKG, rpkg.dates.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(rpkg.dates.p$Days_Hib, rpkg.dates.p$RPKG, method = "pearson")
  # p-value = 0.3231

res <- resid(lm(IBA.Hib ~ RPKG, rpkg.dates.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(rpkg.dates.p$IBA.Hib, rpkg.dates.p$RPKG, method = "pearson")
  # p-value = 0.8018

res <- resid(lm(Num_IBA ~ RPKG, rpkg.dates.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(rpkg.dates.p$Num_IBA, rpkg.dates.p$RPKG, method = "pearson")
  # p-value = 0.9493

```

### Adj P
```{r}
p.adjust(c(0.0006718, 0.443, 0.002927, 0.4277, 0.04429, 0.6474, 0.5897, 0.05967, 0.722,
           0.06493, 0.1045, 0.1923, 0.006091, 0.2322, 0.06079, 0.3841, 0.3218, 0.2561,
           0.2987, 0.4263, 0.008264, 0.7934, 0.166, 0.8798, 0.7325, 0.4552, 0.9436, 0.8833,
           0.3582, 0.8482, 0.7786, 0.9001, 0.2926, 0.7659, 0.09455, 0.04198, 0.2618, 0.363,
           0.8885, 0.04198, 0.1602, 0.5212, 0.0378, 0.2983, 0.858, 0.3477, 0.116, 0.7125,
           0.2854, 0.332, 0.6418, 0.4857, 0.8903, 0.1424, 0.9383, 0.0002925, 0.05815,
           0.1171, 0.3556, 0.4753, 0.2177, 0.3748, 0.5766, 0.1574, 0.1089, 0.4933, 0.3552,
           0.4934, 0.7211, 0.9754), "BH")
  # 0.02351300 0.71954167 0.06829667 0.71283333 0.34447778 0.85505660 0.80939216
 [8] 0.34962308 0.89956140 0.34962308 0.45538889 0.58526087 0.10659250 0.65016000
[15] 0.34962308 0.67217500 0.66868421 0.66868421 0.66868421 0.71283333 0.11569600
[22] 0.92563333 0.52818182 0.94040299 0.89956140 0.71954167 0.95727536 0.94040299
[29] 0.66868421 0.94040299 0.92376271 0.94040299 0.66868421 0.92376271 0.45538889
[36] 0.34447778 0.66868421 0.66868421 0.94040299 0.34447778 0.52818182 0.74457143
[43] 0.34447778 0.66868421 0.94040299 0.66868421 0.45538889 0.89956140 0.66868421
[50] 0.66868421 0.85505660 0.71954167 0.94040299 0.52463158 0.95727536 0.02047500
[57] 0.34962308 0.45538889 0.66868421 0.71954167 0.63495833 0.67217500 0.80724000
[64] 0.52818182 0.45538889 0.71954167 0.66868421 0.71954167 0.89956140 0.97540000




p.adjust(c(0.8616, 0.6949, 0.3991, 0.5399, 0.4686, 0.7622, 0.5222, 0.4297, 0.7281, 0.4531,
           0.4515, 0.8128, 0.3454, 0.4296, 0.9546, 0.09606, 0.5982, 0.4493, 0.4164, 0.5327,
           0.4504, 0.4029, 0.5284, 0.4436, 0.7036, 0.5463, 0.5103, 0.7633, 0.6705, 0.6385,
           5.62E-05, 0.9251, 0.1271, 0.193, 0.5949, 0.7424, 0.1841, 0.6059, 0.742,0.1624,
           0.4762, 0.8184, 0.2444, 0.4055, 0.8882, 0.172, 0.6928, 0.3761, 0.6188, 0.162,
           0.3363, 0.6049, 0.0831, 0.2111, 0.9127, 0.01461, 0.08477, 0.9362, 0.9958, 
           0.8852), "BH")
  # 0.9684828 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600
 [9] 0.9159600 0.9159600 0.9159600 0.9443077 0.9159600 0.9159600 0.9707797 0.9159600
[17] 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600
[25] 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.0033720 0.9684828
[33] 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600
[41] 0.9159600 0.9443077 0.9159600 0.9159600 0.9684828 0.9159600 0.9159600 0.9159600
[49] 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9159600 0.9684828 0.4383000
[57] 0.9159600 0.9684828 0.9958000 0.9684828






p.adjust(c(0.5756, 0.6959, 0.5854, 0.3231, 0.8018, 0.9493, 0.9096, 0.6674, 0.6854, 0.7554, 0.9127), "BH")
  # 0.9493 0.9493 0.9493 0.9493 0.9493 0.9493 0.9493 0.9493 0.9493 0.9493 0.9493
```


### Misc
```{r}
res <- resid(lm(Num_IBA ~ RPKG, rpkg.dates.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(crds.inu.noabx$MaxD, crds.inu.noabx$MaxSlope, method = "pearson")

```