---
title: "Code_CAZymes"
author: "Edna Chiang"
date: "2/2/2022"
output: html_document
---

### Load Packages, scripts, and functions
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
#library(MESS)
#library(pgirmess)
#library(Bolstad2)
library(phyloseq)
library(vegan)
#library(miLineage)
#library(psych)
library(car)
library(DESeq2)
library(labdsv)
library(ggdendro)
library(ape)
library(pvclust)
#source('scripts/import_crds.R')
#source('scripts/bin_crds.R')
source('scripts/misc.R')
#source('scripts/calc_delta_metrics.R')
source('scripts/simper_pretty.R')
source('scripts/R_krusk.R')
set.seed(1)
theme_set(theme_bw())
```

### Prepare dbCAN data ***DON'T RUN***
```{r}
# Load data
otu.i <- read.csv('dbcan/inulin_dbcan_otu_table.csv', row.names=1)
tax.i <- read.csv('dbcan/inulin_dbcan_tax_table.csv', row.names=1, header = T)
tax.i <- tax_table(tax.i)
taxa_names(tax.i) <- tax.i[,2]
colnames(tax.i) <- c("Class", "Family")

otu.s <- read.csv('dbcan/saline_dbcan_otu_table.csv', row.names=1)
tax.s <- read.csv('dbcan/saline_dbcan_tax_table.csv', row.names=1, header = T)
tax.s <- tax_table(tax.s)
taxa_names(tax.s) <- tax.s[,2]
colnames(tax.s) <- c("Class", "Family")


meta <- read.csv('metadata_metag.csv', row.names = 2)


# Combine inulin & saline data
phy.i <- merge_phyloseq(sample_data(meta), tax.i, otu_table(otu.i, taxa_are_rows = T))
phy.s <- merge_phyloseq(sample_data(meta), tax.s, otu_table(otu.s, taxa_are_rows = T))
phy <- merge_phyloseq(phy.i, phy.s)
phy <- prune_taxa(taxa_names(phy) != "cohesin", phy)
  # Remove cohesin
phy <- prune_taxa(taxa_names(phy) != "SLH", phy)
  # Remove SLH

# Remove outlier (S-W20)
# phy <- prune_samples(x = phy, sample_names(phy) != "S.W20")


# Remove CAZymes that appear in < 3 samples
cazy.rem <- list()
otu <- data.frame(otu_table(phy))
for(i in 1:nrow(otu)){
  empty <- length(which(otu[i,] == 0))
    # Identifies # of samples w/o CAZyme
  if(empty > 15){
    # If CAZyme appears in only 1 sample
    cazy.rem <- append(cazy.rem, i)
      # Create list of CAZymes that appear in only 1 sample
  }
}
cazy.rem.row <- as.numeric(cazy.rem)
  # Convert list to numeric
otu.rem <- otu[-cazy.rem.row,]
  # Remove CAZymes that appear in < 3 samples
  # 11 CAZymes
  # GH49, GT52, GT7, GT73, GT89, PL31, CE5, GH232, GH157, GT44, GT61


# Create phyloseq object
cazy.phy <- merge_phyloseq(sample_data(phy), tax_table(phy), otu_table(otu.rem, taxa_are_rows = T))
#save(cazy.phy, file = "cazy.phy.RData")  
  



# Normalized Counts At Family-level
# https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html
otu.rem <- data.frame(otu_table(cazy.phy))
cazy.dds <- DESeqDataSetFromMatrix(countData = otu.rem, colData = data.frame(sample_data(cazy.phy)), design = ~ Season)
cazy.dds <- estimateSizeFactors(cazy.dds)
cazy.norm <- counts(cazy.dds, normalized=T)
#write.csv(cazy.norm, file="dbcan/cazy.Normalized.Counts.Family.csv")

cazy.fam.norm <- read.csv('dbcan/cazy.Normalized.Counts.Family.csv', row.names=1)
cazy.fam.norm.otu <- otu_table(cazy.fam.norm, taxa_are_rows=T)
cazy.fam.norm.phy <- merge_phyloseq(cazy.fam.norm.otu, sample_data(cazy.phy), tax_table(cazy.phy))
#save(cazy.fam.norm.phy, file = "cazy.fam.norm.phy.RData")

# Normalize Counts to Class-Level
cazy.class <- tax_glom(cazy.phy, taxrank="Class")
cazy.class.otu <- data.frame(otu_table(cazy.class))
cazy.dds <- DESeqDataSetFromMatrix(countData = cazy.class.otu, 
                                   colData = data.frame(sample_data(cazy.phy)), 
                                   design = ~ Season)
cazy.dds <- estimateSizeFactors(cazy.dds)
cazy.norm <- counts(cazy.dds, normalized=T)
#write.csv(cazy.norm, file="dbcan/cazy.Normalized.Counts.Class.csv")

cazy.class.norm <- read.csv('dbcan/cazy.Normalized.Counts.Class.csv', row.names=1)
rownames(cazy.class.norm) <- c("Carbohydrate Esterase", "Glycoside Hydrolase", "Glycosyltransferase", "Polysaccharide Lyase")

```


### Load phyloseq object
```{r}
# Load data
meta <- read.csv('metadata_metag.csv', row.names = 2)
load("cazy.phy.Rdata")
cazy.fam.norm <- read.csv('dbcan/cazy.Normalized.Counts.Family.csv', row.names=1)
load("cazy.fam.norm.phy.RData")
cazy.class.norm <- read.csv('dbcan/cazy.Normalized.Counts.Class.csv', row.names=1)
rownames(cazy.class.norm) <- c("Carbohydrate Esterase", "Glycoside Hydrolase", "Glycosyltransferase", "Polysaccharide Lyase")
```


### Count unique CAZyme families
```{r}
# Subset out samples by season
phy.sum <- subset_samples(cazy.phy, Season == "Summer")
phy.win <- subset_samples(cazy.phy, Season == "Winter")
phy.spr <- subset_samples(cazy.phy, Season == "Spring")


# Pull out unique CAZyme families in each season and order alphabetically
sum.fam <- get_taxa_unique(phy.sum, "Family")
sum.fam <- sort(sum.fam)
win.fam <- get_taxa_unique(phy.win, "Family")
win.fam <- sort(win.fam)
spr.fam <- get_taxa_unique(phy.spr, "Family")
spr.fam <- sort(spr.fam)


# Summer - Count # of CAZymes in each class
class <- substr(sum.fam,1,2)
length(which(class == "GH"))
  # 116
length(which(class == "GT"))
  # 53
length(which(class == "CE"))
  # 14
length(which(class == "PL"))
  # 22


# Winter - Count # of CAZymes in each class
class <- substr(win.fam,1,2)
length(which(class == "GH"))
  # 116
length(which(class == "GT"))
  # 53
length(which(class == "CE"))
  # 14
length(which(class == "PL"))
  # 22


# Spring - Count # of CAZymes in each class
class <- substr(spr.fam,1,2)
length(which(class == "GH"))
  # 116
length(which(class == "GT"))
  # 53
length(which(class == "CE"))
  # 14
length(which(class == "PL"))
  # 22
```


### Class-level dot plot
```{r}
# Create phyloseq object to summarize data
class.tax <- data.frame(c("Carbohydrate Esterase", "Glycoside Hydrolase", "Glycosyltransferase", 
                          "Polysaccharide Lyase"))
class.tax <- tax_table(class.tax)
row.names(class.tax) <- class.tax[,1]
colnames(class.tax) <- "Class"
cazy.class.norm.otu <- otu_table(cazy.class.norm, taxa_are_rows=T)
class.phy <- merge_phyloseq(cazy.class.norm.otu, class.tax, sample_data(meta))

# Calculate relative abundance
class.phy <- transform_sample_counts(class.phy, function(x){(x/sum(x))*100})

# Summarize data
class.df <- psmelt(class.phy)
class.df$Class <- ordered(class.df$Class, c("Glycoside Hydrolase", "Glycosyltransferase",
                                            "Carbohydrate Esterase","Polysaccharide Lyase"))
class.df$Season <- ordered(class.df$Season, levels = c("Summer", "Winter", "Spring"))
#class.sum <- class.df %>%
#  group_by(Class, Season) %>%
#  summarize(Mean = mean(Abundance),
#            SD = sd(Abundance),
#            SE = se(Abundance))
#cazy.class.sum$Class <- ordered(cazy.class.sum$Class, c("Glycoside Hydrolase",
#                                                                  "Glycosyltransferase",
#                                                                  "Carbohydrate Esterase",
#                                                                  "Polysaccharide Lyase"))
#cazy.class.sum$Season <- ordered(cazy.class.sum$Season, levels = c("Summer", "Winter", #"Spring"))

# Plot barplot
#tiff("cazy.class.tiff", width=11, height=4, units="in", res= 300)
ggplot(class.df, aes(x=Season, y=Abundance, fill=Season)) +
  geom_dotplot(binaxis='y', stackdir='center', dotsize=1.5, stackratio=1.2) +
  scale_y_continuous(limits=c(0,60), breaks = c(0,11,22,33,44,55)) +
  facet_grid(. ~ Class) +
  scale_fill_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  xlab("CAZyme Class") +
  ylab("Relative Abundance (%)") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face="bold"),
        strip.text.x = element_text(size=11),
        legend.title = element_text(size=12, face = "bold"),
        legend.text = element_text(size=12),
        panel.spacing = unit(0.5, "lines"),
        axis.title.x = element_text(margin = margin(t = 20)))
#dev.off()

```


### Test class-level
```{r}
# Same results if you compare Diet (Feeding vs. Fasting)
### CE
ce <- class.df[which(class.df$Class == "Carbohydrate Esterase"),]

# Test normality
hist(ce$Abundance)
qqnorm(ce$Abundance)
qqline(ce$Abundance)
shapiro.test(ce$Abundance)
  # p-value = 0.9974
  # Normal

# Test CE w/ ANOVA
summary(aov(Abundance ~ Season, data = ce))
  # p-value = 0.117



### GH
gh <- class.df[which(class.df$Class == "Glycoside Hydrolase"),]

# Test normality
hist(gh$Abundance)
qqnorm(gh$Abundance)
qqline(gh$Abundance)
shapiro.test(gh$Abundance)
  # p-value = 0.1308
  # Normal

# Test GH w/ ANOVA
summary(aov(Abundance ~ Season, data = gh))
  # p-value = 0.617




### GT
gt <- class.df[which(class.df$Class == "Glycosyltransferase"),]

# Test normality
hist(gt$Abundance)
qqnorm(gt$Abundance)
qqline(gt$Abundance)
shapiro.test(gt$Abundance)
  # p-value = 0.144
  # Normal

# Test GT w/ ANOVA
summary(aov(Abundance ~ Season, data = gt))
  # p-value = 0.903




### PL
pl <- class.df[which(class.df$Class == "Polysaccharide Lyase"),]

# Test normality
hist(pl$Abundance)
qqnorm(pl$Abundance)
qqline(pl$Abundance)
shapiro.test(pl$Abundance)
  # p-value = 0.004783
  # Not Normal

# Test PL w/ ANOVA
kruskal.test(Abundance ~ Season, pl)
  # p-value = 0.9942

```



### Create DESeq Object
```{r}
# https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html
# https://compbiocore.github.io/deseq-workshop-1/assets/deseq_workshop_1.html
# https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html
# Use UN-NORMALIZED data!!!
  # DESeq accounts for library size


### Test DESeq2 to determine fit type
# https://support.bioconductor.org/p/81094/
#dds <- phyloseq_to_deseq2(cazy.phy, ~Season)
#dds$Season <- factor(dds$Season, levels=c("Summer", "Winter", "Spring"))
#dds <- dds[rowSums(counts(dds)) > 1,]
#local <- DESeq(dds, fitType = "local")
#par <- DESeq(dds, fitType = "parametric")
#mad(log(mcols(local)$dispGeneEst) - log(mcols(local)$dispFit))
  # 7.770331
#mad(log(mcols(par)$dispGeneEst) - log(mcols(par)$dispFit))
  # 5.75149
# Parametric is a better fit (lower median absolute residual) than local

### Convert phyloseq object to deseq2 object
dds <- phyloseq_to_deseq2(cazy.phy, ~Season)
  # Design variable must be unordered otherwise you get an error
dds$Season <- factor(dds$Season, levels=c("Summer", "Winter", "Spring"))

# DESeq DataStructure for analyses
dds <- DESeq(dds)

# Hellinger-transformed data for visualizations
hell <- hellinger(t(assay(dds)))
```



### DESeq - find overrep genes
```{r}
# Pull out results from pairwise comparison
sw <- results(dds, contrast=c("Season", "Summer", "Winter"))
sw.sig <- sw[which(sw$padj < 0.05),]
sw.sig[which(sw.sig$log2FoldChange > 0),]
  # Enriched in Summer compared to Winter (positive log2FoldChange)
  # 16 CAZymes
  # CE12, CE2, GH10, GH11, GH25, GH26, GH31, GH42, GH43, GH44, GH5, GH51, GH94, GT11, PL1, PL11
  # Removed S.W20 =  12 CAZymes
      # CE12, GH10, GH115, GH31, GH42, GH43, GH44, GH5, GH51, GT11, PL1, PL11
sw.sig[which(sw.sig$log2FoldChange < 0),]
  # Enriched in Winter compared to Summer (negative log2FoldChange)
  # 11 CAZymes
  # GH109, GH110, GH20, GH33, GH84, GH88, GH89, GH92, GT94, PL12, PL8
  # Removed S.W20 = 5 CAZymes
      # GH109, GH20, GH33, GH84, GH85

sp <- results(dds, contrast=c("Season", "Summer", "Spring"))
sp.sig <- sp[which(sp$padj < 0.05),]
  # None

wp <- results(dds, contrast=c("Season", "Winter", "Spring"))
wp.sig <- wp[which(wp$padj < 0.05),]
wp.sig[which(wp.sig$log2FoldChange > 0),]
  # Enriched in Winter compared to Spring (positive log2FoldChange)
  # 12 CAZymes
  # GH101, GH109, GH110, GH20, GH33, GH84, GH85, GH88, GH89, GH92, PL12, PL8
  # Removed S.W20 = 9 CAZymes
      # GH109, GH20, GH23, GH33, GH57, GH84, GH85
wp.sig[which(wp.sig$log2FoldChange < 0),]
  # Enriched in Spring compared to Winter (negative log2FoldChange)
  # 21 CAZymes
  # CE12, CE2, GH10, GH115, GH26, GH3, GH31, GH42, GH43, GH44, GH47, GH5, GH51, GH8, GH9, GH94, GT11, GT24, PL1, PL11, PL9
  # Removed S.W20 = 17 CAZymes
      # CE12, CE2, GH10, GH115, GH120, GH3, GH31, GH42, GH43, GH5, GH51, GH9, GH94, GT11, PL1, PL11, PL9
```



### DESeq heatmap of normalized + transformed counts
```{r}
# Prepare data
hell.otu <- otu_table(t(hell), taxa_are_rows = T)
# Trying it with rel abund
#test <- transform_sample_counts(cazy.fam.norm.phy, function(x){(x/sum(x))*100})
#colnames(hell.otu) <- c("3715", "3717", "3723", "3733", "3734", "3744",
                              "3772", "3773" , "3775")
sig <- merge_phyloseq(hell.otu, tax_table(cazy.phy), sample_data(cazy.phy))




sig.active <- subset_taxa(sig, Family == "CE2" | Family == "CE12" | Family == "GH5" | Family == "GH10" |
                            Family == "GH26" | Family == "GH31" | Family == "GH42" | Family == "GH43" |
                            Family == "GH44" | Family == "GH51" | Family == "GH94" | Family == "GT11" |
                            Family == "PL1" | Family == "PL11" | Family == "GH11" | Family == "GH25" |
                            Family == "GH3" | Family == "GH8" | Family == "GH9" | Family == "GH47" |
                            Family == "GH115" | Family == "GT24" | Family == "PL9")
sig.act.sum <- merge_samples(sig.active, "Season")
sig.act.sum <- transform_sample_counts(sig.act.sum, function(x) (x/6))


sig.hib <- subset_taxa(sig, Family == "GH20" | Family == "GH33" | Family == "GH84" |
                         Family == "GH88" | Family == "GH89" | Family == "GH92" | Family == "GH109" |
                         Family == "GH110" | Family == "PL8" | Family == "PL12" | Family == "GT94" |
                         Family == "GH85" | Family == "GH101")
sig.hib.sum <- merge_samples(sig.hib, "Season")
sig.hib.sum <- transform_sample_counts(sig.hib.sum, function(x) (x/6))










##### BY SAMPLE


#tiff("cazy.heatmap.act.samp.tiff", width=10, height=9, units="in", res=300)
plot_heatmap(sig.active, sample.label = "Season", sample.order = c("S.S05", "I.S07", "S.S08", "I.S29",
                                                                "S.S32", "I.S34", "S.W20", "I.W31",
                                                                "I.W32", "I.W33", "S.W36", "S.W37",
                                                                "I.P01", "S.P03", "I.P07", "S.P09",
                                                                "I.P11", "S.P12"), 
             taxa.order = c("PL9", "GT24", "GH115", "GH47", "GH9", "GH8", "GH3", "GH25", "GH11", "PL11",
                            "PL1", "GT11", "GH94", "GH51", "GH44", "GH43", "GH42", "GH31", "GH26",
                            "GH10", "GH5", "CE12", "CE2")) +
  geom_tile(colour="gray40") +
  scale_x_discrete(position = "top", labels=c(rep("Summer",6), rep("Winter", 6), rep("Spring", 6))) +
  xlab("Season\n\n") +
  ylab("CAZyme Family\n\n") +
  scale_fill_gradientn(name=expression("Hellinger-\ntransformed\nnormalized\ncounts"),
                       colours = c("#FFFFFF", "#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c",
                                   "#fc4e2a", "#e31a1c", "#bd0026", "#800026", "#33000f"),
                       limits = c(0.000, 0.245), breaks = c(0.000, 0.049, 0.098, 0.147, 0.196, 0.245),
                       labels = c("0.000", "0.049", "0.098", "0.147", "0.196", "0.245")) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size=20),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.border=element_blank(),
        axis.title.x = element_text(size=20, face="bold"),
        axis.title.y = element_text(size=20, face="bold"),
        legend.title = element_text(size=20, face="bold"),
        legend.text = element_text(size=20)) +
  guides(fill = guide_colorbar(barheight = unit(7,"in"),
                               frame.colour="black",
                               frame.linewidth=1))
#dev.off()


#tiff("cazy.heatmap.hib.samp.tiff", width=14, height=9, units="in", res=300)
plot_heatmap(sig.hib, sample.label = "Season", sample.order = c("S.S05", "I.S07", "S.S08", "I.S29",
                                                                "S.S32", "I.S34", "S.W20", "I.W31",
                                                                "I.W32", "I.W33", "S.W36", "S.W37",
                                                                "I.P01", "S.P03", "I.P07", "S.P09",
                                                                "I.P11", "S.P12"), 
             taxa.order = c("GH101", "GH85", "GT94", "PL12", "PL8", "GH110", "GH109", "GH92", "GH89",
                            "GH88", "GH84", "GH33", "GH20")) +
  geom_tile(colour="gray40") +
  scale_x_discrete(position = "top", labels=c(rep("Summer",6), rep("Winter", 6), rep("Spring", 6))) +
  xlab("Season\n\n") +
  ylab("CAZyme Family\n\n") +
  scale_fill_gradientn(name=expression("Hellinger-\ntransformed\nnormalized\ncounts"),
                       colours = c("#FFFFFF", "#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c",
                                   "#fc4e2a", "#e31a1c", "#bd0026", "#800026", "#33000f"),
                       limits = c(0.000, 0.141), breaks = c(0.000, 0.035, 0.070, 0.105, 0.140),
                       labels = c("0.000", "0.035", "0.070", "0.105", "0.141")) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size=20),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.border=element_blank(),
        axis.title.x = element_text(size=20, face="bold"),
        axis.title.y = element_text(size=20, face="bold"),
        legend.title = element_text(size=20, face="bold"),
        legend.text = element_text(size=20)) +
  guides(fill = guide_colorbar(barheight = unit(7,"in"),
                               frame.colour="black",
                               frame.linewidth=1))
#dev.off()



##### BY SEASON


#tiff("cazy.heatmap.act.seas.tiff", width=4.9, height=9, units="in", res=300)
plot_heatmap(sig.act.sum, sample.label = "Season", sample.order = c("Summer", "Winter", "Spring"), 
             taxa.order = c("PL9", "GT24", "GH115", "GH47", "GH9", "GH8", "GH3", "GH25", "GH11", "PL11",
                            "PL1", "GT11", "GH94", "GH51", "GH44", "GH43", "GH42", "GH31", "GH26",
                            "GH10", "GH5", "CE12", "CE2")) +
  geom_tile(colour="gray40") +
  scale_x_discrete(position = "top", labels = c("Summer", "Winter", "Spring")) +
  xlab("Season\n\n") +
  ylab("CAZyme Family\n\n") +
  scale_fill_gradientn(name=expression("Mean\nhellinger-\ntransformed\nnormalized\ncounts"),
                       colours = c("#FFFFFF", "#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c",
                                   "#fc4e2a", "#e31a1c", "#bd0026", "#800026", "#33000f"),
                       limits = c(0.000, 0.231), breaks = c(0.000, 0.077, 0.154, 0.231),
                       labels = c("0.000", "0.077", "0.154", "0.231")) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size=20),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.border=element_blank(),
        axis.title.x = element_text(size=20, face="bold"),
        axis.title.y = element_text(size=20, face="bold"),
        legend.title = element_text(size=20, face="bold"),
        legend.text = element_text(size=20)) +
  guides(fill = guide_colorbar(barheight = unit(7,"in"),
                               frame.colour="black",
                               frame.linewidth=1))
#dev.off()


#tiff("cazy.heatmap.hib.seas.tiff", width=5.8, height=9, units="in", res=300)
plot_heatmap(sig.hib.sum, sample.label = "Season", sample.order = c("Summer", "Winter", "Spring"), 
             taxa.order = c("GH101", "GH85", "GT94", "PL12", "PL8", "GH110", "GH109", "GH92", "GH89",
                            "GH88", "GH84", "GH33", "GH20")) +
  geom_tile(colour="gray40") +
  scale_x_discrete(position = "top", labels = c("Summer", "Winter", "Spring")) +
  xlab("Season\n\n") +
  ylab("CAZyme Family\n\n") +
  scale_fill_gradientn(name=expression("Mean\nhellinger-\ntransformed\nnormalized\ncounts"),
                       colours = c("#FFFFFF", "#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c",
                                   "#fc4e2a", "#e31a1c", "#bd0026", "#800026", "#33000f"),
                       limits = c(0.000, 0.130), breaks = c(0.000, 0.026, 0.052, 0.078, 0.104, 0.130),
                       labels = c("0.000", "0.026", "0.052", "0.078", "0.104", "0.130")) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size=20),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.border=element_blank(),
        axis.title.x = element_text(size=20, face="bold"),
        axis.title.y = element_text(size=20, face="bold"),
        legend.title = element_text(size=20, face="bold"),
        legend.text = element_text(size=20)) +
  guides(fill = guide_colorbar(barheight = unit(7,"in"),
                               frame.colour="black",
                               frame.linewidth=1))
#dev.off()

```




### DESeq sample dist heatmap / dendrogram
```{r}
# https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#exploring-and-exporting-results
# http://bioconductor.org/packages/devel/workflows/vignettes/rnaseqGene/inst/doc/rnaseqGene.html

dist <- dist(hell, method = "euclidean")
dist.matrix <- as.matrix(dist)
rownames(dist.matrix) <- meta$Season
colnames(dist.matrix) <- meta$Season


# Dendrogram
hclust <- hclust(dist, method = "average")
den <- as.dendrogram(hclust)
den.data <- dendro_data(den, type="rectangle")
den.data$leaf_labels <- c(rep("Winter",6), "Spring", "Summer", "Summer", rep("Spring",4), "Summer", "Spring", "Summer", "Summer", "Summer")
den.data$leaf_labels <- ordered(den.data$leaf_labels, levels = c("Summer", "Winter", "Spring"))


#tiff("cazy.dendro.tiff", width=10, height=5, units="in", res=300)
ggplot(den.data$segments) +
  geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
  geom_text(data = den.data$labels, aes(x, y, label=den.data$leaf_labels, colour=den.data$leaf_labels,
                                        fontface = "bold"), hjust=0, size=5) +
  ylab("Hellinger Distance") +
  xlab("Season") +
  labs(colour = "Season") +
  coord_flip() +
  scale_y_reverse() +
  scale_color_manual(values=c("darkgoldenrod3", "dodgerblue3", "green4")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=20),
        panel.border = element_blank(),
        axis.line.x = element_line(),
        legend.title = element_text(face="bold"),
        axis.title.x = element_text(face="bold", size=20),
        axis.title.y = element_text(face="bold", size=20))
#dev.off()






### Validate clusters
# https://github.com/shimo-lab/pvclust
# https://cran.r-project.org/web/packages/pvclust/pvclust.pdf
# SI: https://rdrr.io/cran/scaleboot/f/vignettes/pvclust.Rmd
clust.test <- pvclust(t(hell), method.hclust = "average", method.dist = "euclidean")
plot(clust.test)
pvrect(clust.test, alpha = 0.95)
#plot(clust.test, print.pv = "si")
#pvrect(clust.test, alpha = 0.95, pv = "si")
```




### Sample dist PCoA & PERMANOVA
```{r}
pcoa <- pcoa(dist)
phy.ord <- cazy.phy
sample_data(phy.ord)$Season <- ordered(sample_data(phy.ord)$Season, levels = c("Summer", "Winter", "Spring"))

#tiff("aaas.pcoa.tiff", width=8, height=6, units="in", res=300)
plot_ordination(physeq = phy.ord, ordination = pcoa, axes = c(1,2),
                color = "Season") +
  geom_point(size=10) +
  scale_color_manual(values=c("#00cccc", "#008484", "#004f4f")) +
  ggtitle("CAZyme Profiles") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size=20),
        axis.title.y = element_text(size=20),
        legend.title = element_text(size=20),
        legend.text = element_text(size=18),
        plot.title = element_blank())
#dev.off()



### Run PERMANOVA on DESEq Hellinger distance
adonis(dist ~ Season*Number, data=meta, permutations = 99999)
  # p-value = 0.3185
beta.tax = betadisper(d=dist, group=meta$Season) 
p <- permutest(beta.tax)
p$tab
  # p-value = 0.012

### Pairwise betadisp test
TukeyHSD(beta.tax, conf.level = 0.95)
  # Summer-Winter p-value = 0.5573697
  # Summer-Spring p-value = 0.0255338
  # Winter-Spring p-value = 0.1742978
```