---
title: "Code"
author: "Edna Chiang"
date: "February 5, 2018"
output: html_document
---

### Load Packages, scripts, and functions
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
library(MESS)
library(pgirmess)
library(Bolstad2)
library(phyloseq)
library(psych)
library(car)
library(dunn.test)
source('scripts/misc.R')
set.seed(1)
theme_set(theme_bw())
```

### Load Data
```{r}
load('crds.norm.RData')
load('crds.use.Rdata')
meta <- read.csv('metadata.csv')
```

### Prepare CRDS data
```{r}
# Add metadata
crds.use[, colnames(meta)[3:ncol(meta)]] <- NA
for(i in 1:nrow(crds.use)){
  meta.row <- which(meta$ID == crds.use$ID[i])
  crds.use[i, 7:ncol(crds.use)] <- meta[meta.row, 3:ncol(meta)]
}

# Calculate square root of AUC
crds.use$AUC <- as.numeric(crds.use$AUC)
minAUC <- min(crds.use$AUC)
crds.use$AUC_sqrt <- crds.use$AUC + (minAUC * -1)
crds.use$AUC_sqrt <- sqrt(crds.use$AUC_sqrt)

# Convert to numeric
crds.use$AvgD <- as.numeric(crds.use$AvgD)
crds.use$MaxD <- as.numeric(crds.use$MaxD)
crds.use$MaxSlope <- as.numeric(crds.use$MaxSlope)
crds.use$AUC <- as.numeric(crds.use$AUC)
crds.use$MaxD <- as.numeric(crds.use$MaxD)
crds.use$Baseline <- as.numeric(crds.use$Baseline)

# Order categorical variables
crds.use$Season <- ordered(crds.use$Season, levels = c("Summer", "Winter", "Spring"))
crds.use$Sex <- ordered(crds.use$Sex, levels = c("Female", "Male"))
crds.use$Antibiotics <- ordered(crds.use$Antibiotics, levels = c("No", "Yes"))
crds.use$Substrate <- ordered(crds.use$Substrate, levels = c("Inulin", "Saline"))
crds.use$Diet <- ordered(crds.use$Diet, levels = c("1", "2"))

# Remove outliers
crds.rem <- crds.use[-which(crds.use$ID == "S23"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S37"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S60"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W43"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W20"),]
  # This is due to odd metagenome
crds.rem <- crds.rem[-which(crds.rem$ID == "W50"),]

# Separate by substrate
crds.inu <- crds.rem[which(crds.rem$Substrate == "Inulin"),]
crds.sal <- crds.rem[which(crds.rem$Substrate == "Saline"),]

# Separate by substrate + season
crds.inu.s <- crds.inu[which(crds.inu$Season == "Summer"),]
crds.inu.w <- crds.inu[which(crds.inu$Season == "Winter"),]
crds.inu.p <- crds.inu[which(crds.inu$Season == "Spring"),]
crds.sal.s <- crds.sal[which(crds.sal$Season == "Summer"),]
crds.sal.w <- crds.sal[which(crds.sal$Season == "Winter"),]
crds.sal.p <- crds.sal[which(crds.sal$Season == "Spring"),]

# Separate bu substrate + antibiotics
crds.inu.noabx <- crds.inu[which(crds.inu$Antibiotics == "No"),]
crds.inu.abx <- crds.inu[which(crds.inu$Antibiotics == "Yes"),]
crds.sal.noabx <- crds.sal[which(crds.sal$Antibiotics == "No"),]
crds.sal.abx <- crds.sal[which(crds.sal$Antibiotics == "Yes"),]
```



### Test baseline
```{r}
### Inulin ###

# No ABX
res <- resid(lm(Baseline ~ Season, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(Baseline ~ Season, crds.inu.noabx)
  # p = 0.2583
summary(aov(Baseline ~ Season, crds.inu.noabx))
  # p = 1.39e-06
TukeyHSD(aov(Baseline ~ Season, crds.inu.noabx))
  # Summer-Winter adj p = 0.0000021; CI = 3.2838050 - 6.742862
  # Summer-Spring adj p = 0.4230985; CI = 0.8609569 - 2.598100
  # Winter-Spring adj p = 0.0000254; CI = -5.8742902 - -2.415234

# ABX
res <- resid(lm(Baseline ~ Season, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(Baseline ~ Season, crds.inu.abx)
  # p = 0.9975
summary(aov(Baseline ~ Season, crds.inu.abx))
  # p = 1.79e-06
TukeyHSD(aov(Baseline ~ Season, crds.inu.abx))
  # Summer-Winter adj p = 0.0000059; CI = 2.229910 - 4.711804
  # Summer-Spring adj p = 0.0000042; CI = 2.326577 - 4.808471
  # Winter-Spring adj p = 0.9736710; CI = -1.036158 - 1.229491



### Saline ###

# No ABX
res <- resid(lm(Baseline ~ Season, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(Baseline ~ Season, crds.sal.noabx)
  # p = 0.1286
summary(aov(Baseline ~ Season, crds.sal.noabx))
  # p = 0.000362
TukeyHSD(aov(Baseline ~ Season, crds.sal.noabx))
  # Summer-Winter adj p = 0.0002443; CI = 2.58160869 - 7.6650580
  # Summer-Spring adj p = 0.0542860; CI = -0.04069572 - 4.8578386
  # Winter-Spring adj p = 0.0289141; CI = -5.16402906 - -0.2654948


# ABX
res <- resid(lm(Baseline ~ Season, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(Baseline ~ Season, crds.sal.abx)
  # p = 0.004228
kruskal.test(Baseline ~ Season, crds.sal.abx)
  # p = 0.01121
dunn.test(x = crds.sal.abx$Baseline, g = crds.sal.abx$Season, method = "bh", label = T)
  # Summer-Winter adj p = 0.0071*
  # Summer-Spring adj p = 0.0193*
  # Winter-Spring adj p = 0.2427

```


### Plot Baseline
```{r}
### Prepare data for plotting
# Inulin
crds.inu$SeasonABX <- interaction(crds.inu$Season, crds.inu$Antibiotics)
crds.inu$SeasonABX <- ordered(crds.inu$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

# Saline
crds.sal$SeasonABX <- interaction(crds.sal$Season, crds.sal$Antibiotics)
crds.sal$SeasonABX <- ordered(crds.sal$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))


### AUC Dot Plots

# Steal Season legend
season.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = Baseline, color = Season, fill = Season)) +
                            geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
                                         position = position_dodge(0.7), stackratio = 0.5) +
                            scale_color_manual(values = c("#c98b00", "#006096", "#00966d")) +
                            scale_fill_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(t=1, unit='cm')))


# Steal ABX legend
abx.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = Baseline, fill = Antibiotics)) + 
                         geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5, 
                                      position = position_dodge(0.7), stackratio = 0.5) +
                         scale_fill_manual(values = c("black", "white")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(b=1, unit='cm')))




  
# Inulin
inu.base.plot <- ggplot(crds.inu, aes(x = Season, y = Baseline, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Inulin")  + 
  ylab(expression("Baseline"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



# Saline
sal.base.plot <- ggplot(crds.sal, aes(x = Season, y = Baseline, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Saline")  + 
  ylab(expression("Baseline"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



### Plot

#png("crds.base.png", width = 200, height = 75, units = "mm", res = 400)
gricrds.newpage()
pushViewport(viewport(layout=gricrds.layout(2,3, widths = c(1, 1, 0.3))))

print(inu.base.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=1))
grid.text("A", x=unit(0.065, "npc"), y=unit(0.93, "npc"), 
          vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=20,fontface="bold"))


print(sal.base.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=2))
grid.text("B", x=unit(0.065, "npc"), y=unit(0.93, "npc"),
          vp=viewport(layout.pos.row=1, layout.pos.col=2), gp=gpar(fontsize=20,fontface="bold"))

season.legend$vp <- viewport(layout.pos.row=1, layout.pos.col=3)
grid.draw(season.legend)
abx.legend$vp <- viewport(layout.pos.row=2, layout.pos.col=3)
grid.draw(abx.legend)
#dev.off()


#png("crds.base.png", width = 170, height = 75, units = "mm", res = 300)
```



### Test AUC_sqrt
```{r}
### Inulin ###

# No ABX
res <- resid(lm(AUC_sqrt ~ Season, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(AUC_sqrt ~ Season, crds.inu.noabx)
  # p = 0.167
summary(aov(AUC_sqrt ~ Season, crds.inu.noabx))
  # p = 0.105

# ABX
res <- resid(lm(AUC_sqrt ~ Season, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(AUC_sqrt ~ Season, crds.inu.abx)
  # p = 0.3323
summary(aov(AUC_sqrt ~ Season, crds.inu.abx))
  # p = 0.559



### Saline ###

# No ABX
res <- resid(lm(AUC_sqrt ~ Season, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.02206
  # Not Normal
fligner.test(AUC_sqrt ~ Season, crds.sal.noabx)
  # p = 0.3271
kruskal.test(AUC_sqrt ~ Season, crds.sal.noabx)
  # p = 0.1175

# ABX
res <- resid(lm(AUC_sqrt ~ Season, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(AUC_sqrt ~ Season, crds.sal.abx)
  # p = 0.7997
summary(aov(AUC_sqrt ~ Season, crds.sal.abx))
  # p = 0.128

```


### Plot AUC_sqrt
```{r}
### Prepare data for plotting
# Inulin
crds.inu$SeasonABX <- interaction(crds.inu$Season, crds.inu$Antibiotics)
crds.inu$SeasonABX <- ordered(crds.inu$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

# Saline
crds.sal$SeasonABX <- interaction(crds.sal$Season, crds.sal$Antibiotics)
crds.sal$SeasonABX <- ordered(crds.sal$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))


### AUC Dot Plots

# Steal Season legend
season.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = AUC_sqrt, color = Season, fill = Season)) +
                            geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
                                         position = position_dodge(0.7), stackratio = 0.5) +
                            scale_color_manual(values = c("#c98b00", "#006096", "#00966d")) +
                            scale_fill_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(t=1, unit='cm')))


# Steal ABX legend
abx.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = AUC_sqrt, fill = Antibiotics)) + 
                         geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5, 
                                      position = position_dodge(0.7), stackratio = 0.5) +
                         scale_fill_manual(values = c("black", "white")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(b=1, unit='cm')))




  
# Inulin
inu.AUC.plot <- ggplot(crds.inu, aes(x = Season, y = AUC_sqrt, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Inulin")  + 
  ylab(expression(sqrt("AUC")~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



# Saline
sal.AUC.plot <- ggplot(crds.sal, aes(x = Season, y = AUC_sqrt, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Saline")  + 
  ylab(expression(sqrt("AUC")~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



### Plot

#tiff("crds.AUC.tiff", width = 200, height = 75, units = "mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=grid.layout(2,3, widths = c(1, 1, 0.3))))

print(inu.AUC.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=1))
grid.text("A", x=unit(0.065, "npc"), y=unit(0.93, "npc"), 
          vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=20,fontface="bold"))


print(sal.AUC.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=2))
grid.text("B", x=unit(0.065, "npc"), y=unit(0.93, "npc"),
          vp=viewport(layout.pos.row=1, layout.pos.col=2), gp=gpar(fontsize=20,fontface="bold"))

season.legend$vp <- viewport(layout.pos.row=1, layout.pos.col=3)
grid.draw(season.legend)
abx.legend$vp <- viewport(layout.pos.row=2, layout.pos.col=3)
grid.draw(abx.legend)
#dev.off()
```


### Test AvgD
```{r}
### Inulin ###

# No ABX
res <- resid(lm(AvgD ~ Season, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(AvgD ~ Season, crds.inu.noabx)
  # p = 0.03463
kruskal.test(AvgD ~ Season, crds.inu.noabx)
  # p = 0.187

# ABX
res <- resid(lm(AvgD ~ Season, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(AvgD ~ Season, crds.inu.abx)
  # p = 0.2714
summary(aov(AvgD ~ Season, crds.inu.abx))
  # p = 0.592



### Saline ###

# No ABX
res <- resid(lm(AvgD ~ Season, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.002128
  # Not Normal
fligner.test(AvgD ~ Season, crds.sal.noabx)
  # p = 0.8126
kruskal.test(AvgD ~ Season, crds.sal.noabx)
  # p = 0.05586

# ABX
res <- resid(lm(AvgD ~ Season, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(AvgD ~ Season, crds.sal.abx)
  # p = 0.6339
summary(aov(AvgD ~ Season, crds.sal.abx))
  # p = 0.0492
TukeyHSD(aov(AvgD ~ Season, crds.sal.abx))
  # Summer-Winter adj p = 0.049383; CI = -2.3343025 - -0.002986351
  # Summer-Spring adj p = 0.1598825; CI = -1.9421614 - 0.280661384
  # Spring-Winter adj p = 0.7334754; CI = -1.503552538 - 0.8277636
```




### Plot AvgD
```{r}
### Prepare data for plotting
# Inulin
crds.inu$SeasonABX <- interaction(crds.inu$Season, crds.inu$Antibiotics)
crds.inu$SeasonABX <- ordered(crds.inu$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

# Saline
crds.sal$SeasonABX <- interaction(crds.sal$Season, crds.sal$Antibiotics)
crds.sal$SeasonABX <- ordered(crds.sal$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))


### AUC Dot Plots

# Steal Season legend
season.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = AvgD, color = Season, fill = Season)) +
                            geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
                                         position = position_dodge(0.7), stackratio = 0.5) +
                            scale_color_manual(values = c("#c98b00", "#006096", "#00966d")) +
                            scale_fill_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(t=1, unit='cm')))


# Steal ABX legend
abx.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = AvgD, fill = Antibiotics)) + 
                         geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5, 
                                      position = position_dodge(0.7), stackratio = 0.5) +
                         scale_fill_manual(values = c("black", "white")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(b=1, unit='cm')))




  
# Inulin
inu.avgD.plot <- ggplot(crds.inu, aes(x = Season, y = AvgD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Inulin")  + 
  ylab(expression("Average"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



# Saline
sal.avgD.plot <- ggplot(crds.sal, aes(x = Season, y = AvgD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Saline")  + 
  ylab(expression("Average"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



### Plot

#tiff("crds.avgD.tiff", width = 200, height = 75, units = "mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=grid.layout(2,3, widths = c(1, 1, 0.3))))

print(inu.avgD.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=1))
grid.text("A", x=unit(0.065, "npc"), y=unit(0.93, "npc"), 
          vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=20,fontface="bold"))


print(sal.avgD.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=2))
grid.text("B", x=unit(0.065, "npc"), y=unit(0.93, "npc"),
          vp=viewport(layout.pos.row=1, layout.pos.col=2), gp=gpar(fontsize=20,fontface="bold"))

season.legend$vp <- viewport(layout.pos.row=1, layout.pos.col=3)
grid.draw(season.legend)
abx.legend$vp <- viewport(layout.pos.row=2, layout.pos.col=3)
grid.draw(abx.legend)
#dev.off()
```


### Test MaxD
```{r}
### Inulin ###

# No ABX
res <- resid(lm(MaxD ~ Season, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(MaxD ~ Season, crds.inu.noabx)
  # p = 0.1326
summary(aov(MaxD ~ Season, crds.inu.noabx))
  # p = 0.0143
TukeyHSD(aov(MaxD ~ Season, crds.inu.noabx))
  # Summer-Winter adj p = 0.1423491; CI = -291.5699 - 2375.4194
  # Summer-Spring adj p = 0.4264198; CI = -1999.9697 - 667.0195
  # Winter-Spring adj p = 0.0112803; CI = -3041.8945 - -374.9052



# ABX
res <- resid(lm(MaxD ~ Season, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(MaxD ~ Season, crds.inu.abx)
  # p = 0.221
summary(aov(MaxD ~ Season, crds.inu.abx))
  # p = 0.938



### Saline ###

# No ABX
res <- resid(lm(MaxD ~ Season, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.0007598
  # Not Normal
fligner.test(MaxD ~ Season, crds.sal.noabx)
  # p = 0.2192
kruskal.test(MaxD ~ Season, crds.sal.noabx)
  # p = 0.1765

# ABX
res <- resid(lm(MaxD ~ Season, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(MaxD ~ Season, crds.sal.abx)
  # p = 0.981
summary(aov(MaxD ~ Season, crds.sal.abx))
  # p = 0.0447
TukeyHSD(aov(MaxD ~ Season, crds.sal.abx))
  # Summer-Winter adj p = 0.0769298; CI = -2.443737 - 0.11551526
  # Summer-Spring adj p = 0.0710440; CI = -2.350631 - 0.08952031
  # Winter-Spring adj p = 0.9974069; CI = -1.246071 - -1.31318192
```



### Plot MaxD
```{r}
### Prepare data for plotting
# Inulin
crds.inu$SeasonABX <- interaction(crds.inu$Season, crds.inu$Antibiotics)
crds.inu$SeasonABX <- ordered(crds.inu$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

# Saline
crds.sal$SeasonABX <- interaction(crds.sal$Season, crds.sal$Antibiotics)
crds.sal$SeasonABX <- ordered(crds.sal$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))


### AUC Dot Plots

# Steal Season legend
season.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = MaxD, color = Season, fill = Season)) +
                            geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
                                         position = position_dodge(0.7), stackratio = 0.5) +
                            scale_color_manual(values = c("#c98b00", "#006096", "#00966d")) +
                            scale_fill_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(t=1, unit='cm')))


# Steal ABX legend
abx.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = MaxD, fill = Antibiotics)) + 
                         geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5, 
                                      position = position_dodge(0.7), stackratio = 0.5) +
                         scale_fill_manual(values = c("black", "white")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(b=1, unit='cm')))




  
# Inulin
inu.maxD.plot <- ggplot(crds.inu, aes(x = Season, y = MaxD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Inulin")  + 
  ylab(expression("Maximum"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



# Saline
sal.maxD.plot <- ggplot(crds.sal, aes(x = Season, y = MaxD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Saline")  + 
  ylab(expression("Maximum"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



### Plot

#tiff("crds.maxD.tiff", width = 200, height = 75, units = "mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=grid.layout(2,3, widths = c(1, 1, 0.3))))

print(inu.maxD.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=1))
grid.text("A", x=unit(0.065, "npc"), y=unit(0.93, "npc"), 
          vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=20,fontface="bold"))


print(sal.maxD.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=2))
grid.text("B", x=unit(0.065, "npc"), y=unit(0.93, "npc"),
          vp=viewport(layout.pos.row=1, layout.pos.col=2), gp=gpar(fontsize=20,fontface="bold"))

season.legend$vp <- viewport(layout.pos.row=1, layout.pos.col=3)
grid.draw(season.legend)
abx.legend$vp <- viewport(layout.pos.row=2, layout.pos.col=3)
grid.draw(abx.legend)
#dev.off()
```



### Test MaxSlope
```{r}
### Inulin ###

# No ABX
res <- resid(lm(MaxSlope ~ Season, crds.inu.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(MaxSlope ~ Season, crds.inu.noabx)
  # p = 0.1476
summary(aov(MaxSlope ~ Season, crds.inu.noabx))
  # p = 0.00069
TukeyHSD(aov(MaxSlope ~ Season, crds.inu.noabx))
  # Summer-Winter adj p = 0.0127626; CI = 201.5148 - 1760.3792
  # Summer-Spring adj p = 0.3590466; CI = -1208.7012 - 350.1633
  # Winter-Spring adj p = 0.0005968; CI = -2189.6482 - -630.7837



# ABX
res <- resid(lm(MaxSlope ~ Season, crds.inu.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(MaxSlope ~ Season, crds.inu.abx)
  # p = 0.2762
summary(aov(MaxSlope ~ Season, crds.inu.abx))
  # p = 0.000138
TukeyHSD(aov(MaxSlope ~ Season, crds.inu.abx))
  # Summer-Winter adj p = 0.0001732; CI = -193.16212 - -67.87171
  # Summer-Spring adj p = 0.0006726; CI = -176.64258 - -51.35217
  # Winter-Spring adj p = 0.7406549; CI = -40.66745 - -73.70653



### Saline ###

# No ABX
res <- resid(lm(MaxSlope ~ Season, crds.sal.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.0001102
  # Not Normal
fligner.test(MaxSlope ~ Season, crds.sal.noabx)
  # p = 0.5991
kruskal.test(MaxSlope ~ Season, crds.sal.noabx)
  # p = 0.9395

# ABX
res <- resid(lm(MaxSlope ~ Season, crds.sal.abx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
leveneTest(MaxSlope ~ Season, crds.sal.abx)
  # p = 0.4466
summary(aov(MaxSlope ~ Season, crds.sal.abx))
  # p = 0.125





### Test Spring Variance
crds.inu.p.noabx <- crds.inu.noabx[which(crds.inu.noabx$Season == "Spring"),]
crds.inu.p.noabx$Day <- substr(crds.inu.p.noabx$Date_Sampled, 3, 4)
crds.inu.p.noabx$Day[1] <- 8
crds.inu.p.noabx$Day <- as.numeric(crds.inu.p.noabx$Day)

# Spearman Correlation
res <- resid(lm(MaxSlope ~ Day, crds.inu.p.noabx))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
cor.test(crds.inu.p.noabx$MaxSlope, crds.inu.p.noabx$Day, method = "kendall")
  # p-value = 0.5619
  # tau = -0.2380952
```



### Plot MaxSlope
```{r}
### Prepare data for plotting
# Inulin
crds.inu$SeasonABX <- interaction(crds.inu$Season, crds.inu$Antibiotics)
crds.inu$SeasonABX <- ordered(crds.inu$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

# Saline
crds.sal$SeasonABX <- interaction(crds.sal$Season, crds.sal$Antibiotics)
crds.sal$SeasonABX <- ordered(crds.sal$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))


### AUC Dot Plots

# Steal Season legend
season.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = MaxSlope, color = Season, fill = Season)) +
                            geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
                                         position = position_dodge(0.7), stackratio = 0.5) +
                            scale_color_manual(values = c("#c98b00", "#006096", "#00966d")) +
                            scale_fill_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(t=1, unit='cm')))


# Steal ABX legend
abx.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = MaxSlope, fill = Antibiotics)) + 
                         geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5, 
                                      position = position_dodge(0.7), stackratio = 0.5) +
                         scale_fill_manual(values = c("black", "white")) +
                            theme(legend.title = element_text(size=10, face="bold"),
                                  legend.text = element_text(size=10),
                                  legend.margin = margin(b=1, unit='cm')))




  
# Inulin
inu.slope.plot <- ggplot(crds.inu, aes(x = Season, y = MaxSlope, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Inulin")  + 
  ylab(expression("Maximum"~~delta^13~"C Slope"~"(%"[o]~~"/ time)")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



# Saline
sal.slope.plot <- ggplot(crds.sal, aes(x = Season, y = MaxSlope, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_se", fun.args = list(mult = 1), geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Saline")  + 
  ylab(expression("Maximum"~~delta^13~"C Slope"~"(%"[o]~~"/ time)")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(face="bold", size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(face="bold", size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
        legend.position = "none")



### Plot

#tiff("crds.slope.tiff", width = 200, height = 75, units = "mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=grid.layout(2,3, widths = c(1, 1, 0.3))))

print(inu.slope.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=1))
grid.text("A", x=unit(0.065, "npc"), y=unit(0.93, "npc"), 
          vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=20,fontface="bold"))


print(sal.slope.plot, vp=viewport(layout.pos.row=1:2, layout.pos.col=2))
grid.text("B", x=unit(0.065, "npc"), y=unit(0.93, "npc"),
          vp=viewport(layout.pos.row=1, layout.pos.col=2), gp=gpar(fontsize=20,fontface="bold"))

season.legend$vp <- viewport(layout.pos.row=1, layout.pos.col=3)
grid.draw(season.legend)
abx.legend$vp <- viewport(layout.pos.row=2, layout.pos.col=3)
grid.draw(abx.legend)
#dev.off()
```










### Plot Delta Curves
```{r}
# Steal Season legend
season.legend <- g_legend(ggplot(inu.all, aes(x=BinTime, y=Y_Mean, color=Season)) +
                         geom_line(aes(linetype=Antibiotics), size=1) +
                         geom_point(size=3, shape=21, aes(color=Season, 
                                    fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
                         scale_color_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
                         scale_fill_manual(values=c("#E69F00", "#0072B2", "#00bf8b"),
                                           na.value="white") +
                         theme(plot.title=element_text(hjust=0.5, size=20),
                               axis.title.x=element_text(size=20, 
                                  margin=margin(t=10, r=0, b=0, l=0)),
                               axis.title.y=element_text(size=18),
                               axis.text.x=element_text(size=16),
                               axis.text.y=element_text(size=16),
                               plot.margin = unit(c(0, 0.3, 0.3, 0.3), "cm"),
                                  #top, right, bottom, left
                               panel.grid.major.x = element_blank(),
                               panel.grid.minor.y = element_blank(),
                               panel.grid.minor.x = element_blank())
                         )
# Steal ABX legend
abx.legend <- g_legend(ggplot(inu.all, aes(x=BinTime, y=Y_Mean, color=Season)) +
                         geom_line(aes(linetype=Antibiotics), size=1) +
                         geom_point(size=3, shape=21, aes(color=Season, 
                                    fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
                         scale_color_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
                         scale_fill_manual(values=c("#E69F00", "#0072B2", "#00bf8b"),
                                           na.value="white") +
                         theme(plot.title=element_text(hjust=0.5, size=20),
                               axis.title.x=element_text(size=20, 
                                  margin=margin(t=10, r=0, b=0, l=0)),
                               axis.title.y=element_text(size=18),
                               axis.text.x=element_text(size=16),
                               axis.text.y=element_text(size=16),
                               plot.margin = unit(c(0, 0.3, 0.3, 0.3), "cm"),
                                  #top, right, bottom, left
                               panel.grid.major.x = element_blank(),
                               panel.grid.minor.y = element_blank(),
                               panel.grid.minor.x = element_blank())
                       )


### Inulin
inu.delta.plot <- ggplot(inu.all, aes(x=BinTime, y=Y_Mean, color=Season)) +
   geom_line(aes(linetype=Antibiotics), size=1) +
   geom_point(size=3, shape=21, aes(color=Season, 
                                    fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(values = c("#E69F00", "#0072B2", "#00bf8b"), guide = "none") +
  scale_fill_manual(values=c("#E69F00", "#0072B2", "#00bf8b"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Y_Mean-Y_SD, ymax = Y_Mean+Y_SD), 
                width=0.125, position=position_dodge(0.1)) +
  ggtitle(expression("Inulin"~~delta^13~"C")) +
  xlab("Time Since Gavage (hr)") +
  ylab(expression("Mean"~~delta^13~"C"~"(%"[o]~")")) +
  xlim(-0.6,4.1) +
  scale_y_continuous(breaks=c(0, 780, 1560, 2340, 3120, 3900), limits=c(-30, 3900)) +
  theme(plot.title=element_text(hjust=0.5, size=20),
        axis.title.x=element_text(size=20, 
                                  margin=margin(t=10, r=0, b=0, l=0)),
        axis.title.y=element_text(size=18),
        axis.text.x=element_text(size=16),
        axis.text.y=element_text(size=16),
        plot.margin = unit(c(0, 0.3, 0.3, 0.3), "cm"),
          #top, right, bottom, left
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())


## Saline
sal.delta.plot <- ggplot(sal.all, aes(x=BinTime, y=Y_Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
  geom_point(size=3, shape=21, aes(color=Season, 
                                   fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(values = c("#E69F00", "#0072B2", "#00bf8b"), guide = "none") +
  scale_fill_manual(values=c("#E69F00", "#0072B2", "#00bf8b"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Y_Mean-Y_SD, ymax = Y_Mean+Y_SD), width=0.125,
                position=position_dodge(0.1)) +
  scale_y_continuous(breaks=c(-30.0, -24.8, -19.6, -14.4, -9.2, -4.0), limits=c(-30, -4)) +
  ggtitle(expression("Saline"~~delta^13~"C")) +
  xlab("Time Since Gavage (hr)") +
  ylab(expression("Mean"~~delta^13~"C"~"(%"[o]~")")) +
  theme(plot.title=element_text(hjust=0.5, size=20),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14),
        axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())





### All 2 substrates on same axis
carb.plot <- ggplot(crds.sum, aes(x=BinTime, y=Y_Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
   geom_point(size=3, shape=21, aes(color=Season, fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Y_Mean-Y_SD, ymax = Y_Mean+Y_SD), width=0.125, position=position_dodge(0.1)) + 
  facet_grid(.~Substrate) +
  xlab("Time Since Gavage (hr)") +
  ylab(expression("Mean"~~delta^13~"C"~"(%"[o]~")")) +
  xlim(-0.6,4.41) +
  scale_y_continuous(breaks=c(0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000), limits=c(-30, 4000)) +
  theme(axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        axis.title.x = element_text(size=20, margin=margin(t=10, r=0, b=0, l=0)),
        axis.title.y = element_text(size=20, margin=margin(t=0, r=10, b=, l=0)),
        strip.text.x = element_text(size=20, face="bold"),
        strip.text.y = element_text(size=14),
        panel.spacing=unit(1, "lines"),
        legend.title = element_text(size = 20, face="bold"),
        legend.text = element_text(size=18),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        strip.background = element_blank()
  )



#png("deltaCurves.sd.png", width = 240, height = 110, units = "mm", res = 400)
carb.plot
#dev.off()
```



### Hib Dates
```{r}
### Load data

# Dates
dates <- read.csv('metadata_dates.csv')
dates_use <- dates[-which(dates$Season == "Summer"),]
rownames(dates_use) <- 1:nrow(dates_use)
dates_use <- dates_use[-13:-28,]
rownames(dates_use) <- 1:nrow(dates_use)
dates_use <- dates_use[-33:-40,]

# Remove outliers
dates_use <- dates_use[-which(dates_use$ID == "W20"),]



# Add CRDS metrics
for(k in 1:nrow(dates_use)){
  ID <- dates_use$ID[k]
  rowUse <- which(crds.rem$ID == ID)
  dates_use$AvgD[k] <- crds.rem$AvgD[rowUse]
  dates_use$MaxD[k] <- crds.rem$MaxD[rowUse]
  dates_use$MaxSlope[k] <- crds.rem$MaxSlope[rowUse]
  dates_use$AUC_sqrt[k] <- crds.rem$AUC_sqrt[rowUse]
  dates_use$Baseline[k] <- crds.rem$Baseline[rowUse]
}
  
# Separate Spring
dates.spr <- dates_use[which(dates_use$Season == "Spring"),]



### Test IBA-Hib Ratio

# Test normality
res <- resid(lm(IBA.Hib ~ Season, dates_use))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(IBA.Hib ~ Season, dates_use)
  # p-value = 0.8404
t.test(IBA.Hib ~ Season, dates_use)
  # p = 0.3313

```



### Plot Misc
```{r}
## All individuals
ggplot(crds.bin, aes(x=BinTime, y=Delta, color=ID)) +
  geom_line() +
  geom_point()

ggplot(crds.rem, aes(x=BinTime, y=Delta, color=ID)) +
  geom_line() +
  geom_point() +
  facet_grid(Season ~ Antibiotics)





ggplot(crds, aes(x=BinTime, y=Delta, color=ID)) +
  geom_line() +
  geom_point() +
  facet_grid(Season ~ Antibiotics) +
  guides(colour=F, linetype=F)
  


### Split into experimental groups --- INCLUDES OUTLIERS (switch to crds.bin to crds.rem if want to exclude outliers)
crds.split <- crds.bin %>%
  group_split(Substrate, Antibiotics, Season) %>%
  as.data.frame


### Plot
for(group in 1:length(crds.split$.)){
  df <- crds.split[[1]][[group]]
  print(df)
  name <- paste0(c(df$Substrate[1], as.character(df$Season[1]), df$Antibiotics[1]),
                 collapse = ".")
  plotName <- paste0(c(name, "tiff"), collapse = ".")
  
  plot <- ggplot(df, aes(x=RelTime, y=Delta, color=ID)) +
  geom_line() +
  geom_point() +
  facet_grid(ID ~.)
  
  #tiff(plotName, width = 10, height = 10, units = "in", res = 300)
  print(plot)
  #dev.off()

}












## Substrate/ABX
ggplot(crds.sum, aes(x=BinTime, y=Mean, color=Substrate)) +
  geom_line(aes(linetype=Antibiotics)) +
  geom_point() +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE))

## Inulin
inu.plot <- ggplot(inu.all, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
   geom_point(size=3, shape=21, aes(color=Season, fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) +
  ggtitle(expression("Inulin"~~delta^13~"C")) +
  xlab("Time Since Gavage (hr)") +
  ylab(expression("Mean"~~delta^13~"C"~"(%"[o]~")")) +
  xlim(-0.6,4.1) +
  scale_y_continuous(breaks=c(0, 625, 1250, 1875, 2500), limits=c(-30, 2700)) +
  theme(plot.title=element_text(hjust=0.5, size=20),
        axis.title.x=element_text(size=20, 
                                  margin=margin(t=10, r=0, b=0, l=0)),
        axis.title.y=element_text(size=18),
        axis.text.x=element_text(size=16),
        axis.text.y=element_text(size=16),
        plot.margin = unit(c(0, 0.3, 0.3, 0.3), "cm"),
          #top, right, bottom, left
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank()
  ) +
  guides(colour=F, linetype=F)



## Saline
sal.plot <- ggplot(sal.all, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
  geom_point(size=3, shape=21, aes(color=Season, fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) +
  ggtitle(expression("Saline"~~delta^13~"C")) +
  xlab("Time Since Gavage (hr)") +
  ylab(expression("Mean"~~delta^13~"C"~"(%"[o]~")")) +
  theme(plot.title=element_text(hjust=0.5, size=20),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14),
        axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank()) +
  guides(colour=F, linetype=F)




## Steal legend
steal.legend <- ggplot(sal.all, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
  geom_point(size=3) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) +
  ggtitle(expression("Saline"~~delta^13~"C")) +
  xlab("Time Since Gavage (hr)") +
  ylab(expression("Mean"~~delta^13~"C"~"(%"[o]~")")) +
  theme(plot.title=element_text(hjust=0.5, size=20),
        axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14),
        axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        legend.title = element_text(size=20, face="bold"),
        legend.text = element_text(size=18)
        )
legend <- g_legend(steal.legend)






### All 3 substrates on same axis
carb.plot <- ggplot(crds.rem, aes(x=BinTime, y=Mean, color=Season)) +
  geom_line(aes(linetype=Antibiotics), size=1) +
   geom_point(size=3, shape=21, aes(color=Season, fill=factor(ifelse(Antibiotics == "Yes", NA, Season)))) +
  scale_color_manual(name="Season", values=c("darkgoldenrod2", "dodgerblue3", "green3")) +
  scale_fill_manual(values=c("darkgoldenrod2", "dodgerblue3", "green3"), na.value="white", guide="none") +
  geom_errorbar(aes(ymin = Mean-SE, ymax = Mean+SE), width=0.125, position=position_dodge(0.1)) + 
  facet_grid(.~Substrate) +
  xlab("Time Since Gavage (hr)") +
  ylab(expression("Mean"~~delta^13~"C"~"(%"[o]~")")) +
  xlim(-0.6,4.1) +
  scale_y_continuous(breaks=c(0, 500, 1000, 1500, 2000, 2500), limits=c(-30, 2700)) +
  theme(axis.text.x = element_text(size=16),
        axis.text.y = element_text(size=16),
        axis.title.x = element_text(size=20, margin=margin(t=10, r=0, b=0, l=0)),
        axis.title.y = element_text(size=20, margin=margin(t=0, r=10, b=, l=0)),
        strip.text.x = element_text(size=20, face="bold"),
        #strip.text.y = element_text(size=14),
        panel.spacing=unit(1, "lines"),
        legend.title = element_text(size = 20, face="bold"),
        legend.text = element_text(size=18),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
  )



#tiff("crds.tiff", width = 12.75, height = 3.5, units = "in", res = 300)
carb.plot
dev.off()
```