---
title: "Test Diet"
author: "Edna Chiang"
date: "12/14/2021"
output: html_document
---

### Load Packages, scripts, and functions
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
library(MESS)
library(pgirmess)
library(Bolstad2)
library(phyloseq)
library(miLineage)
library(psych)
library(car)
library(equivalence)
source('scripts/import_crds.R')
source('scripts/bin_crds.R')
source('scripts/misc.R')
source('scripts/calc_delta_metrics.R')
set.seed(1)
theme_set(theme_bw())

### Stats Notes
# Use 'subset' in kruskal.test
# Do NOT use 'subset' in kruskalmc or pairwise.wilcox.test; it doesn't work!
```

### Load Data
```{r}
crds <- import.crds('CSV', 'metadata.csv')
```

### Bin RelTime
```{r}
crds.bin <- bin.crds(crds)
```

### Summarize by Substrate + ABX
```{r}
### Remove Inulin outliers
#crds.rem <- crds.bin[-which(crds.bin$ID == "S34"),]
crds.rem <- crds.bin[-which(crds.bin$ID == "S37"),]
  # ABX didn't work; high [DNA]
#crds.rem <- crds.rem[-which(crds.rem$ID == "S37"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "P28"),]
#crds.rem <- crds.rem[-which(crds.rem$ID == "P30"),]

# Remove Saline outliers
#crds.rem <- crds.rem[-which(crds.rem$ID == "W26"),]
#crds.rem <- crds.rem[-which(crds.rem$ID == "W43"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W50"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "P04"),]
  # This is an adult, not pup

crds.rem$Season <- ordered(crds.rem$Season, levels=c("Summer", "Winter", "Spring"))


# Summarize
#crds.sum <- crds.rem %>%
  group_by(Substrate, Antibiotics, Season, BinTime) %>%
  summarize(Y_Mean = mean(Delta),
            Y_Median = median(Delta),
            Y_SD = sd(Delta),
            Y_SE = se(Delta),
            Y_IQR = IQR(Delta),
            X_Mean = mean(RelTime),
            X_Median = median(RelTime),
            X_SD = sd(RelTime),
            X_SE = se(RelTime),
            X_IQR = IQR(RelTime),
            SampSize = n())
  # X_Mean is different from BinTime because BinTime was calculated with ABX and non-ABX combined
    # BinTime was calculated this way to make sure datapoints for all individuals will align together on x-axis. If datapoints are misaligned that can be confusing for the audience. So binning was done this way for the clearest visualization.
    # X_Mean is calculated for ABX and non-ABX separately, so there will be some variation
#crds.sum$Season <- ordered(crds.sum$Season, levels=c("Summer", "Winter", "Spring"))
```

### Test baseline - Diet
```{r}
### Separate samples
crds.base <- crds.rem[which(crds.rem$RelTime < 0),]
base.inu <- crds.base[which(crds.base$Substrate == "Inulin"),]
base.sal <- crds.base[which(crds.base$Substrate == "Saline"),]
base.inu.s <- base.inu[which(base.inu$Season == "Summer"),]
base.inu.w <- base.inu[which(base.inu$Season == "Winter"),]
base.inu.p <- base.inu[which(base.inu$Season == "Spring"),]
base.sal.s <- base.sal[which(base.sal$Season == "Summer"),]
base.sal.w <- base.sal[which(base.sal$Season == "Winter"),]
base.sal.p <- base.sal[which(base.sal$Season == "Spring"),]



### Check Normality

# Inulin Summer ABX
hist(base.inu.s[which(base.inu.s$Antibiotics == "Yes"),]$Delta)
qqnorm(base.inu.s[which(base.inu.s$Antibiotics == "Yes"),]$Delta)
qqline(base.inu.s[which(base.inu.s$Antibiotics == "Yes"),]$Delta)
shapiro.test(base.inu.s[which(base.inu.s$Antibiotics == "Yes"),]$Delta)
  # p-value = 0.2577
  # Normal

# Saline Summer ABX
hist(base.sal.s[which(base.sal.s$Antibiotics == "Yes"),]$Delta)
qqnorm(base.sal.s[which(base.sal.s$Antibiotics == "Yes"),]$Delta)
qqline(base.sal.s[which(base.sal.s$Antibiotics == "Yes"),]$Delta)
shapiro.test(base.sal.s[which(base.sal.s$Antibiotics == "Yes"),]$Delta)
  # p-value = 0.02765
  # Not Normal



# Test baseline

# Inulin Summer ABX
t.test(Delta ~ Diet, data = base.inu.s[which(base.inu.s$Antibiotics == "Yes"),])
  # p-value = 0.5671

# Saline Summer ABX
wilcox.test(Delta ~ Diet, data = base.sal.s[which(base.sal.s$Antibiotics == "Yes"),])
  # p-value = 0.8571



### Test baseline variance

# Inulin Summer ABX
var.test(Delta ~ Diet, data = base.inu.s[which(base.inu.s$Antibiotics == "Yes"),])
  # p-value = 0.2194

# Saline Summer ABX
fligner.test(Delta ~ Diet, data = base.sal.s[which(base.sal.s$Antibiotics == "Yes"),])
  # p-value = 0.04528*

```


### Calculate Delta Metrics
```{r}
# Calculate delta metrics
d.metrics <- calc.delta.metrics(crds.rem)
#write.csv(d.metrics, "delta_metrics.csv", row.names = F)
#d.metrics <- read.csv('delta_metrics.csv')

# Load metadata
meta <- read.csv('metadata.csv', fileEncoding="UTF-8-BOM")

# Add metadata to delta metrics
d.metrics[,colnames(meta)[3:12]] <- NA
for(sq in 1:nrow(d.metrics)){
  meta.row <- which(meta$ID == d.metrics$ID[sq])
  d.metrics[sq, 5:14] <- meta[meta.row, 3:12]
}

# Convert to numeric
d.metrics$TimeMaxD <- as.numeric(d.metrics$TimeMaxD)
d.metrics$Slope <- as.numeric(d.metrics$Slope)
d.metrics$SlopeTime <- as.numeric(d.metrics$SlopeTime)

# Order seasons
d.metrics$Season <- ordered(d.metrics$Season, levels=c("Summer", "Winter", "Spring"))

# Separate by substrate
d.inu <- d.metrics[which(d.metrics$Substrate == "Inulin"),]
d.sal <- d.metrics[which(d.metrics$Substrate == "Saline"),]

# Separate by substrate + ABX
d.inu.abx <- d.inu[which(d.inu$Antibiotics == "Yes"),]
d.inu.noabx <- d.inu[which(d.inu$Antibiotics == "No"),]
d.sal.abx <- d.sal[which(d.sal$Antibiotics == "Yes"),]
d.sal.noabx <- d.sal[which(d.sal$Antibiotics == "No"),]

# Separate by substrate + season
d.inu.s <- d.inu[which(d.inu$Season == "Summer"),]
d.inu.w <- d.inu[which(d.inu$Season == "Winter"),]
d.inu.p <- d.inu[which(d.inu$Season == "Spring"),]
d.sal.s <- d.sal[which(d.sal$Season == "Summer"),]
d.sal.w <- d.sal[which(d.sal$Season == "Winter"),]
d.sal.p <- d.sal[which(d.sal$Season == "Spring"),]
```

### Test Slope
```{r}
### Check Normality

# Inulin Summer ABX
hist(d.inu.s[which(d.inu.s$Antibiotics == "Yes"),]$Slope)
qqnorm(d.inu.s[which(d.inu.s$Antibiotics == "Yes"),]$Slope)
qqline(d.inu.s[which(d.inu.s$Antibiotics == "Yes"),]$Slope)
shapiro.test(d.inu.s[which(d.inu.s$Antibiotics == "Yes"),]$Slope)
  # p-value = 0.9513
  # Normal

# Saline Summer ABX
hist(d.sal.s[which(d.sal.s$Antibiotics == "Yes"),]$Slope)
qqnorm(d.sal.s[which(d.sal.s$Antibiotics == "Yes"),]$Slope)
qqline(d.sal.s[which(d.sal.s$Antibiotics == "Yes"),]$Slope)
shapiro.test(d.sal.s[which(d.sal.s$Antibiotics == "Yes"),]$Slope)
  # p-value = 0.6855
  # Normal



### Test Diet

# Inulin Summer ABX
t.test(Slope ~ Diet, data = d.inu.s[which(d.inu.s$Antibiotics == "Yes"),])
  # p-value = 0.6737

# Saline Summer ABX
t.test(Slope ~ Diet, data = d.sal.s[which(d.sal.s$Antibiotics == "Yes"),])
  # p-value = 0.2791




### Test Diet Variance

# Inulin Summer ABX
var.test(Slope ~ Diet, data = d.inu.s[which(d.inu.s$Antibiotics == "Yes"),])
  # p-value = 0.1498

# Saline Summer ABX
var.test(Slope ~ Diet, data = d.sal.s[which(d.sal.s$Antibiotics == "Yes"),])
  # p-value = 0.2161
```

### Calculate AUC
```{r}
# AUC = Area Under Curve
# Trapezoid Method

### Calculate AUC
ids <- unique(crds.rem$ID)
auc.df <- data.frame(crds.rem[1,])
auc.df <- auc.df[,-2:-3]
  # Remove Delta and CO2 cols
auc.df <- auc.df[,-13]
  # Remove BinTime col
colnames(auc.df) <- c("AUC", "Number", "ID", "Season", "Sex", "Antibiotics", "Substrate", "Diet", "Mom", "Mom_Location", "BodyMass", "BodyTemp")
auc.df$Ketones <- NA
  # Rename cols
meta <- read.csv('metadata.csv', fileEncoding="UTF-8-BOM")

#crds.rem= crds.bin
# First normalize Rel Time so 
#for (i in 2){
for (i in 1:length(ids)){
  ID <- ids[i]
  select <- crds.rem[which(crds.rem$ID == ID),]
    # Dataframe with CRDS values for 1 squirrel

  # Normalize delta value to baseline
  select$Delta <- select$Delta - select$Delta[1]
  
  # Remove baseline from AUC calculation because we care about the AUC after gavage
  # Since we already normalized delta value to baseline, we don't need that value anymore
  # Set baseline to gavage time = 0
  select[1,1] <- 0
  
  # Normalize AUC end time
  # Since length of experiment varies for each individual, we don't want experimental length to bias our AUC calculations
  # Normalize length to min time within each substrate
    # Inu = 4.0667
    # Sal = 2.21667
  if (select$Substrate == "Inulin") {
    max <- which(select$RelTime > 4.06667)
    select$RelTime[max] <- 4.06667
  } else if (select$Substrate == "Saline") {
    max <- which(select$RelTime > 2.21666667)
    select$RelTime[max] <- 2.21666667
  }

  # Create auc variable
  AUC <- 0
  
  # Run rectangle method integration - less accurate
  #for (j in 1:(nrow(select)-1)){
  #  AUC <- AUC + ((select$RelTime[j+1]-select$RelTime[j])*select$Delta[j+1])
  #}
  
  # Run trapezoid method integration - more accurate
  for(j in 1:(nrow(select)-1)){
    avgH <- (select$Delta[j+1]+select$Delta[j])/2
      # Calculates average height between start and end point
    width <- (select$RelTime[j+1]-select$RelTime[j])
    AUC <- AUC + (avgH*width)
  }
    
  auc.df[i,1] <- AUC
  auc.df[i, 2:12] <- select[1, 4:14]
  
  use <- which(meta$ID == ID)
  auc.df$Ketones[i] <- meta$Ketones[use]
}


### Subset by Substrate & Season
auc.inu <- auc.df[which(auc.df$Substrate == "Inulin"),]
auc.sal <- auc.df[which(auc.df$Substrate == "Saline"),]
auc.inu.s <- auc.inu[which(auc.inu$Season == "Summer"),]
auc.inu.w <- auc.inu[which(auc.inu$Season == "Winter"),]
auc.inu.p <- auc.inu[which(auc.inu$Season == "Spring"),]
auc.sal.s <- auc.sal[which(auc.sal$Season == "Summer"),]
auc.sal.w <- auc.sal[which(auc.sal$Season == "Winter"),]
auc.sal.p <- auc.sal[which(auc.sal$Season == "Spring"),]
```

### Test AUC
```{r}
### Check Normality

# Inulin Summer ABX
hist(auc.inu.s[which(auc.inu.s$Antibiotics == "Yes"),]$AUC)
qqnorm(auc.inu.s[which(auc.inu.s$Antibiotics == "Yes"),]$AUC)
qqline(auc.inu.s[which(auc.inu.s$Antibiotics == "Yes"),]$AUC)
shapiro.test(auc.inu.s[which(auc.inu.s$Antibiotics == "Yes"),]$AUC)
  # p-value = 0.1686
  # Normal

# Saline Summer ABX
hist(auc.sal.s[which(auc.sal.s$Antibiotics == "Yes"),]$AUC)
qqnorm(auc.sal.s[which(auc.sal.s$Antibiotics == "Yes"),]$AUC)
qqline(auc.sal.s[which(auc.sal.s$Antibiotics == "Yes"),]$AUC)
shapiro.test(auc.sal.s[which(auc.sal.s$Antibiotics == "Yes"),]$AUC)
  # p-value = 0.4136
  # Normal



### Test Diet

# Inulin Summer ABX
t.test(AUC ~ Diet, data = auc.inu.s[which(auc.inu.s$Antibiotics == "Yes"),])
  # p-value = 0.9514

# Saline Summer ABX
t.test(AUC ~ Diet, data = auc.sal.s[which(auc.sal.s$Antibiotics == "Yes"),])
  # p-value = 0.503



### Test Diet Variance

# Inulin Summer ABX
var.test(AUC ~ Diet, data = auc.inu.s[which(auc.inu.s$Antibiotics == "Yes"),])
  # p-value = 0.8792

# Saline Summer ABX
var.test(AUC ~ Diet, data = auc.sal.s[which(auc.sal.s$Antibiotics == "Yes"),])
  # p-value = 0.507
```


















