---
title: "Multiomics"
author: "Edna Chiang"
date: "4/27/2022"
output: html_document
---

### Load Libraries
```{r}
library(ape)
library(dplyr)
library(dunn.test)
library(effsize)
library(ggplot2)
library(grid)
library(gridExtra)
library(phyloseq)
library(picante)
library(pwr)
library(tidyr)
library(vegan)
source('scripts/misc.R')
theme_set(theme_bw())
set.seed(1)
```


### Load Data
```{r}
# Load metabolomic data
metab <- read.csv('metabolomics/metabolomics_use.csv', row.names = 1)
metab <- data.frame(t(metab))
for(i in 1:(ncol(metab) - 2)){
  metab[,i] <- as.numeric(metab[,i])
}
metab.noabx <- metab[which(metab$Antibiotics == "No"),]
metab.abx <- metab[which(metab$Antibiotics == "Yes"),]
metab.inu <- metab[which(metab$Substrate == "Inulin"),]
metab.sal <- metab[which(metab$Substrate == "Saline"),]

# Remove bad columns
metab.abx <- metab.abx[,-7]
metab.abx <- metab.abx[,-8:-9]
metab.inu <- metab.inu[,-10]
metab.inu <- metab.inu[,-7]


# Load metadata
meta <- read.csv('metadata.csv')

```


### Test Substrate
```{r}
metab.noabx.output <- data.frame(matrix(nrow = 1, ncol = 4))
colnames(metab.noabx.output) <- c("Compound", "P-value", "Lower_CI", "Upper_CI")
for(j in 1:(ncol(metab.noabx) - 2)){
  test <- wilcox.test(metab.noabx[,j] ~ Substrate, metab.noabx, conf.int = T)
  metab.noabx.output[j,] <- c(colnames(metab.noabx)[j], test$p.value, test$conf.int[1], test$conf.int[2])
}
metab.noabx.output$AdjP <- p.adjust(metab.noabx.output$`P-value`, "BH")
#write.table(metab.noabx.output, file = 'metabolomics/NoABX_TestSubstrate.csv', sep = ",", row.names = F)

metab.abx.output <- data.frame(matrix(nrow = 1, ncol = 4))
colnames(metab.abx.output) <- c("Compound", "P-value", "Lower_CI", "Upper_CI")
for(j in 1:(ncol(metab.abx) - 2)){
  test <- wilcox.test(metab.abx[,j] ~ Substrate, metab.abx, conf.int = T)
  metab.abx.output[j,] <- c(colnames(metab.abx)[j], test$p.value, test$conf.int[1], test$conf.int[2])
}
metab.abx.output$AdjP <- p.adjust(metab.abx.output$`P-value`, "BH")
#write.table(metab.abx.output, file = 'metabolomics/ABX_TestSubstrate.csv', sep = ",", row.names = F)
```

### Test ABX
```{r}
metab.inu.output <- data.frame(matrix(nrow = 1, ncol = 4))
colnames(metab.inu.output) <- c("Compound", "P-value", "Lower_CI", "Upper_CI")
for(j in 1:(ncol(metab.inu) - 2)){
  test <- wilcox.test(metab.inu[,j] ~ Antibiotics, metab.inu, conf.int = T)
  metab.inu.output[j,] <- c(colnames(metab.inu)[j], test$p.value, test$conf.int[1], test$conf.int[2])
}
metab.inu.output$AdjP <- p.adjust(metab.inu.output$`P-value`, "BH")
#write.table(metab.inu.output, file = 'metabolomics/Inulin_TestABX.csv', sep = ",", row.names = F)


metab.sal.output <- data.frame(matrix(nrow = 1, ncol = 4))
colnames(metab.sal.output) <- c("Compound", "P-value", "Lower_CI", "Upper_CI")
for(j in 1:(ncol(metab.sal) - 2)){
  test <- wilcox.test(metab.sal[,j] ~ Antibiotics, metab.sal, conf.int = T)
  metab.sal.output[j,] <- c(colnames(metab.sal)[j], test$p.value, test$conf.int[1], test$conf.int[2])
}
metab.sal.output$AdjP <- p.adjust(metab.sal.output$`P-value`, "BH")
#write.table(metab.sal.output, file = 'metabolomics/Saline_TestABX.csv', sep = ",", row.names = F)
```


### Plot
```{r}
### Prepare data for plotting
metab$SubstrateABX <- interaction(metab$Substrate, metab$Antibiotics)
metab$SubstrateABX <- ordered(metab$SubstrateABX, levels = c("Inulin.No", "Inulin.Yes", "Saline.No", "Saline.Yes"))


### Acetate
acetate.plot <- ggplot(metab, aes(x = Substrate, y = Acetate, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Acetate")  + 
  ylab("Acetate abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Butyrate
butyrate.plot <- ggplot(metab, aes(x = Substrate, y = Butyrate, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Butyrate")  + 
  ylab("Butyrate abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Fructose
fructose.plot <- ggplot(metab, aes(x = Substrate, y = Fructose, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Fructose")  + 
  ylab("Fructose abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Glucose
glucose.plot <- ggplot(metab, aes(x = Substrate, y = Glucose, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Glucose")  + 
  ylab("Glucose abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Glutamate
glutamate.plot <- ggplot(metab, aes(x = Substrate, y = Glutamate, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Glutamate")  + 
  ylab("Glutamate abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Lactate
lactate.plot <- ggplot(metab, aes(x = Substrate, y = Lactate, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Lactate")  + 
  ylab("Lactate abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Mannose
mannose.plot <- ggplot(metab, aes(x = Substrate, y = Mannose, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Mannose")  + 
  ylab("Mannose abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Phenylalanine
phenylalanine.plot <- ggplot(metab, aes(x = Substrate, y = Phenylalanine, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Phenylalanine")  + 
  ylab("Phenylalanine abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Propionate
propionate.plot <- ggplot(metab, aes(x = Substrate, y = Propionate, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Propionate")  + 
  ylab("Propionate abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")

### Uracil
#uracil.plot <- ggplot(metab, aes(x = Substrate, y = Uracil, color = SubstrateABX,
                                    fill = SubstrateABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("gray25", "#000000", "gray70", "gray70")) +
  scale_fill_manual(values = c("gray25", "white", "gray50", "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Uracil")  + 
  ylab("Uracil abundance per mg content") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")
```


### Save plots
```{r}
tiff("metabolites.tiff", width = 6, height = 9, units = "in", res = 600)
grid.newpage()
pushViewport(viewport(layout=grid.layout(4,2, widths = c(1, 1))))

print(acetate.plot, vp=viewport(layout.pos.row=1, layout.pos.col=1))
grid.text("A", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(butyrate.plot, vp=viewport(layout.pos.row=1, layout.pos.col=2))
grid.text("B", x=unit(0.063, "npc"), y=unit(0.95, "npc"),
          vp=viewport(layout.pos.row=1, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))


print(fructose.plot, vp=viewport(layout.pos.row=2, layout.pos.col=1))
grid.text("C", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=2, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(glucose.plot, vp=viewport(layout.pos.row=2, layout.pos.col=2))
grid.text("D", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=2, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))



print(glutamate.plot, vp=viewport(layout.pos.row=3, layout.pos.col=1))
grid.text("E", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=3, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(lactate.plot, vp=viewport(layout.pos.row=3, layout.pos.col=2))
grid.text("F", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=3, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))



print(phenylalanine.plot, vp=viewport(layout.pos.row=4, layout.pos.col=1))
grid.text("G", x=unit(0.063, "npc"), y=unit(1, "npc"), 
          vp=viewport(layout.pos.row=4, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(propionate.plot, vp=viewport(layout.pos.row=4, layout.pos.col=2))
grid.text("H", x=unit(0.063, "npc"), y=unit(1, "npc"), 
          vp=viewport(layout.pos.row=4, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))


#season.legend$vp <- viewport(layout.pos.row=1:4, layout.pos.col=3)
#grid.draw(season.legend)
#abx.legend$vp <- viewport(layout.pos.row=1:4, layout.pos.col=3)
#grid.draw(abx.legend)
dev.off()
```