---
title: "Code_TestABX"
author: "Edna Chiang"
date: "12/14/2021"
output: html_document
---
### Load Packages, scripts, and functions
```{r}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
library(car)
library(Rmisc)
library(boot)
library(simpleboot)
source('scripts/misc.R')
set.seed(1)
theme_set(theme_bw())
```

### Load Data
```{r}
load('crds.norm.RData')
load('crds.use.Rdata')
meta <- read.csv('metadata.csv')
```

### Prepare CRDS data
```{r}
# Add metadata
crds.use[, colnames(meta)[3:ncol(meta)]] <- NA
for(i in 1:nrow(crds.use)){
  meta.row <- which(meta$ID == crds.use$ID[i])
  crds.use[i, 7:ncol(crds.use)] <- meta[meta.row, 3:ncol(meta)]
}

# Calculate square root of AUC
crds.use$AUC <- as.numeric(crds.use$AUC)
minAUC <- min(crds.use$AUC)
crds.use$AUC_sqrt <- crds.use$AUC + (minAUC * -1)
crds.use$AUC_sqrt <- sqrt(crds.use$AUC_sqrt)

# Convert to numeric
crds.use$AvgD <- as.numeric(crds.use$AvgD)
crds.use$MaxD <- as.numeric(crds.use$MaxD)
crds.use$MaxSlope <- as.numeric(crds.use$MaxSlope)
crds.use$AUC <- as.numeric(crds.use$AUC)
crds.use$MaxD <- as.numeric(crds.use$MaxD)
crds.use$Baseline <- as.numeric(crds.use$Baseline)

# Order categorical variables
crds.use$Season <- ordered(crds.use$Season, levels = c("Summer", "Winter", "Spring"))
crds.use$Sex <- ordered(crds.use$Sex, levels = c("Female", "Male"))
crds.use$Antibiotics <- ordered(crds.use$Antibiotics, levels = c("No", "Yes"))
crds.use$Substrate <- ordered(crds.use$Substrate, levels = c("Inulin", "Saline"))
crds.use$Diet <- ordered(crds.use$Diet, levels = c("1", "2"))

# Remove outliers
crds.rem <- crds.use[-which(crds.use$ID == "S23"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S37"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "S60"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W43"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "W20"),]
  # This is due to odd metagenome
crds.rem <- crds.rem[-which(crds.rem$ID == "W50"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "P20"),]
crds.rem <- crds.rem[-which(crds.rem$ID == "P22"),]

# Separate by substrate
crds.inu <- crds.rem[which(crds.rem$Substrate == "Inulin"),]
crds.sal <- crds.rem[which(crds.rem$Substrate == "Saline"),]

# Separate by substrate + season
crds.inu.s <- crds.inu[which(crds.inu$Season == "Summer"),]
crds.inu.w <- crds.inu[which(crds.inu$Season == "Winter"),]
crds.inu.p <- crds.inu[which(crds.inu$Season == "Spring"),]
crds.sal.s <- crds.sal[which(crds.sal$Season == "Summer"),]
crds.sal.w <- crds.sal[which(crds.sal$Season == "Winter"),]
crds.sal.p <- crds.sal[which(crds.sal$Season == "Spring"),]
```




### Test AUC_sqrt
```{r}
### Inulin ###

# Summer
res <- resid(lm(AUC_sqrt ~ Antibiotics, crds.inu.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AUC_sqrt ~ Antibiotics, crds.inu.s)
  # p = 0.01146
  # CI = 2.223386 127.340287
wilcox.test(AUC_sqrt ~ Antibiotics, crds.inu.s, conf.int = T)
  # p = 0.002525
  # CI = 19.13140 42.13401


# Winter
res <- resid(lm(AUC_sqrt ~ Antibiotics, crds.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.02815
  # Not Normal
fligner.test(AUC_sqrt ~ Antibiotics, crds.inu.w)
  # p = 0.01802
b2 <- two.boot(sample1 = crds.inu.w$AUC_sqrt[which(crds.inu.w$Antibiotics == "No")], 
         sample2 = crds.inu.w$AUC_sqrt[which(crds.inu.w$Antibiotics == "Yes")],
         FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # CI = 45.1, 338.1
wilcox.test(AUC_sqrt ~ Antibiotics, crds.inu.w, conf.int = T)
  # p = 0.1282
  # CI = -1.393805 30.259635


# Spring
res <- resid(lm(AUC_sqrt ~ Antibiotics, crds.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AUC_sqrt ~ Antibiotics, crds.inu.p)
  # p = 0.002489
  # CI = 3.770332 157.522367
wilcox.test(AUC_sqrt ~ Antibiotics, crds.inu.p, conf.int = T)
  # p = 0.002331
  # CI = 13.03106 67.80970





### Saline ###

# Summer
res <- resid(lm(AUC_sqrt ~ Antibiotics, crds.sal.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AUC_sqrt ~ Antibiotics, crds.sal.s)
  # p = 0.03349
  # CI = 1.210118 61.801662
wilcox.test(AUC_sqrt ~ Antibiotics, crds.sal.s, conf.int = T)
  # p = 0.04113
  # CI = 0.01303972 0.47025504

# Winter
res <- resid(lm(AUC_sqrt ~ Antibiotics, crds.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AUC_sqrt ~ Antibiotics, crds.sal.w)
  # p = 0.4268
  # 0.2515625 17.4040116
t.test(AUC_sqrt ~ Antibiotics, crds.sal.w, conf.int = T)
  # p = 0.05829
  # CI = -0.008916618  0.416216269


# Spring
res <- resid(lm(AUC_sqrt ~ Antibiotics, crds.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AUC_sqrt ~ Antibiotics, crds.sal.p)
  # p = 0.04975
  # CI = 1.002777 57.432214
wilcox.test(AUC_sqrt ~ Antibiotics, crds.sal.p, conf.int= T)
  # p = 0.4318
  # CI = -0.1016435  0.1944076




# F test
p.adjust(c(0.01146, 0.01802, 0.002489, 0.03349, 0.4268, 0.04975), "BH")
  # Inulin Summer = 0.034380*
  # Inulin Winter = 0.036040*
  # Inulin Spring = 0.014934*
  # Saline Summer = 0.050235~
  # Saline Winter = 0.426800
  # Saline Spring = 0.059700~


# T-test
p.adjust(c(0.002525,  0.1282, 0.002331, 0.04113, 0.05829, 0.4318), "BH")
  # Inulin Summer = 0.007575*
  # Inulin Winter = 0.153840
  # Inulin Spring = 0.007575*
  # Saline Summer = 0.082260~
  # Saline Winter = 0.087435~
  # Saline Spring = 0.431800
```


### Test AvgD
```{r}
### Inulin ###

# Summer
res <- resid(lm(AvgD ~ Antibiotics, crds.inu.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AvgD ~ Antibiotics, crds.inu.s)
  # p = 0.0002082
  # CI = 17.28148 989.76457
wilcox.test(AvgD ~ Antibiotics, crds.inu.s, conf.int = T)
  # p = 0.002525
  # CI = 509.1071 1272.3075


# Winter
res <- resid(lm(AvgD ~ Antibiotics, crds.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.04713
  # Not Normal
fligner.test(AvgD ~ Antibiotics, crds.inu.w)
  # p = 0.01802
b2 <- two.boot(sample1 = crds.inu.w$AvgD[which(crds.inu.w$Antibiotics == "No")], 
         sample2 = crds.inu.w$AvgD[which(crds.inu.w$Antibiotics == "Yes")],
         FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # CI = 67310, 249621
wilcox.test(AvgD ~ Antibiotics, crds.inu.w, conf.int = T)
  # p = 0.07284
  # CI = -15.82484 750.23853


# Spring
res <- resid(lm(AvgD ~ Antibiotics, crds.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but I think it's sigmoid/skewed
  # Not Normal
fligner.test(AvgD ~ Antibiotics, crds.inu.p)
  # p = 0.02847
b2 <- two.boot(sample1 = crds.inu.p$AvgD[which(crds.inu.p$Antibiotics == "No")], 
         sample2 = crds.inu.p$AvgD[which(crds.inu.p$Antibiotics == "Yes")],
         FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # 417707, 981951
wilcox.test(AvgD ~ Antibiotics, crds.inu.p, conf.int = T)
  # p = 0.002331
  # CI = 156.0996 1938.4486





### Saline ###

# Summer
res <- resid(lm(AvgD ~ Antibiotics, crds.sal.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AvgD ~ Antibiotics, crds.sal.s)
  # p = 0.02984
  # CI = 1.277188 65.226985
wilcox.test(AvgD ~ Antibiotics, crds.sal.s, conf.int = T)
  # p = 0.04113
  # CI = 0.2408333 5.7647222


# Winter
res <- resid(lm(AvgD ~ Antibiotics, crds.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Not normal due to 1 outlier
  # Normal
var.test(AvgD ~ Antibiotics, crds.sal.w)
  # p = 0.1519
  # CI = 0.5165517 35.7369262
t.test(AvgD ~ Antibiotics, crds.sal.w, conf.int = T)
  # p = 0.07599
  # CI = -0.2306684  3.6421616


# Spring
res <- resid(lm(AvgD ~ Antibiotics, crds.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(AvgD ~ Antibiotics, crds.sal.p)
  # p = 0.1555
  # CI = 0.5119787 29.3226273
t.test(AvgD ~ Antibiotics, crds.sal.p)
  # p = 0.3399
  # CI = -0.6141366  1.5992525




# F test
p.adjust(c(0.0002082, 0.01802, 0.02847, 0.02984, 0.1519, 0.1555), "BH")
  # Inulin Summer = 0.0012492*
  # Inulin Winter = 0.0447600*
  # Inulin Spring = 0.0447600*
  # Saline Summer = 0.0447600*
  # Saline Winter = 0.1555000
  # Saline Spring = 0.1555000


# T-tests
p.adjust(c(0.002525, 0.07284, 0.002331, 0.04113, 0.07599, 0.3399), "BH")
  # Inulin Summer = 0.007575*
  # Inulin Winter = 0.09118~
  # Inulin Spring = 0.007575*
  # Saline Summer = 0.082260~
  # Saline Winter = 0.09118~
  # Saline Spring = 0.339900

```

### Test MaxD
```{r}
### Inulin ###

# Summer
res <- resid(lm(MaxD ~ Antibiotics, crds.inu.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(MaxD ~ Antibiotics, crds.inu.s)
  # p = 0.0006131
  # CI = 10.02017 573.88672
wilcox.test(MaxD ~ Antibiotics, crds.inu.s, conf.int = T)
  # p = 0.002525
  # CI =  928.6176 2425.2837

# Winter
res <- resid(lm(MaxD ~ Antibiotics, crds.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.02949
  # Not Normal
fligner.test(MaxD ~ Antibiotics, crds.inu.w)
  # p = 0.01802
b2 <- two.boot(sample1 = crds.inu.w$MaxD[which(crds.inu.w$Antibiotics == "No")], 
         sample2 = crds.inu.w$MaxD[which(crds.inu.w$Antibiotics == "Yes")],
         FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # CI = 91416, 344362 
wilcox.test(MaxD ~ Antibiotics, crds.inu.w, conf.int = T)
  # p = 0.01107
  # CI = 10.7200 972.7889


# Spring
res <- resid(lm(MaxD ~ Antibiotics, crds.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but looks sigmoidal
  # Not Normal
fligner.test(MaxD ~ Antibiotics, crds.inu.p)
  # p = 0.02847
b2 <- two.boot(sample1 = crds.inu.p$MaxD[which(crds.inu.p$Antibiotics == "No")], 
         sample2 = crds.inu.p$MaxD[which(crds.inu.p$Antibiotics == "Yes")],
         FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # 912266, 2810506
wilcox.test(MaxD ~ Antibiotics, crds.inu.p, conf.int = T)
  # p = 0.001166
  # CI = 901.4787 3555.5800




### Saline ###

# Summer
res <- resid(lm(MaxD ~ Antibiotics, crds.sal.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(MaxD ~ Antibiotics, crds.sal.s)
  # p = 0.03139
  # CI = 1.247274 63.699233
wilcox.test(MaxD ~ Antibiotics, crds.sal.s, conf.int = T)
  # p = 0.06494
  # CI =  -0.252500  5.465833


# Winter
res <- resid(lm(MaxD ~ Antibiotics, crds.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.02549
  # Test says not normal, but that's just because of 1 outlier
  # Normal
var.test(MaxD ~ Antibiotics, crds.sal.w)
  # p = 0.0483
  # CI = 1.01974 70.54935
wilcox.test(MaxD ~ Antibiotics, crds.sal.w, conf.int = T)
  # p = 0.01732
  # CI = 0.675614 6.848148


# Spring
res <- resid(lm(MaxD ~ Antibiotics, crds.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(MaxD ~ Antibiotics, crds.sal.p)
  # p = 0.03707
  # CI = 1.181607 67.674355
wilcox.test(MaxD ~ Antibiotics, crds.sal.p, conf.int = T)
  # p = 0.4318
  # CI = -0.9066667  1.8573333




# F test
p.adjust(c(0.0006131, 0.01802, 0.02847, 0.03139, 0.0483, 0.03707), "BH")
  # Inulin Summer = 0.0036786*
  # Inulin Winter = 0.0444840*
  # Inulin Spring = 0.0444840*
  # Saline Summer = 0.0444840*
  # Saline Winter = 0.0483000*
  # Saline Spring = 0.0444840*


# T-test
p.adjust(c(0.002525, 0.01107, 0.001166, 0.06494, 0.01732, 0.4318), "BH")
  # Inulin Summer = 0.007575*
  # Inulin Winter = 0.022140*
  # Inulin Spring = 0.006996*
  # Saline Summer = 0.077928~
  # Saline Winter = 0.025980~
  # Saline Spring = 0.431800

```









### Test MaxSlope
```{r}
### Inulin ###

# Summer
res <- resid(lm(MaxSlope ~ Antibiotics, crds.inu.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says not normal, but that's because of 3 outliers
  # Normal
var.test(MaxSlope ~ Antibiotics, crds.inu.s)
  # p = 9.695e-05
  # CI = 25.3807 1453.6324
wilcox.test(MaxSlope ~ Antibiotics, crds.inu.s, conf.int = T)
  # p = 0.002525
  # CI = 1129.152 2267.778


# Winter
res <- resid(lm(MaxSlope ~ Antibiotics, crds.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but looks not normal
  # Not Normal
fligner.test(MaxSlope ~ Antibiotics, crds.inu.w)
  # p = 0.01802
b2 <- two.boot(sample1 = crds.inu.w$MaxSlope[which(crds.inu.w$Antibiotics == "No")], 
         sample2 = crds.inu.w$MaxSlope[which(crds.inu.w$Antibiotics == "Yes")],
         FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # 20893, 144651
wilcox.test(MaxSlope ~ Antibiotics, crds.inu.w, conf.int = T)
  # p = 0.006993
  # CI = 108.1775 470.3333


# Spring
res <- resid(lm(MaxSlope ~ Antibiotics, crds.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but looks not normal
  # Not Normal
fligner.test(MaxSlope ~ Antibiotics, crds.inu.p)
  # p = 0.02858
b2 <- two.boot(sample1 = crds.inu.p$MaxSlope[which(crds.inu.p$Antibiotics == "No")], 
         sample2 = crds.inu.p$MaxSlope[which(crds.inu.p$Antibiotics == "Yes")],
         FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # 222312, 863511
wilcox.test(MaxSlope ~ Antibiotics, crds.inu.p, conf.int = T)
  # p = 0.001166
  # CI = 1010.309 2393.546





### Saline ###

# Summer
res <- resid(lm(MaxSlope ~ Antibiotics, crds.sal.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(MaxSlope ~ Antibiotics, crds.sal.s)
  # p = 0.01687
  # CI = 1.65725 84.63705
wilcox.test(MaxSlope ~ Antibiotics, crds.sal.s, conf.int = T)
  # p = 0.5887
  # CI = -1.610948  9.109071


# Winter
res <- resid(lm(MaxSlope ~ Antibiotics, crds.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says not normal, but that's only because of 2 outliers
  # Normal
var.test(MaxSlope ~ Antibiotics, crds.sal.w)
  # p = 0.01825
  # CI = 1.741273 120.467578
wilcox.test(MaxSlope ~ Antibiotics, crds.sal.w, conf.int = T)
  # p = 0.329
  # CI = -1.843268  5.774679


# Spring
res <- resid(lm(MaxSlope ~ Antibiotics, crds.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(MaxSlope ~ Antibiotics, crds.sal.p)
  # p = 0.2028
  # CI = 0.03444641 1.97285412
t.test(MaxSlope ~ Antibiotics, crds.sal.p)
  # p = 0.5455
  # CI = -3.780182  2.218957



# F test
p.adjust(c(9.695e-05, 0.01802, 0.02858, 0.01687, 0.01825, 0.2028), "BH")
  # Inulin Summer = 0.0005817* 
  # Inulin Winter = 0.0273750*
  # Inulin Spring = 0.0342960*
  # Saline Summer = 0.0273750*
  # Saline Winter = 0.0273750*
  # Saline Spring = 0.2028000


# T-test
p.adjust(c(0.002525, 0.006993, 0.001166, 0.5887, 0.329, 0.5455), "BH")
  # Inulin Summer = 0.007575*
  # Inulin Winter = 0.013986*
  # Inulin Spring = 0.006996*
  # Saline Summer = 0.588700 
  # Saline Winter = 0.493500 
  # Saline Spring = 0.588700

```


### Test DNA Yield
```{r}
# Load data
dna <- read.csv('dna.csv')
dna.c <- dna[which(grepl("CC", dna$Sample) == T),]

# Remove outliers
dna.c <- dna.c[-which(dna.c$Squirrel == "S23"),]
dna.c <- dna.c[-which(dna.c$Squirrel == "S37"),]
dna.c <- dna.c[-which(dna.c$Squirrel == "S60"),]
dna.c <- dna.c[-which(dna.c$Squirrel == "W43"),]
dna.c <- dna.c[-which(dna.c$Squirrel == "W20"),]
  # This is due to odd metagenome
dna.c <- dna.c[-which(dna.c$Squirrel == "W50"),]
dna.c <- dna.c[-which(dna.c$Squirrel == "P20"),]
dna.c <- dna.c[-which(dna.c$Squirrel == "P22"),]

dna.c$Metabolism <- "a"
dna.c$Metabolism[which(dna.c$Season == "Winter")] <- "Hibernation"
dna.c$Metabolism[which(dna.c$Season != "Winter")] <- "Active"
dna.c$Metabolism <- ordered(dna.c$Metabolism, levels = c("Active", "Hibernation"))
dna.c$Season <- ordered(dna.c$Season, levels = c("Summer", "Winter", "Spring"))
dna.s <- dna.c[which(dna.c$Season == "Summer"),]
dna.w <- dna.c[which(dna.c$Season == "Winter"),]
dna.p <- dna.c[which(dna.c$Season == "Spring"),]
dna.inu.s <- dna.s[which(dna.s$Substrate == "Inulin"),]
dna.inu.w <- dna.w[which(dna.w$Substrate == "Inulin"),]
dna.inu.p <- dna.p[which(dna.p$Substrate == "Inulin"),]
dna.sal.s <- dna.s[which(dna.s$Substrate == "Saline"),]
dna.sal.w <- dna.w[which(dna.w$Substrate == "Saline"),]
dna.sal.p <- dna.p[which(dna.p$Substrate == "Saline"),]



### Inulin

# Summer
res <- resid(lm(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.03586
  # Not Normal
fligner.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.s)
  # p = 0.007437
b2 <- two.boot(sample1 = dna.inu.s$DNA_Yield_.ng.mg.[which(dna.inu.s$Antibiotics == "No Antibiotics")], sample2 = dna.inu.s$DNA_Yield_.ng.mg.[which(dna.inu.s$Antibiotics == "Antibiotics")], FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # CI = 579, 2817
wilcox.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.s, conf.int = T)
  # p = 0.004101
  # CI = -150.91699  -47.70186

# Winter
res <- resid(lm(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Not normal because of 2 outliers, so go w/ normal
  # Normal
var.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.w)
  # p = 6.495e-06
  # CI = 0.0009550301 0.0399006283
wilcox.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.w, conf.int = T)
  # p = 0.001166
  # CI = -172.66179  -77.09414

# Spring
res <- resid(lm(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but I disagree. Looks sigmoidal like the others
  # Not Normal
fligner.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.p)
  # p = 0.00418
b2 <- two.boot(sample1 = dna.inu.p$DNA_Yield_.ng.mg.[which(dna.inu.p$Antibiotics == "No Antibiotics")], sample2 = dna.inu.p$DNA_Yield_.ng.mg.[which(dna.inu.p$Antibiotics == "Antibiotics")], FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # CI = 1465, 4817
wilcox.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.inu.p, conf.int = T)
  # p = 0.000666
  # CI = -204.7277  -80.9147




### Saline

# Summer
res <- resid(lm(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.s))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # p = 0.03124
  # Not Normal
fligner.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.s)
  # p = 0.02736
b2 <- two.boot(sample1 = dna.sal.s$DNA_Yield_.ng.mg.[which(dna.sal.s$Antibiotics == "No Antibiotics")], sample2 = dna.sal.s$DNA_Yield_.ng.mg.[which(dna.sal.s$Antibiotics == "Antibiotics")], FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # CI = 558, 4199
wilcox.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.s, conf.int = T)
  # p = 0.003232
  # CI = -114.06252  -65.38241

# Winter
res <- resid(lm(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.w))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.w)
  # p = 9.318e-05
  # CI = 0.0005548553 0.0383869117
wilcox.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.w, conf.int = T)
  # p = 0.004329
  # CI = -130.44206  -49.43139

# Spring
res <- resid(lm(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.p))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Test says normal, but I disagree. Looks sigmoidal like the others
  # Not Normal
fligner.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.p)
  # p = 0.005882
b2 <- two.boot(sample1 = dna.sal.p$DNA_Yield_.ng.mg.[which(dna.sal.p$Antibiotics == "No Antibiotics")], sample2 = dna.sal.p$DNA_Yield_.ng.mg.[which(dna.sal.p$Antibiotics == "Antibiotics")], FUN = var, R = 9999)
boot.ci(b2, conf = 0.95, type = "bca")
  # CI = 488, 3185
wilcox.test(DNA_Yield_.ng.mg. ~ Antibiotics, dna.sal.p, conf.int = T)
  # p = 0.002165
  # CI = -175.58248  -78.96272




# Fligner tests
p.adjust(c(0.007437, 6.495e-06, 0.00418, 0.02736, 9.318e-05, 0.005882), "BH")
  # Inulin Summer = 0.00892440*
  # Inulin Winter = 0.00003897*
  # Inulin Spring = 0.00836000*
  # Saline Summer = 0.02736000*
  # Saline Winter = 0.00027954*
  # Saline Spring = 0.00882300*


# Wilcoxon tests
p.adjust(c(0.004101, 0.001166, 0.000666, 0.003232, 0.004329, 0.002165), "BH")
  # Inulin Summer = 0.004329*
  # Inulin Winter = 0.003498*
  # Inulin Spring = 0.003498*
  # Saline Summer = 0.004329*
  # Saline Winter = 0.004329*
  # Saline Spring = 0.004329*

```



### Plot errything
```{r}
### Prepare data for plotting
# DNA yield
dna.inu <- dna.c[which(dna.c$Substrate == "Inulin"),]
dna.sal <- dna.c[which(dna.c$Substrate == "Saline"),]

dna.inu$SeasonABX <- interaction(dna.inu$Season, dna.inu$Antibiotics)
dna.inu$SeasonABX <- ordered(dna.inu$SeasonABX, levels=c("Summer.No Antibiotics", "Summer.Antibiotics", "Winter.No Antibiotics", "Winter.Antibiotics", "Spring.No Antibiotics", "Spring.Antibiotics"))

dna.sal$SeasonABX <- interaction(dna.sal$Season, dna.sal$Antibiotics)
dna.sal$SeasonABX <- ordered(dna.sal$SeasonABX, levels=c("Summer.No Antibiotics", "Summer.Antibiotics", "Winter.No Antibiotics", "Winter.Antibiotics", "Spring.No Antibiotics", "Spring.Antibiotics"))

# Inulin
crds.inu$SeasonABX <- interaction(crds.inu$Season, crds.inu$Antibiotics)
crds.inu$SeasonABX <- ordered(crds.inu$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

# Saline
crds.sal$SeasonABX <- interaction(crds.sal$Season, crds.sal$Antibiotics)
crds.sal$SeasonABX <- ordered(crds.sal$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

# All
crds.rem$SeasonABX <- interaction(crds.rem$Season, crds.rem$Antibiotics)
crds.rem$SeasonABX <- ordered(crds.rem$SeasonABX, levels=c("Summer.No", "Summer.Yes", "Winter.No", "Winter.Yes", "Spring.No", "Spring.Yes"))

  


### DNA Yield

#tiff("abx.dna.tiff", width = 5, height = 2.5, units = "in", res = 600)
ggplot(dna.c, aes(x = Season, y = X.DNA._.ng.uL., color = SeasonABX, fill = SeasonABX)) +
  facet_grid(.~Substrate) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ylab("DNA yield (ng/uL)") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=10, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=10),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10, margin = margin(l = 5)),
        strip.text.x = element_text(size=11, face = "bold"),
        legend.position = "none")
#dev.off()



# Inulin AUC
abx.inu.auc.plot <- ggplot(crds.inu, aes(x = Season, y = AUC_sqrt, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Inulin AUC")  + 
  ylab(expression("AUC"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")


### Saline AUC
abx.sal.auc.plot <- ggplot(crds.sal, aes(x = Season, y = AUC_sqrt, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Saline AUC")  + 
  ylab(expression("AUC"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")


# Inulin AvgD
abx.inu.avgD.plot <- ggplot(crds.inu, aes(x = Season, y = AvgD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle(expression("Inulin Average"~~delta^13~"C"))  + 
  ylab(expression("Average"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")


### Saline AvgD
abx.sal.avgD.plot <- ggplot(crds.sal, aes(x = Season, y = AvgD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle(expression("Saline Average"~~delta^13~"C"))  + 
  ylab(expression("Average"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")




# Inulin MaxD
abx.inu.maxD.plot <- ggplot(crds.inu, aes(x = Season, y = MaxD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle(expression("Inulin Maximum"~~delta^13~"C"))  + 
  ylab(expression("Maximum"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")


### Saline MaxD
abx.sal.maxD.plot <- ggplot(crds.sal, aes(x = Season, y = MaxD, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle(expression("Saline Maximum"~~delta^13~"C"))  + 
  ylab(expression("Maximum"~~delta^13~"C"~"(%"[o]~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")




# Inulin MaxSlope
abx.inu.maxSlope.plot <- ggplot(crds.inu, aes(x = Season, y = MaxSlope, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Inulin Maximum Slope")  + 
  ylab(expression("Maximum Slope"~"(%"[o]~"hr"^-1~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")


### Saline MaxSlope
abx.sal.maxSlope.plot <- ggplot(crds.sal, aes(x = Season, y = MaxSlope, color = SeasonABX,
                                    fill = SeasonABX)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 2.5,
               position = position_dodge(0.7), stackratio = 0.5) +
  scale_color_manual(values = c("#c98b00", "#E69F00", "#004166", "#006299", "#00966d",
                                "#00bf8b")) +
  scale_fill_manual(values = c("#E69F00", "white", "#006299", "white", "#00bf8b",
                               "white")) +
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",
               color = "black", position = position_dodge(0.7), size = 0.5) +
  ggtitle("Saline Maximum Slope")  + 
  ylab(expression("Maximum Slope"~"(%"[o]~"hr"^-1~")")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_text(size=11, margin = margin(t = 7.5)),
        axis.title.y = element_text(size=11),
        axis.text.x = element_text(size=10),
        axis.text.y = element_text(size=10),
        plot.title = element_text(hjust = 0.5, size = 11),
        legend.position = "none")




# # Steal Season legend
# season.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = AUC_sqrt, color = Season, fill = Season)) +
#                             geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5,
#                                          position = position_dodge(0.7), stackratio = 0.5) +
#                             scale_color_manual(values = c("#c98b00", "#006096", "#00966d")) +
#                             scale_fill_manual(values = c("#E69F00", "#0072B2", "#00bf8b")) +
#                             theme(legend.title = element_text(size=10, face="bold"),
#                                   legend.text = element_text(size=10),
#                                   legend.margin = margin(t=1, unit='cm')))
# 
# 
# # Steal ABX legend
# abx.legend <- g_legend(ggplot(crds.inu, aes(x = Season, y = AUC_sqrt, fill = Antibiotics)) + 
#                          geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 1.5, 
#                                       position = position_dodge(0.7), stackratio = 0.5) +
#                          scale_fill_manual(values = c("black", "white"),
#                                            labels = c("Antibiotic-free", "Antibiotic-treated")) +
#                             theme(legend.title = element_text(size=10, face="bold"),
#                                   legend.text = element_text(size=10),
#                                   legend.margin = margin(b=1, unit='cm')))

```



### Save plots
```{r}
tiff("abx.delta.metrics.tiff", width = 6, height = 9, units = "in", res = 600)
grid.newpage()
pushViewport(viewport(layout=grid.layout(4,2, widths = c(1, 1))))

print(abx.inu.auc.plot, vp=viewport(layout.pos.row=1, layout.pos.col=1))
grid.text("A", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(abx.sal.auc.plot, vp=viewport(layout.pos.row=1, layout.pos.col=2))
grid.text("E", x=unit(0.063, "npc"), y=unit(0.95, "npc"),
          vp=viewport(layout.pos.row=1, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))



print(abx.inu.avgD.plot, vp=viewport(layout.pos.row=2, layout.pos.col=1))
grid.text("B", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=2, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(abx.sal.avgD.plot, vp=viewport(layout.pos.row=2, layout.pos.col=2))
grid.text("F", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=2, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))



print(abx.inu.maxD.plot, vp=viewport(layout.pos.row=3, layout.pos.col=1))
grid.text("C", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=3, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(abx.sal.maxD.plot, vp=viewport(layout.pos.row=3, layout.pos.col=2))
grid.text("G", x=unit(0.063, "npc"), y=unit(0.95, "npc"), 
          vp=viewport(layout.pos.row=3, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))



print(abx.inu.maxSlope.plot, vp=viewport(layout.pos.row=4, layout.pos.col=1))
grid.text("D", x=unit(0.063, "npc"), y=unit(1, "npc"), 
          vp=viewport(layout.pos.row=4, layout.pos.col=1), gp=gpar(fontsize=14,fontface="bold"))

print(abx.sal.maxSlope.plot, vp=viewport(layout.pos.row=4, layout.pos.col=2))
grid.text("H", x=unit(0.063, "npc"), y=unit(1, "npc"), 
          vp=viewport(layout.pos.row=4, layout.pos.col=2), gp=gpar(fontsize=14,fontface="bold"))


#season.legend$vp <- viewport(layout.pos.row=1:4, layout.pos.col=3)
#grid.draw(season.legend)
#abx.legend$vp <- viewport(layout.pos.row=1:4, layout.pos.col=3)
#grid.draw(abx.legend)
dev.off()
```


### Hib Dates
```{r}
### Load data ###

# Dates
dates <- read.csv('metadata_dates.csv')
dates_use <- dates[-which(dates$Season == "Summer"),]
rownames(dates_use) <- 1:nrow(dates_use)
dates_use <- dates_use[-13:-28,]
rownames(dates_use) <- 1:nrow(dates_use)
dates_use <- dates_use[-33:-40,]

# Remove outliers
#dates_use <- dates_use[-which(dates_use$ID == "W43"),]
dates_use <- dates_use[-which(dates_use$ID == "W20"),]
  # This is due to odd metagenome
#dates_use <- dates_use[-which(dates_use$ID == "W50"),]
#dates_use <- dates_use[-which(dates_use$ID == "P20"),]
#dates_use <- dates_use[-which(dates_use$ID == "P22"),]



# Add CRDS metrics
for(k in 1:nrow(dates_use)){
  ID <- dates_use$ID[k]
  rowUse <- which(crds.rem$ID == ID)
  dates_use$AvgD[k] <- crds.rem$AvgD[rowUse]
  dates_use$MaxD[k] <- crds.rem$MaxD[rowUse]
  dates_use$MaxSlope[k] <- crds.rem$MaxSlope[rowUse]
  dates_use$AUC_sqrt[k] <- crds.rem$AUC_sqrt[rowUse]
  dates_use$Baseline[k] <- crds.rem$Baseline[rowUse]
}
  
# Separate by Season
dates.spr <- dates_use[which(dates_use$Season == "Spring"),]
dates.win <- dates_use[which(dates_use$Season == "Winter"),]



### Spring
res <- resid(lm(Days_Hib ~ Antibiotics, dates.spr))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(Days_Hib ~ Antibiotics, dates.spr)
  # p-value = 0.9201
t.test(Days_Hib ~ Antibiotics, dates.spr)
  # p = 0.1215


res <- resid(lm(IBA.Hib ~ Antibiotics, dates.spr))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(IBA.Hib ~ Antibiotics, dates.spr)
  # p-value = 0.9449
t.test(IBA.Hib ~ Antibiotics, dates.spr)
  # p = 0.9588


res <- resid(lm(Num_IBA ~ Antibiotics, dates.spr))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(Num_IBA ~ Antibiotics, dates.spr)
  # p-value = 0.5191
t.test(Num_IBA ~ Antibiotics, dates.spr)
  # p = 0.4637



### Winter
res <- resid(lm(Days_Hib ~ Antibiotics, dates.win))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(Days_Hib ~ Antibiotics, dates.win)
  # p-value = 0.1999
t.test(Days_Hib ~ Antibiotics, dates.win)
  # p = 0.01295


res <- resid(lm(IBA.Hib ~ Antibiotics, dates.win))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(IBA.Hib ~ Antibiotics, dates.win)
  # p-value = 0.3048
t.test(IBA.Hib ~ Antibiotics, dates.win)
  # p = 0.4024


res <- resid(lm(Num_IBA ~ Antibiotics, dates.win))
hist(res)
qqnorm(res)
qqline(res)
shapiro.test(res)
  # Normal
var.test(Num_IBA ~ Antibiotics, dates.win)
  # p-value = 0.8388
t.test(Num_IBA ~ Antibiotics, dates.win)
  # p = 0.469

```
